### ISSUE TITLE
should Mobile Grade default to grade C?

### ISSUE THREAD

**Issue by bobbravo2** [serbanghita/Mobile-Detect#148]
Love the class - great work! 

Ok - so I'm writing some tests using the setUserAgent() method, and have yet to find a suitable string to make the MobileGrade() return Mobile_Detect::MOBILE_GRADE_C

I tried a bunch of user agent strings - non-sensical strings, MSIE 4.0, Windows Mobile 4.5 etc, and could not get any of them to return MOBILE_GRADE_C. 

My point with this issue, is that I believe it's more helpful to have a detection method that adds features as it detects known good devices, vs. having an unknown device automatically getting the B grade experience.

Does that make any sense?

**Comment by serbanghita** [comment]
Device grade is no longer relevant. I removed these helper methods from `7.4`
