### ISSUE TITLE
[Wordpress] WP Cache + Mobile Detect

### ISSUE THREAD

**Issue by serbanghita** [serbanghita/Mobile-Detect#180]
Hello,

Is there anyone interested in developing a plugin of Mobile Detect that works with WP Cache? I've heard about this before, but lately it was brought to my attention: https://twitter.com/petripottonen/status/413281101952466944

Is this possible server-side?

**Comment by topraf** [comment]
Posting here since the other ticket was closed - her @serbanghita , any news /hotfix for this issue with caching on W3 total cache? Thanks!

**Comment by pothi** [comment]
I haven't used W3 Total Cache plugin. But, if a full-page caching plugin uses the built-in `wp_is_mobile` function to detect mobile devices, https://wordpress.org/plugins/tinywp-mobile-detect/ can be used to tweak `wp_is_mobile` to work correctly for tablets. For example, WP Super Cache plugin uses `wp_is_mobile` function and it works flawlessly with the aforementioned plugin (that in turn uses Mobile Detect PHP library).

**Comment by topraf** [comment]
Hi @pothi, i'll try to use your plugin to do that but i'm not sure it solves the caching issue. I'll let you know
