### ISSUE TITLE
Browser incorrect

### ISSUE THREAD

**Issue by DaanBiesterbos** [serbanghita/Mobile-Detect#184]
Hi.  Thanks for all the great work. I found a issue with my Chrome browser.
When I visit http://demo.mobiledetect.net/ and check the results it says:
isChrome()  bool(false)

Then, at the bottom it does mention the webkit version.  And the chrome + safari version.

version(Chrome) string(12) "31.0.1650.63"
version(Safari) string(6) "537.36"
version(Webkit) string(6) "537.36"

Personally I'm not bothered with versions too much. But not being able to tell what browser the user is using does not sound like intented behaviour.

Kind Regards,
Daan Biesterbos

**Comment by serbanghita** [comment]
https://github.com/serbanghita/Mobile-Detect/issues/15#issuecomment-782725480

I experimented with this, see https://github.com/serbanghita/Mobile-Detect/tree/devel-3-workinprogress/lib, and it's very hard to maintain. I'll keep the a tight focus to Mobile Detect, and that is to detect the mobile environment and focus on the separation of mobiles vs tablets.
