### ISSUE TITLE
Social Media Bot UA strings

### ISSUE THREAD

**Issue by Paratron** [serbanghita/Mobile-Detect#190]
Hey,
I just tested a few bots of social media networks and thought they might be of interest for you.

You already have facebook in your detection class but as far as I can see the others are missing.

Find the UA strings in my gist here: https://gist.github.com/Paratron/8676518

greetings,
Chris

**Comment by WalterGR** [comment]
> Besides, a bot doesn't need a special page layout. The bot just indexes the text.

That is incorrect.  

"Finding more mobile-friendly search results"
https://developers.google.com/webmasters/mobile-sites/references/googlebot
