### ISSUE TITLE
Detects  Smart TV ?

### ISSUE THREAD

**Issue by treebhoph** [serbanghita/Mobile-Detect#203]
Now, users are use web browser on Smart TV .

SAMSUNG, LG, SONY, PANASONIC, PHILIPS, SHARP, TCL

**Comment by bato3** [comment]
another tv devices list: https://deviceatlas.com/blog/list-smart-tv-user-agent-strings

**Comment by jasperf** [comment]
Has a Smart TV or television screens as option been worked on since this last comment end 2018? Seems there has been no follow up. 4K or UHD screens are out and 8K screens are around the corner..

**Comment by serbanghita** [comment]
I'll keep the a tight focus to Mobile Detect, and that is to detect the mobile environment and focus on the separation of mobiles vs tablets.
