### ISSUE TITLE
add PHP version compatibility warning (for 2.x and 3.x)

### ISSUE THREAD

**Issue by serbanghita** [serbanghita/Mobile-Detect#209]
We have to add a PHP compatibility warning about `2.x` and `3.x` branches 
This is extremely important when we launch `3.x`

**Comment by jkosanovic** [comment]
I have been struggling to get Mobile_Detect working in my PHP site.
My view blade file has 
`require_once '/home/master/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php';
$detect = new Mobile_Detect;`

My app.php file has the following for the package service provider
`		 mobiledetect\mobiledetectlib\Mobile_Detect::class,`
and the following line for the alias
`		'Mobile_Detect' => mobiledetect\mobiledetectlib\Facade::class,`

I created a Facade.php file in the mobiledetectlib folder
`<?php

namespace mobiledetect\mobiledetectlib;

use Illuminate\Support\Facades\Facade as LaravelFacade;

/**
 * @see \Illuminate\Validation\Factory
 */
class Facade extends LaravelFacade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'Mobile_Detect';
    }
}
`
and I updated the composer.json file in the mobiledetectlib folder as seen below
`{
    "name": "mobiledetect/mobiledetectlib",
    "type": "library",
    "description": "Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the User-Agent string combined with specific HTTP headers to detect the mobile environment.",
    "keywords": ["mobile", "mobile detect", "mobile detector", "php mobile detect", "detect mobile devices"],
    "homepage": "https://github.com/serbanghita/Mobile-Detect",
    "license": "MIT",
    "authors": [
        {
            "name": "Serban Ghita",
            "email": "serbanghita@gmail.com",
            "homepage": "http://mobiledetect.net",
            "role": "Developer"
        }
    ],
    "require": {
        "php": ">=5.0.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.8.35||~5.7"
    },
    "autoload": {
        "classmap": ["Mobile_Detect.php"],
        "psr-0": {
            "Detection": "namespaced/"
        }
    },
	"extra": {
        "laravel": {
            "providers": [
                "mobiledetect\\mobiledetectlib\\Mobile_Detect"
            ],
            "aliases": {
                "Mobile_Detect": "mobiledetect\\mobiledetectlib\\Facade"
            }
        }
    },
    "archive": {
      "exclude": ["docs", "examples", "export"]
    }
}`

I updated the Mobile_Detect package from 2.8.33 to 2.8.34 successfully with composer.
My live site is www.americanpharoah.ca  You will see the error I get when you browse to it..... class Mobile_Detect not found   :(

**Comment by jkosanovic** [comment]
still fighting this today
more info...
The hosted service is running PHP 7.2 
I have updated the require_once line in my blade file to the following
require_once '/var/www/americanpharoah.ca/html/racehorses/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php';

Autoload_classmap file has...
    'Mobile_Detect' => $vendorDir . '/mobiledetect/mobiledetectlib/Mobile_Detect.php',
in the array
but  autoload_namespaces file only had
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
so I added the following line...
	'Mobile_Detect' => array($vendorDir . '/mobiledetect/mobiledetectlib'),
and I added the line...
use mobiledetect\mobiledetectlib\Mobile_Detect.php;
to my controller

**Comment by jkosanovic** [comment]
After running composer update last night, the home page no longer displayed the error regarding the missing Mobile_Detect class, instead the webpage is blank.  After running 'composer update' I checked the composer.json file in the mobiledetectlib folder and it reverted back to the original before I made any changes and the Facade.php file I created in that folder is gone.  Looking at the error.log file in the bootstrap folder it shows `[Thu Dec 05 21:13:44.795945 2019] [php7:error] [pid 10364] [client 209.202.75.15:11755] PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /var/www/americanpharoah.ca/html/racehorses/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:234\nStack trace:\n#0 /var/www/americanpharoah.ca/html/racehorses/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(397): Illuminate\\Support\\Facades\\Facade::__callStatic('replaceNamespac...', Array)\n#1 /var/www/americanpharoah.ca/html/racehorses/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(374): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#2 /var/www/americanpharoah.ca/html/racehorses/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(289): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#3 /var/www/americanpharoah.ca/html/racehorses/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(188): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse( in /var/www/americanpharoah.ca/html/racehorses/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 234
`

I will continue with this on Sunday. 
It may be a permissions issue on some of the folders perhaps.
However, I did see the the Riverskies\Laravel\MobileDetect\MobileDetectServiceProvider so I might try using that as well.
