### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by Netsurfer24** [serbanghita/Mobile-Detect#212]
Hi,

first of all my compliments for all your work!
But the usage is a bit cumbersome ...!

I mean why does one have to write:
$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'mobile') : 'desktop');
when it is quite clear that he wants to know the device type?
So why not: $deviceType = $detect->deviceType();

Same for OS, Browser, Browser Version and so on ...!

This really would help authors a lot.

BTW: The documentation, especially for the $detect->is('...') methods, leaves something to be desired.

I know that this feature request is somehow the same as #33.

Greetings
Gunther

**Comment by serbanghita** [comment]
We're going to stick with `isMobile` and `isTablet` because they suggest what this library actually is meant for.
The magic methods have been documented: https://github.com/serbanghita/Mobile-Detect/blob/5.x/Mobile_Detect.php#L26
