### ISSUE TITLE
Chrome/Safari/Opera are "seen" as each other

### ISSUE THREAD

**Issue by Tklaversma** [serbanghita/Mobile-Detect#215]
The following returns a float in Chrome (instead of false):

<pre>
$detect->version('Safari', 'float')
</pre>

To be exact:
I'm using Chrome 33.0.1750.149 on Mac. The line above outputs:

<pre>
537.36
</pre>

EDIT:
Also the following returns a float in Opera (instead of false):

<pre>
$detect->version('Chrome', 'float')
</pre>

To be exact again:
I'm using Opera 20 on Mac. The line above outputs:

<pre>
33.01750149
</pre>

EDIT 2:
Also the following returns a float in Safari (instead of false):

<pre>
$detect->version('Opera', 'float')
</pre>

To be exact again:
I'm using Safari 7.02 on Mac. The line above outputs:

<pre>
7.02
</pre>

**Comment by serbanghita** [comment]
`$detect->version(...)` should work fine now.
