### ISSUE TITLE
Detect default Android Browser

### ISSUE THREAD

**Issue by olafcm** [serbanghita/Mobile-Detect#217]
How to detect the Android stock browser?

Take for example:
"Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; GT-P5210 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30"

It's recognized as Android (isAndroidOS), but a browser type is missing in Mobile-Detect.

Since this is currently the most popular Android browser, something like isAndroidBrowser() would be very useful.

(More examples here: http://www.useragentstring.com/_uas_Android%20Webkit%20Browser_version_.php)

**Comment by serbanghita** [comment]
I'll keep the a tight focus to Mobile Detect, and that is to detect the mobile environment and focus on the separation of mobiles vs tablets.

The tablet `GT-P5210` was added to the detection script.
