### ISSUE TITLE
Add isTouch functionality

### ISSUE THREAD

**Issue by remithomas** [serbanghita/Mobile-Detect#259]
It's possible to add the functionality "isTouch" ?
Actually I'm using 

```
if( $detect->isMobile() || $detect->isTablet() ){
```

but some other devices have touch functionality like ASUS, how to do that for every devices?
thanks

**Comment by coderintherye** [comment]
Is it though? WurflCloud seems to managed it with getDeviceCapability(). It seems that most touch-capable devices have "touch" in the user-agent. Couldn't we try just a isTouch() method with a simple regex like:
"match": "*touch*"
Granted, I'm talking out of my league here, so if it is truly difficult then that's understandable, and the Modernizr.touch use makes sense

**Comment by serbanghita** [comment]
@coderintherye you cannot assert from User Agent that the device is touch sensitive.
