### ISSUE TITLE
An idea to improve your API

### ISSUE THREAD

**Issue by clement961** [serbanghita/Mobile-Detect#260]
In your next version, can you add the detection for smart TVs and video games consoles (portable and fixed) ? I think your API is the best but it would be better if you add these functions.

Edit : I'm sorry. I had not seen. A lot of subjects talks about this.

**Comment by serbanghita** [comment]
I'll keep the a tight focus to Mobile Detect, and that is to detect the mobile environment and focus on the separation of mobiles vs tablets.
