### ISSUE TITLE
Can this stuff detect xiaomi phone & tablets, which is very popular in China now

### ISSUE THREAD

**Issue by yixinrock** [serbanghita/Mobile-Detect#299]
Here you go : 
http://www.mi.com/en

**Comment by BobbyWibowo** [comment]
Sorry for bringing this up. Is there any custom detection method for Xiaomi phone? Such as the isSamsung() thing?
Also, here's my user agent for Xiaomi Mi3 with a Google Chrome:
`Mozilla/5.0 (Linux; Android 4.4.4; MI 3W Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36`
Seems like it's not available here: https://github.com/serbanghita/Mobile-Detect/blob/devel/tests/providers/vendors/Mi.php
