### ISSUE TITLE
mobile or tablet

### ISSUE THREAD

**Issue by poxa** [serbanghita/Mobile-Detect#309]
Hi Serban,

We need to be able to differentiate between mobiles and tablets. Is there a way to use this code to tell us that? Or at least to tell us that a device is mobile, along with its resolution. 

Thanks,
Roxana

**Comment by serbanghita** [comment]
Hi Alex,

Unfortunately those sites only show an iframe with your site embedded, that doesn't change or emulate anything but the `screen size`. You can test those site with http://demo.mobiledetect.net and see that you have a `desktop` user-agent. You need to use real emulators like http://www.browserstack.com
