### ISSUE TITLE
New 3rd party module

### ISSUE THREAD

**Issue by robinef** [serbanghita/Mobile-Detect#312]
Name : ua-lua 
Link : https://github.com/robinef/ua-lua
Description : 
ua-lua is a small lib written in LUA providing device type detection.
ua-lua is detecting mobile or tablet devices based on user-agent inside nginx daemon.

**Comment by robinef** [comment]
Just a small ping here, its still open and I cannot find my module in 3rd party list.

**Comment by serbanghita** [comment]
@robinef done, sorry I was off-radar for a period! Thank you!
