### ISSUE TITLE
Problems upgrading Mobile-Detect version from 2.5.3 to 2.8.11

### ISSUE THREAD

**Issue by rikinogues** [serbanghita/Mobile-Detect#313]
Hi,
I´m newby in PHP and I would need some help ... ;-)
I´m just upgrading the version of the Mobile-Detect on my server, from the 2.5.3 to the last one 2.8.11, because I´ve noticed that I can´t get the correct 'Browser Language' from some Android devices.
But I´m not sure if since all that time I need to change also the source code of aplications, calls to functions, (e.g. I´m using the Mobile_Detect() class, but I see that in the new version is deprecated..) 
What call to function should I use to fix that? Do you have a guide table to see which functions are deprecated and which one is the new function name to call?

Thanks in advance
Ricard

**Comment by serbanghita** [comment]
@rikinogues I think you need to scan `$_SERVER['HTTP_ACCEPT_LANGUAGE']`. I don't recall `Mobile_Detect` class ever dealing with the browser language detection aspect.
