### ISSUE TITLE
New 3rd party module for Processwire

### ISSUE THREAD

**Issue by justb3a** [serbanghita/Mobile-Detect#320]
[Processwire Mobile Detect](http://modules.processwire.com/modules/mobile-detect/) uses a lightweight PHP class for detecting mobile devices (including tablets). This Module extends the configuration  and sets the following parameters: `$config->deviceType` (phone, tablet or desktop), `$config->browser` (mobile browser), `$config->operatingsystem` (mobile operatingsystem) and `$config->device` (mobile device). These are accessible where ever you need them (such as other modules, templates).

**Comment by justonestep** [comment]
_just a little reminder_ :)

**Comment by serbanghita** [comment]
I know, I've been over my head with job related tasks. Sorry for the delay! :baby:

**Comment by chrisave** [comment]
Hello :),
Your lightweight PHP class, Mobile_Detect, has been mentioned several times in the ProcessWire Forums and there is a ProcessWire "3rd party module".
Could you please add it to the official list?
Thank you so much in advance!
Have a nice evening/day!
Christophe
