### ISSUE TITLE
isAndroidOS doesn't work with Firefox for Android

### ISSUE THREAD

**Issue by ghost** [serbanghita/Mobile-Detect#324]
When i use "isAndroidOS()" from Firefox for Android (with a Nexus 7, android 5.0), it return false.

**Comment by serbanghita** [comment]
@ThibaultModat did you report this on http://demo.mobiledetect.net ? Anyway I'm looking into the problem.

**Comment by serbanghita** [comment]
I tested this on Nexus 7 but with Android 4.4 and it was `true`.

**Comment by ThibaultModat** [comment]
It works just fine on http://demo.mobiledetect.net, sorry for the disruption.
Just one thing, on demo.mobiledetect.net, "isNexus() 	bool(false)" with my Nexus 7 5.0
