### ISSUE TITLE
[BUG] Wrong detect Windows Phone lastest update

### ISSUE THREAD

**Issue by redstrike** [serbanghita/Mobile-Detect#328]
Newest Windows Phone update causes wrong detect as an iPhone.

Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

**Comment by serbanghita** [comment]
@redstrike We're aware of this, can be fixed in the `3.0` branch only. The current `2.0` releases only aim at detecting `mobile` and `tablet` devices. Thanks for the heads-up
