### ISSUE TITLE
Desktop detection and get_browser

### ISSUE THREAD

**Issue by toneplex** [serbanghita/Mobile-Detect#33]
Since browscap doesn't have the ability to distinguish between a phone and a tablet, it would be very nice to replace browscap with mobile-detect.   Do you have any plans to add desktop detection, OS version, etc. to mobile-detect?

Specifically, my need would be for the following array:

Array
(
    [platform] => WinXP
    [browser] => Firefox
    [version] => 0.9
    [majorver] => 0
    [minorver] => 9
);

**Comment by serbanghita** [comment]
https://github.com/serbanghita/Mobile-Detect/issues/15#issuecomment-782725480

> I experimented with this, see https://github.com/serbanghita/Mobile-Detect/tree/devel-3-workinprogress/lib, and it's very hard to maintain. I'll keep the a tight focus to Mobile Detect, and that is to detect the mobile environment and focus on the separation of mobiles vs tablets.
