### ISSUE TITLE
$detect->isTablet() not working

### ISSUE THREAD

**Issue by poxa** [serbanghita/Mobile-Detect#330]
Hi there ($i trăiască $$$erban $$$efu' la bani!),
ăăă.. După cum zicea și colegul meu Alex într-un thread pe care l-ai închis și probabil că nu mai primești notificari pe el:

I'm using your script to differentiate between mobiles and tablets, but I'm having a problem in detecting the Table users.
The method $detect->isTablet() should return true if the user access the page from a tablet right?
I tested the function by using some online emulators like : http://tablet-emulator.org/ and http://mobiletest.me, and also by changing the user agent of the browser... But the method still returns false in all the cases.
Am I doing something wrong?

Thank you in advance ;)

Alex & Poxa

**Comment by serbanghita** [comment]
Hi Poxa!

Sorry, I was AFK for a while. The problem with these emulators is that they are just some iframes. Check the website http://demo.mobiledetect.net in both emulators to see that it's your User-Agent. That is why they cannot be detected.
You would have to use a real emulator like browserstack.com

**Comment by RayCietoR** [comment]
Hello and thank you for your answer

Your right about those wanna be emulators. I tried it with browserstack as you suggested and for some tablets indeed it worked. But, for example, for samsung galaxy tab 10 it didn't.

**Comment by serbanghita** [comment]
@RayCietoR no, it's a known problem at BrowserStack, some of the user-agents of those tablets contain no trace that that device is a tablet, but only a generic `Android sdk` user-agent. If you want to test the detection script use Crome -> Developers Tools -> Emulate and change the viewport and the user-agent string.
