### ISSUE TITLE
Medion Lifetab S7852 - bad detection

### ISSUE THREAD

**Issue by gizellos** [serbanghita/Mobile-Detect#331]
It says my device is both a mobile and a tablet. It is just a tablet in fact.
 Mozilla/5.0 (Linux; Android 4.4; Nexus 7 Build/KRT16M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.92 Safari/537.36

**Comment by Allan-iam** [comment]
A tablet is also considered mobile.

If you're targeting only mobile phones then you have do something like: If( isMobile && !IsTablet).

**Comment by gizellos** [comment]
Thank you for your reply. Yes, you are right I am argeting just mobile phones. It's a pity there is not a function like isPhone. Could you make it?

**Comment by Allan-iam** [comment]
You could make you own function :), but this should work.

Add it to the class.
 public function isPhone( ) {
            return ( $this->isMobile() && !$this->isTablet() );
}

I haven't tested it, but it's straight forward, it should work.
Good luck Buddy :)

**Comment by gizellos** [comment]
Thank you very much. I will try it. Have a nice day.

**Comment by serbanghita** [comment]
@Allan-iam thanks for the assist! :+1: 

@gizellos Why is this isssue called "Medion Lifetab S7852"? Is that in the first post the User-Agent? It looks like a Nexus 7, if not can you share the User-Agent? 10x!

**Comment by gizellos** [comment]
@serbanghita I sent it from the Medion Lifetab. I just copied the user-agent from the demo. I didn't notice the bad user-agent until now. So maybe it was really bad detection in the end.

I don't have the tablet by me now so I cannot share it again but it is 100% it was the user-agent the demo generated for me. I have never had the nexus tablet.

By the way I use Mobile Detect module for Nette Framework and they made for me the functions isPhone and isNotPhone so I am fully satisfied now. The module is here if you are interested - https://github.com/iPublikuj/MobileDetect

**Comment by gizellos** [comment]
BTW: when I thought the detection the tablet as a mobile device was bug, I tried to check the demo with more Medion tablets. I sent the feedback with them so if you check a log from the feedback page you can see the user-agents from them (I suppose you save the user-agents togeter with the feedback).
