### ISSUE TITLE
Detect Chrome in Mobile/Tablet 

### ISSUE THREAD

**Issue by miguelpedregosa** [serbanghita/Mobile-Detect#334]
I have a BQ Aquaris E10, a 10 inches tablet by a popular spanish devices brand. Mobile-Detect detects it as a mobile phone. 

The user agent is:

Mozilla/5.0 (Linux; Android 4.4.2; Aquaris E10 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36

Chrome uses the word "mobile"  for mobile devices and no word for tablets in Android/iOS. More info available in https://developer.chrome.com/multidevice/user-agent

**Comment by xgdgsc** [comment]
I also have this issue.

**Comment by serbanghita** [comment]
This is already solved on the latest `2.8.15` release. Thanks for the report!
@miguelpedregosa :beers:
