### ISSUE TITLE
Sony Xperia Z3 Compact is detected as tablet

### ISSUE THREAD

**Issue by krassx** [serbanghita/Mobile-Detect#341]

**Comment by constb** [comment]
Same story about Sony Xperia Z1 Compact. User agent is ``Mozilla/5.0 (Linux; Android 4.4.4; D5503 Build/14.4.A.0.157) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Mobile Safari/537.36``

I believe it's D5803 for Z3 Compact, D6603 for big Z3, D5103 for T3, D2533 for C3, etc.

Can we use ``/D[0-9]{3}3/`` as a generic xperia marker?
