### ISSUE TITLE
Add Blackphone/PrivatOS support

### ISSUE THREAD

**Issue by MathRobin** [serbanghita/Mobile-Detect#345]
Is it possible to add support of blackphone/privatOS support please ?

https://blackphone.ch/privat-os/

**Comment by MathRobin** [comment]
Can't find the user-agent, just find this http://mail-archives.apache.org/mod_mbox/incubator-devicemap-commits/201408.mbox/%3CJIRA.12732050.1407256440823.46081.1407527591604@arcas%3E

**Comment by sorinstanila** [comment]
Also I have find this: https://issues.apache.org/jira/browse/DMAP-66 -  I belive that this phone has a spoofed user agent "User-Agent: <???>". in that case detection is impossible

**Comment by MathRobin** [comment]
Ok... Seems that it will be complicated, it's True... We can close I guess
