### ISSUE TITLE
HTC One M8 Detected as Tablet. 

### ISSUE THREAD

**Issue by James-Azzopardi** [serbanghita/Mobile-Detect#353]
On the HTC One M8 is returning as a tablet instead of mobile.

Thanks

**Comment by serbanghita** [comment]
I have added 300 new tests for HTC One and all pass. Could you be more specific and provide an user-agent? Thanks

**Comment by kevstor996** [comment]
I just noticed this using my HTC M8 - the user agent info is:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/33.0.0.0 Safari/534.24

hoping this may help? Thx
