### ISSUE TITLE
Detection via Googlebot

### ISSUE THREAD

**Issue by ivankaban** [serbanghita/Mobile-Detect#355]
Hi! 
From here:
Google webmaster tools -> Scanning -> See like Googlebot -> choose: for mobile devices cHTML
As a result - this Googlebot is NOT detect like mobile.
I think this may cause problems for SEO goals.
What do you think about it?

**Comment by nicktacular** [comment]
It's not an SEO issue. It's only an issue for Google to be able to mark that site as having different content for mobile targets.

**Comment by ivankaban** [comment]
@nicktacular yes, that's it, wrong mark from Google may cost positions in SERP, because content don't appropriate device's type

**Comment by nicktacular** [comment]
I think what we should probably do is separate bots into 2 separate categories for detection. I think what is most appropriate is for the bot to return true for both bot and mobile checks. @serbanghita any objections to this?

**Comment by WalterGR** [comment]
Google shows different results depending on the user's device.

If a website uses this library to determine whether a "user" is on a mobile device or not and adjusts content accordingly, detecting the GoogleBot UAs incorrectly and displaying an inappropriate page  tells Google, "Yeah, this site doesn't work properly on [mobile/tablet/desktop]."

GoogleBot *checks whether pages work well on the devices it "uses" to view pages*.  If it detects that a site has usability issues on mobile devices, they will a. send you notifications and email if you've signed up for Google Webmaster Tools (IIRC) and b. choose whether to show those pages or not in the search results.

So this is a matter beyond Google marking sites as having different content for mobile targets.

See also

#190 - Social Media Bot UA strings (Jan 2014)
#208 - Update the bot regex (Feb 2014)
#211 - Error detection for Mobil: cHTML (Feb 2014)

**Comment by carlosbuenosvinos** [comment]
+1 here. googlebot-mobile, bingbot-mobile should be added.

**Comment by belgianwolfie** [comment]
+1

**Comment by BugHunter2k** [comment]
We are using mobile-detect on our site and having no issues with google detecting the mobile version. Web Mastertools and the google Mobile-Friendly-Test reports the pages as mobile-friendly.
May be you have to send a "Vary: User-Agent" header to give google a hint. (see: https://developers.google.com/webmasters/mobile-sites/mobile-seo/configurations/dynamic-serving)

**Comment by petervansark** [comment]
Unfortunately the "Vary: User-Agent" header didn't solve the problem for me.
Can you show a working example passing the Mobile-Friendly-Test?

**Comment by petervansark** [comment]
The script works fine and passes the Mobile-Friendly-Test without any problems. The demo-page passed with flying colors.

If a website does pass, take a closer look at the implementation. This fixed the issue for me.
Check the code in the demo-page if needed.

**Comment by J5Dev** [comment]
Hi @petervansark You say that the demo page & script works, could you be more specific as to where they are.

We have ran into this issue, and until a solution is in place i have been struggling with a fix.

**Comment by JessycaFrederick** [comment]
Was there any resolution on this? When I Fetch & Render at Google, using the VARY header, GoogleBot Mobile (which identifies as an iPhone) is still getting the default (desktop in this case) version of the page. Is there a way to add a detector for is_GoogleBot and is_GooglebotMobile? (This would be better if it applied to the whole group of identified UA, not just Google, I just wanted to use it as an example)
