### ISSUE TITLE
How to include correctly Mobile Detect - installed via composer

### ISSUE THREAD

**Issue by gioialorusso** [serbanghita/Mobile-Detect#357]
Hi. I have an issue including your library. I installed it via composer in my project, so it is in my vendor folder. I have a certain file in another folder which wants to use mobile detect. So, if I write on the top of the file 
use Mobile_Detect
it works, but the code gives me continuos warning, saying that:
Warning: The use statement with non-compound name 'Mobile_Detect' has no effect (File: /var/www...)
I don't want these warning, especially because my system logs them. So, I replaced the use statement with this:
include_once(dirname(__FILE__).'/../vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php');
but I don't like it so much, I want to include your library as all the libraries I include via composer: with the use statement and the library name.
Maybe I'm missing something in my use statement. Can you help me?
Thank you. I like so much your work: it is very complete and useful.
Greetings from Italy. Gioia

**Comment by nicktacular** [comment]
Your use statement should be this:

```php
<?php
use Detection\MobileDetect;
```

Or, if you wish to have it named `Mobile_Detect` then just:

```php
<?php
use Detection\MobileDetect as Mobile_Detect;
```

**Comment by gioialorusso** [comment]
Thank you. It works perfectly.
Have a nice day!
