### ISSUE TITLE
Detect mobile only & detect high DPI screens & connection

### ISSUE THREAD

**Issue by fschleifenbaum** [serbanghita/Mobile-Detect#359]
Hello,

Is it possible to detect mobile phones only? Currently isMobile() is for tablet and phones. I'd like to have a statement for phones only. Also it would be nice to see if the user agent has a high resolution (retina) screen.

Case: shop images; low resolution on phones, normal res on default, double res on retina. Always retina when on wifi, always low when on other connections/4g...

**Comment by serbanghita** [comment]
@fschleifenbaum this can be achieved with media queries client-side.

```css
@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
only screen and (min--moz-device-pixel-ratio: 1.5),
only screen and (-o-device-pixel-ratio: 3/2), 
only screen and (min-device-pixel-ratio: 1.5) {

    //high resolution images go here

}
```

https://github.com/serbanghita/Mobile-Detect/issues/201
