### ISSUE TITLE
New Chrome Browser (Version 41.0.2272.76 m) identified as phone on PC

### ISSUE THREAD

**Issue by amir0220** [serbanghita/Mobile-Detect#360]
Please specify the User-Agent. Go to http://is.gd/mobiletest and copy-paste it here.

Mobile_Detect v. 2.8.11
The lightweight PHP class for detecting mobile devices.
This is a computer. Your UA is Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by serbanghita** [comment]
@amir0220 are you sure you're using the latest version? I just tested with the latest chrome:
UA: `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36`
Result: `This is a computer.`

**Comment by serbanghita** [comment]
https://github.com/serbanghita/Mobile-Detect/issues/358

**Comment by amir0220** [comment]
I was having this issue with older version of Mobile_detect (2.6). Updated to latest version (2.8.11) and the issue was resolved in case some other people run into this issue as well.

THanks for your quick response tho.
