### ISSUE TITLE
Recognized erroneously as mobile browser

### ISSUE THREAD

**Issue by sergiozia** [serbanghita/Mobile-Detect#362]
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by serbanghita** [comment]
Cannot reproduce, code used:

```
<?php
include_once 'Mobile_Detect.php';

$detect = new Mobile_Detect();
$detect->setUserAgent('Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:36.0) Gecko/20100101 Firefox/36.0');
var_dump($detect->getScriptVersion());
var_dump($detect->isMobile());
var_dump($detect->isTablet());
```

**Comment by sergiozia** [comment]
Please see the screenshot here attached

Regards,
Sergio

2015-03-11 14:52 GMT+01:00 Serban Ghita <notifications@github.com>:

**Comment by sergiozia** [comment]
If I use your test code :

include_once 'Mobile_Detect.php';
$detect = new Mobile_Detect();
$detect->setUserAgent('Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:36.0) Gecko/20100101 Firefox/36.0');
var_dump($detect->getScriptVersion());
var_dump($detect->isMobile());
var_dump($detect->isTablet());

Result browsed with my Firefox 36 under Linux Ubuntu 12.04 :
"2.8.11"
bool(true)
bool(false)

Same test browsed with Firefox 36 under WinXP:
"2.8.11"
bool(false)
bool(false)

is detected user-agent really overwrited by the setUserAgent() method ?

**Comment by serbanghita** [comment]
@sergiozia yes it should, can you provide me with full HTTP headers of your request? I cannot reproduce this.

**Comment by sergiozia** [comment]
Please :

Request :
```
GET / HTTP/1.1
Host: demo.mobiledetect.net
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:36.0) Gecko/20100101 Firefox/36.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,text/vnd.wap.wml;q=0.6
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Cookie: PHPSESSID=e6506c2f930655b3478dd436ae881349
Connection: keep-alive
Cache-Control: max-age=0
```
Response:
```
HTTP/1.1 200 OK
Date: Fri, 13 Mar 2015 14:33:04 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 4676
Keep-Alive: timeout=3, max=80
Connection: Keep-Alive
Content-Type: text/html
 ```
Result to the screenshot here attached
![screenshot](https://cloud.githubusercontent.com/assets/11424496/6640534/68809548-c998-11e4-96ae-97549b8f4574.png)

**Comment by sergiozia** [comment]
I hope that the "Accept" header is probably the problem, it contains ",text/vnd.wap.wml;q=0.6"
Perhaps an installed plugin but I don't find this :-/

**Comment by serbanghita** [comment]
@sergiozia yes, the `mobile` is triggered by `text/vnd.wap.wml`, this is strange, I wonder if this is something that has to do with the OS or some plugins

**Comment by sergiozia** [comment]
YESSS !!
I've found in my "about:config" that the "network.http.accept.default' key was changed, perhaps by a previously installed plugin.
I replaced by the default key and... it works now !!

Sorry for the inconvenience and thanks for your contribution

**Comment by serbanghita** [comment]
I found this so far http://stackoverflow.com/questions/7357368/firefox-defaulting-to-several-mobile-websites

**Comment by sergiozia** [comment]
It's exactly I've done !
Thanks and congratulations for your work, it's a great library :)
