### ISSUE TITLE
Google Chrome 41

### ISSUE THREAD

**Issue by atournayre** [serbanghita/Mobile-Detect#365]
Hi,

Chrome 41 is detected as à mobile.

Here are the user agents tested :

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

Thanks for your feedback.

**Comment by jeanmichel71** [comment]
update to last version, fixed it for me...

**Comment by atournayre** [comment]
yes, it's fixed with the last version.

thanks !
