### ISSUE TITLE
iPhone safari and desktop safari different detected

### ISSUE THREAD

**Issue by GregMcMahan** [serbanghita/Mobile-Detect#366]
Here's the PHP I have included in my page:

include_once 'scripts/Mobile_Detect.php';
$detect = new Mobile_Detect;
$device = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'desktop');
if (($device == "tablet") || ($device == "phone")) { $device = "mobile"; }

$browserType = ($detect->isSafari() ? ($detect->isIE() ? 'ie' : 'safari') : 'generic');

echo "
";

On my iphone safari it shows as $browserType: safari, as expected. On my laptop/desktop computer it shows $browserType: generic. 

What am I missing here?

**Comment by serbanghita** [comment]
Hi @GregMcMahan 

I know my answer comes late, but here is the explanation. `Mobile_Detect` is currently intended to only detect `mobile` browsers, not the regular ones. We're upgrading the script in the `3.0.0` to make it a fully featured device detection to accommodate this.

Thanks for using the library!
