### ISSUE TITLE
Issues with Internet Explorer 11

### ISSUE THREAD

**Issue by kevinwarren** [serbanghita/Mobile-Detect#369]
Hi,

Not sure if it's just me or whatever but on my Windows 8.1 PC this is my user agent string when using IE 11:

     Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko

isIE() returns false & the version() function returns versions for Trident & Windows NT

I've also got a PC with Windows 10 Tech Prev on it. I have similar issues only it thinks IE is Chrome v 39!!! However it does pick up the Windows NT version as 10.0 which is correct. Don't know what the user agent is but can get a copy if desired. Again not sure it's me or not but similar problems on 2 pcs with IE?!

FYI check out a side project I pulled together at http://www.detectdevice.com :-)

**Comment by kevinwarren** [comment]
Ok It's not me!

https://msdn.microsoft.com/en-us/library/ie/hh869301(v=vs.85).aspx

**Comment by kevinwarren** [comment]
Something like this will detect IE 11:

     if (preg_match('/Edge\/12.0/', $_SERVER['HTTP_USER_AGENT'])) {
     	$browser = 'Internet Explorer 11';
     } elseif ($detect->version('Trident') !== false && preg_match('/rv:11.0/', $_SERVER['HTTP_USER_AGENT'])) {
     	$browser = 'Internet Explorer 11';
     }

**Comment by serbanghita** [comment]
@kevinwarren good find! :+1: Thanks for the heads-up!
Nice project you have there, we're also moving towards a device detection solution.

Thanks for the code, i'm looking over the link and get back with a solution.

**Comment by AdrienDS** [comment]
@serbanghita Hi, do you plan on releasing a version with this fix anytime soon ?

**Comment by serbanghita** [comment]
Yes, I'm trying to release a new minor version this weekend. Thanks for the heads-up

**Comment by AdrienDS** [comment]
Thank you!  we're looking forward to it.

**Comment by serbanghita** [comment]
`isIE` and `version` show work now on IE. Check `2.8.13`

**Comment by usb248** [comment]
`isIE` return false in Internet explorer 11 on windows 10 ..............
