### ISSUE TITLE
New 3rd party module

### ISSUE THREAD

**Issue by wescleveland56** [serbanghita/Mobile-Detect#370]
Name: WP247 Body Classes

Link: https://wordpress.org/plugins/wp247-body-classes/

Description: Add unique classes to the &lt;body&gt; tag for easy styling based on various attributes (archive, user, post, mobile) and various WordPress "is" functions. Mobile attributes include type of device, Operating System, Browser, etc. Examples: <strong>.is-mobile</strong>, <strong>.is-not-mobile</strong>, <strong>.is-tablet</strong>, <strong>.is-ios</strong>, <strong>.is-not-ios</strong>, <strong>.is-androidos</strong>, <strong>.is-chromebrowser</strong>.

**Comment by serbanghita** [comment]
:+1: I'm working on adding this to the front page

**Comment by wescleveland56** [comment]
Would seek your opinion on one concern I have. Different WordPress plugins could be using different versions of this script. As an example, I noticed that the <strong>WordPress Mobile Detect</strong> plugin is using Mobile-Detect version 2.5.8 and the <strong>mobble</strong> plugin is using Mobile-Detect version 2.7.6. <strong>WP247 Body Classes<plugin> is using Mobile-Detect version 2.8.12. In order to avoid conflicts with other plugins, and to be able to control issues for my plugin, my solution was to change the class name from <strong>Mobile_Detect</strong> to <strong>WP247_Mobile_Detect</strong> in the version of Mobile-Detect that is included with my plugin. I don't think this is the best long-term approach and was wondering if you had any thoughts on the subject.

**Comment by serbanghita** [comment]
@wescleveland56 I've added the project to the front page. I wrote an answer to you several times but my kid deleted them before I submitted them to Github :)

We though about the issue with the WP modules that are using multiple versions of Mobile_Detect and are generating conflicts. The only way we can normalize this is to release an official `Mobile Detect WP module` that exposes the core methods to Wordpress. Each module that need mobile detection will have to implement the `Mobile Detect WP module` as a dependency. 
A drawback would be that not every module developer would want to add another module as a dependency, but if we market it well, it might become something "official".
This way when we update the module `Mobile Detect WP module` with the latest version, say 2.8.12, everybody benefits from that.

Let me know your thoughts, if you have any further ideas.

**Comment by wescleveland56** [comment]
@serbanghita. Haha, I love it. Aren’t kids great? Give ‘em a hug for making my day ;). You have expressed my thoughts exactly about making a single common plugin available for everyone. I would be happy to help with that effort if you want. I see some additional drawbacks for plugin developers who rely on a common version, namely:

 

·         What happens when the “official” common plugin has a failure that causes the developers plugin to fail? The developer has no control over how long his/her plugin will be down.

·         The plugin developer will need to account for when the “official” common plugin has been inactivated (for whatever reason) to avoid program errors when the Mobile_Direct class doesn’t exist.

·         What happens when an unofficial version of the class is created before the “official” version is executed? Not just a potential nightmare for plugin developers relying on the “official” common version, but a potential problem to be solved by the “official” common plugin as well.

 

So, here’s a thought: Perhaps the “official” common version could implement class WPMD_Mobile_Detect. Plugin developers can use the “official” common version, or a version they include with their plugin that implements class Mobile_Detect (or whatever else they want to call it as long as it isn’t WPMD_Mobile_Detect), or they could use both. This way, too, I can implement my plugin without requiring the “official” common WPMD plugin and can make it optional for my plugin users.

 

Here’s how I think I personally would implement it:

 

·         In my code:

 

If ( true === $myoptions[ ‘use-common-mobile-detect’ ] and class_exists( ‘WPMD_Mobile_Detect’ ) )

$this->mobile_detect = new WPMD_Mobile_Detect();

Else

{

                require_once dirname( __FILE__ ) . "/mobile-detect/Mobile_Detect.php";

                $this->mobile_detect = new WP247_Mobile_Detect();

}

 

·         If a problem arises with the “official” common WordPress Mobile_Detect plugin and it is not quickly resolved, I have 2 choices:

1.       Disable the “official” common plugin.

2.       In my plugin’s admin panel, set the ‘use-common-mobile-detect’ option to False.

Either way, my code still works but perhaps with an older version of Mobile_Detect.

 

We could then promote this as the preferred method of using Mobile_Detect in WordPress.

 

Your thoughts?

 

 <mailto:wes@clevemail.net> Wes

**Comment by serbanghita** [comment]
1. Don't worry about faulty releases, we cannot break stuff because we have integration tests, and until now, we didn't have any major problems with the releases. We keep compatibility with the important methods like `isMobile()` and `isTablet()`

2. I don't see any issues with existing plugins that already have `Mobile_Detect` class declared. We're going to declare our class in a namespace like `\WPMD\Mobile_Detect`. I know Wordpress doesn't use namespaces yet ... but we can.

3. Regarding the marketing of the official module, we can advertise it better than any existing module. We would start spreading the news between existing modules and talk with the authors.

4. We would like to do this along with the new release of `MobileDetect` `3.0.0` which is under the `MobileDetect` namespace.

I could start a new GitHub project with WPMD module and you can be the first "client" with WP247 Body Classes and see how it goes ... you could be in charge with updating the module on the Wordpress.org site after each release ...

**Comment by serbanghita** [comment]
Btw, check this also https://github.com/serbanghita/Mobile-Detect/issues/180

**Comment by wescleveland56** [comment]
Noticed there is a WP Mobile Detect plugin out there. Suggest we go with something like WordPress Mobile Detect Common (WPMDC namespace) to avoid potential future collisions. Maybe it doesn't matter. I will be glad to be the first client (spelled guinea pig?). Happy to get it onto WP.org and keep it current. Just let me know what/when I can do.
