### ISSUE TITLE
Support for windows 8.1

### ISSUE THREAD

**Issue by savdeep** [serbanghita/Mobile-Detect#373]
Do we have support for windows 8.1 in current release? I am got a response as androidOs for windows 8.1 case.
Please suggest.

**Comment by serbanghita** [comment]
@savdeep  not yet, we are working on that on the new `3.0` that will be announced soon. In the current `2.x` releases we are only focusing on detecting `mobile` and `tablet` devices.

Thanks for bringing this up!

**Comment by savdeep** [comment]
@serbanghita, that is great. But, i was talking about windows 8.1 on Nokia Lumia mobile.

**Comment by serbanghita** [comment]
@savdeep you mean `isWindowsPhoneOS` is returning false for that? Please provide me with an user-agent.

**Comment by savdeep** [comment]
Yes, it is returning false.
Plus, i think this pull request https://github.com/serbanghita/Mobile-Detect/pull/372 must have resolved this issue. :+1: 
Kindly tell me which tag to update to ?

**Comment by savdeep** [comment]
@serbanghita I can you please update when this pull request would be merged? https://github.com/serbanghita/Mobile-Detect/pull/372

**Comment by serbanghita** [comment]
Done in `2.8.13`
