### ISSUE TITLE
Not working in code in included file

### ISSUE THREAD

**Issue by dizplayy** [serbanghita/Mobile-Detect#374]
Hello, I am developing a site and i have this anomaly: there is a file index.php in root with only the detenction code, and the redirect works. Then there is a folder ENG / with inside some page templates that include (php include();) themselves in the head a header.php. The header.php have the detection code befor of all  (before <doctype>) . Well, if I open one of the templates (with the header.php included) the redirect does not work, but if I open directly header.php the redirect is ok. 
What can cause this issue?

**Comment by serbanghita** [comment]
@dizplayy you might have a classic error of 'headers already sent'. check for white spaces BEFORE header.php
