### ISSUE TITLE
The local cache is not cleared when using the setUserAgent in 2.8.12

### ISSUE THREAD

**Issue by kuthz** [serbanghita/Mobile-Detect#375]
example:
 $user_agents = array(
            'android' => 'Mozilla/5.0 (Linux; Android 4.2; Nexus 7 Build/JOP40C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Safari/535.19',
            'iphone6' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A523 Safari/8536.25',
            'blackberry' => 'Mozilla/5.0 (BB10; Touch) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.0.9.2372 Mobile Safari/537.10+'
        );
        $mobile_detect = new \Detection\MobileDetect();

        foreach($user_agents as $user_agent)
        {
            $mobile_detect->setUserAgent($user_agent);
            var_dump($mobile_detect->isAndroidOS());
        }

**Comment by serbanghita** [comment]
I need to write a test for this. It might be from a pull request that I've merged.
 Meanwhile, do you have any time to look into this? Check https://github.com/serbanghita/Mobile-Detect/pull/308

**Comment by serbanghita** [comment]
@kuthz thanks a lot, when I accepted #308 without unit tests.
