### ISSUE TITLE
Xperia SP detected as a tablet

### ISSUE THREAD

**Issue by alexandernst** [serbanghita/Mobile-Detect#378]
This is the UA of my Xperia SP (Cyanogen Mod 11)

~~~
[30/Mar/2015:21:13:48 +0200] "GET / HTTP/1.1" 200 2521 "-" "Mozilla/5.0 (Linux; Android 4.4.4; Xperia SP Build/KTU84Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36" 
~~~

**Comment by alexandernst** [comment]
My fault, it's working fine here http://demo.mobiledetect.net/ , so it must me something wrong in my code.

**Comment by alexandernst** [comment]
I found the problem. It is Mobile-Detect's fault.
My phone is detected correctly with 2.8.11, but with 2.8.12 it is detected as a tablet.

**Comment by serbanghita** [comment]
Added the user-agent to the test suite and it pass. `isMobile` is `true` and `isTablet` is `false`
