### ISSUE TITLE
get API

### ISSUE THREAD

**Issue by forza020** [serbanghita/Mobile-Detect#379]
Hello,

Any chances to implment such API:
```
$mobile->getBrowser();  //  return 'IE'
$mobile->getOs(); // return 'WindowsPhoneOS'
$mobile->getDeviceName(); // return 'Nokia'
```
Thanks

**Comment by serbanghita** [comment]
@forza020 Yes in `3.0.0`, we're working on this. We will attempt to release a new API in July with all these features. Thanks for the interest. I can keep you updated when the beta is out.
