### ISSUE TITLE
Parsing device name out of User Agent

### ISSUE THREAD

**Issue by littleneotrix** [serbanghita/Mobile-Detect#380]
Hi,
I was wondering... is it possible to get via this plugin the device name from the user agent.
For example If my user agent is:
Mozilla/5.0 (Linux; Android 5.1; Nexus 5 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.0.0 Mobile Safari/537.36

It'll return: Nexus 5 ?

Thanks.

**Comment by serbanghita** [comment]
Hi @littleneotrix 

Not yet, we're working on this on `3.0.0` version.
I'm glad that there is interest in this direction. I'll let you know when we release the beta. Thanks!
