### ISSUE TITLE
Onda Tablet not detected as a tablet

### ISSUE THREAD

**Issue by AdrienDS** [serbanghita/Mobile-Detect#384]
Onda Tablet (V975i) is not detected as a tablet when browsing on chrome, but it is on Firefox : 

User agent in **Chrome** : Mozilla/5.0 (Linux; Android 4.2.2; **V975i** Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.108 Safari/537.36
User agent in **Firefox** : Mozilla/5.0 (Android; **Tablet**; rv:37.0) Gecko/37.0 Firefox/37.0

V975i : http://www.onda.cn/Support/Search.aspx?keyword=v975i
Constructor website (cn) : http://www.onda.cn/
List of onda tablets (en) : http://www.onda-tablet.com/buy-android-onda.html?dir=desc&order=price

**Comment by serbanghita** [comment]
Done in `2.8.13`. Added Onda Tablets. Thanks for the details, if you find any new Onda user-agents please let me know.
