### ISSUE TITLE
Somewhat confusing instruction

### ISSUE THREAD

**Issue by FrankConijn** [serbanghita/Mobile-Detect#385]
Hello folks, 

Great project! However, the instruction on the demo page is quite easily misunderstood. It says: "Before sending an answer double check if you are using the browser in 'Desktop mode'." That may suggest to people for whom English is not their native language, or who read too fast, that one should have the browser in Desktop mode.  

A better instruction would be: "Before sending an answer double check that you are using the browser in its normal mode, not in 'Desktop mode'." This instruction may save you quite a number of incorrect reports of faulty results.

**Comment by serbanghita** [comment]
:+1:

**Comment by serbanghita** [comment]
Done in `2.8.13`. Thank you!
