### ISSUE TITLE
Parent dir

### ISSUE THREAD

**Issue by szepeviktor** [serbanghita/Mobile-Detect#386]
Please consider `dirname( dirname( ...` instead of the current code.
https://github.com/serbanghita/Mobile-Detect/blob/master/namespaced/Detection/MobileDetect.php#L20

**Comment by serbanghita** [comment]
@szepeviktor could you post a pull request?

**Comment by szepeviktor** [comment]
https://github.com/serbanghita/Mobile-Detect/pull/387/files
