### ISSUE TITLE
Some troubles with detection.. :)

### ISSUE THREAD

**Issue by IlyaVorozhbit** [serbanghita/Mobile-Detect#390]
Dont know why, but:

        if( $this->mobileDetect->isMobile() && !$this->mobileDetect->isTablet() ){
            $this->layout = '//layouts/mobile';
        }

Is not work for me. [for Iphones or any others phones]

I must do $this->layout = '//layouts/mobile' before Mobile_Detect starts working, an than, if we detect a tablet device, we overrides layout;

Something like this:

        $this->layout = '//layouts/mobile';

        if( !$this->mobileDetect->isMobile() && $this->mobileDetect->isTablet() ){
            $this->layout = '//layouts/tablet';
        }

Instead of:

        if( $this->mobileDetect->isMobile() && !$this->mobileDetect->isTablet() ){
            $this->layout = '//layouts/mobile';
        }

        if( !$this->mobileDetect->isMobile() && $this->mobileDetect->isTablet() ){
            $this->layout = '//layouts/tablet';
        }

Thanks, and have a good day!

**Comment by serbanghita** [comment]
Hi @IlyaVorozhbit 
Thanks for using Mobile Detect!

It think the problem here is because a tablet will trigger both `$this->mobileDetect->isMobile() == true` and `$this->mobileDetect->isTablet() == true`

I think the code should look like this:

```php
    $this->layout = '//layouts/classic';

    if ($this->mobileDetect->isMobile()){
        $this->layout = '//layouts/mobile';
    }

   if ( $this->mobileDetect->isTablet() ) {
        $this->layout = '//layouts/mobile';
   }
```

An iPhone should trigger `$this->layout = '//layouts/mobile';` line only.
