### ISSUE TITLE
HTTP spec violation

### ISSUE THREAD

**Issue by webdevsHub** [serbanghita/Mobile-Detect#396]
How come Mobile-Detect does not work with correct HTTP header names (https://tools.ietf.org/html/rfc7231#page-46)?

```php
$mobileDetect = new \Mobile_Detect([
    'User-Agent' => 'Mozilla/5.0 (Android; Mobile; rv:35.0) Gecko/35.0 Firefox/35.0 FirePHP/0.7.4'
]);
var_dump($mobileDetect->is('Firefox')); // bool(false)
```
One have to rewrite the header names **intentionally wrong** to get it work:

```php
$mobileDetect = new \Mobile_Detect([
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Android; Mobile; rv:35.0) Gecko/35.0 Firefox/35.0 FirePHP/0.7.4'
]);
var_dump($mobileDetect->is('Firefox')); // bool(true)
```

Okay, `HTTP_USER_AGENT` is the PHP way of violating the standard and the lib should take that into account for inexperienced programmers. But what if you use Mobile-Detect with php-cli to detect devices from previously stored headers or if you just copy the headers from any browser web toolbar? Or if you use a framework that fixes header names violations? 

```php
$headers = [
    'User-Agent' => 'Mozilla/5.0 (Android; Mobile; rv:35.0) Gecko/35.0 Firefox/35.0 FirePHP/0.7.4'
];
foreach ($headers as $name => $value) {
    $headers[sprintf('HTTP_%s', strtoupper(str_replace('-', '_', $name)))] = $value;
}
        
$mobileDetect = new \Mobile_Detect($headers);
var_dump($mobileDetect->is('Firefox')); // bool(true)
```

Mobile-Detect forces you to write more code if you want it to work according to the standard :confused:

My suggestion / feature request: Change header name strings in the lib (e.g. `protected static $mobileHeaders`) to HTTP standard and modify `Mobile_Detect::setHttpHeaders()` to transform bad formatted $_SERVER header names into HTTP standard names (basically reverse of that `sprintf` in the code example above).

**Comment by nicktacular** [comment]
Thanks for the feedback. This is completely rewritten in v3.0.
