### ISSUE TITLE
Add support for Samsung Tab S SM-T705Y tablet

### ISSUE THREAD

**Issue by tareiking** [serbanghita/Mobile-Detect#401]
user-agent within Chrome: `Mozilla/5.0 (Linux; Android 4.4.2; SM-T705Y Build/KOT49H) AppleWebKit/537.36(KHTML, like Gecko) Chrome/42.0.2311.111 Safari/537.36`

**Comment by serbanghita** [comment]
Done in `2.8.14`. Thanks :beers:, I really appreciate the feedback
