### ISSUE TITLE
Asus TF103C (K010)

### ISSUE THREAD

**Issue by brilsergei** [serbanghita/Mobile-Detect#407]
https://www.asus.com/ru/Tablets/ASUS_Transformer_Pad_TF103C/
UA
Mozilla/5.0 (Linux; Android 4.4.2; K010 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.111 Safari/537.36

**Comment by serbanghita** [comment]
Added in `2.8.14` :+1: 

Thanks a lot!
