### ISSUE TITLE
Mobile Detect + Redux Framework + iphone cache

### ISSUE THREAD

**Issue by jokusuma** [serbanghita/Mobile-Detect#408]
First off, thanks for taking time to develop this awesome script.
I'm a wp theme developer and I use this mobile_detect script to provide optional mobile design layout
that can be enable or disable via the theme option panel (I use SMOF and REDUX framework).

It works well when I use SMOF. So when I enable the custom mobile layout, 
then check on my iphone 5, I will see the mobile layout right away and vice versa (when I disable).

However, when I use Redux Framework, this script will not trigger real time changes when I enable or
disable the custom mobile layout. I spent several days trying to figure out what happened,
and I found that it is a cache problem. However, I've clean the cookies & browsing data on my iphone
but the problem is still there. The problem will be gone when I activate another theme and reactivate
my current theme.

Here's my code :

on the functions.php
require_once('inc/Mobile_Detect.php');
	$mdetect = new Mobile_Detect;
	global $myismobile;
	$myismobile = false;
	if($mdetect->isMobile()) {
		$myismobile = true;
	}

on the desktop page 
$mdetect_isenabled = $redux_options['mdetect_isenabled'];
$mdetect_layout = $redux_options['mdetect_layout'];
global $myismobile;
if($myismobile and $mdetect_isenabled){ 
		include (TEMPLATEPATH . '/mobile.php');	
    } else {
               desktop layout code here
}

Can you please tell me how to solve this ?

Thank you
Jo

**Comment by serbanghita** [comment]
@jokusuma sorry for being late with this, but I cannot respond in time to custom Mobile Detect integrations.

First use `$myismobile = $mdetect->isMobile()` directly.

If somehow you're not sure on the code you wrote, do check the examples from https://github.com/serbanghita/Mobile-Detect/wiki/Code-examples
