### ISSUE TITLE
desktop safari  Version 8.0.7 (10600.7.10) wrongly detected as mobile 

### ISSUE THREAD

**Issue by savdeep** [serbanghita/Mobile-Detect#411]
With new update of safari Version 8.0.7 (10600.7.10), browser is started being detected as mobile.
Any suggestions?

**Comment by serbanghita** [comment]
@savdeep please be more specific, give us the HTTP headers or the user agent.

**Comment by savdeep** [comment]
Yes, here it is @serbanghita 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17

**Comment by serbanghita** [comment]
I tried the user agent against http://demo.mobiledetect.net/ and it says `This is a computer. Your UA is Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17`
