### ISSUE TITLE
Nexus 9 - Android's Chromium webview

### ISSUE THREAD

**Issue by tjl666** [serbanghita/Mobile-Detect#412]
Hi there, 

Firstly great script! I just have a quick snag I wanted to let you know about, when viewing a website using the Nexus 9, running the latest version of Android's Chromium webview, it passes it as a desktop view and not a tablet.

Many thanks :)

**Comment by serbanghita** [comment]
@tjl666 a user agent of that webview would be nice to know. Can you catch it or force the webview to go to http://demo.mobiledetect.net ?
