### ISSUE TITLE
Samsung Tablet is not recognized as isTablet

### ISSUE THREAD

**Issue by fattalgazi** [serbanghita/Mobile-Detect#414]
Hello,

I have Samsung Galaxy Tab Lite 3 (SM-T116NQ) tablet,

When I test your script with this tablet, it is not recognized as tablet, just recognized as isMobile.

It's user-agent is : 

"Mozilla/5.0 (Linux; Android 4.4.4; SM-T116NQ Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.92 Safari/537.36"

Can we fix this problem ?

**Comment by serbanghita** [comment]
I'm on it :+1:

**Comment by MervRenton** [comment]
Related to this..

There seem to have been no releases since 26th April?
Is there anywhere where we can get the latest sets of device data etc as you update them to keep up with new devices and detection rules as they are added?

Thanks,

Merv

**Comment by fattalgazi** [comment]
Fixed and updated. Thanks.

**Comment by serbanghita** [comment]
@MervRenton we're currently providing automate updates through `composer` https://packagist.org/packages/mobiledetect/mobiledetectlib

Thanks @fattalgazi :beers:
