### ISSUE TITLE
latest chrome browser on android nexus 5

### ISSUE THREAD

**Issue by jaammedia** [serbanghita/Mobile-Detect#416]
More of a heads up than a bug but the current class wont pick this up as a mobile browser without some editing.
user agent is now:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Safari/537.36

**Comment by serbanghita** [comment]
@jaammedia Unfortunately there is no evidence in the User-agent that the device is `mobile`
