### ISSUE TITLE
Airtel dongle returns headers of mobile on desktop

### ISSUE THREAD

**Issue by savdeep** [serbanghita/Mobile-Detect#418]
Hi,

In India, on airtel (huge network provider) while accessing a url from desktop, an extra   ["HTTP_WAP_CONNECTION"]=> "Stack-Type=HTTP"    header is being returned.

So, as per our MobileDetection lib HTTP_WAP_CONNECTION is detected as Mobile. 

Please suggest what can be done?

**Comment by serbanghita** [comment]
I'll search this through the db to see how many users were affected so far.
Do you think we can get some official documentation on this extra header?

**Comment by savdeep** [comment]
https://adtwirl.com/mobile_http_headers.php?&user_language=ru

These headers come for  samsung devices like 
" SAMSUNG-GT-S3850/S3850XEKC4 SHP/VPP/R5 Dolfin/2.0 NexPlayer/3.0 SMM-MMS/1.2.0 profile/MIDP-2.1 configuration/CLDC-1.1 OPN-B "

which is samsung corby device. I made live my changes with removing this parameter and things look fine.
