### ISSUE TITLE
In-app / WebView detection

### ISSUE THREAD

**Issue by serbanghita** [serbanghita/Mobile-Detect#423]
I've been asked by a lot of users to detect in-app browser or webview.

Here is what I've gathered so far.

User-Agents:
https://gist.github.com/jabley/990596

Related issues:
https://github.com/serbanghita/Mobile-Detect/issues/246
https://github.com/serbanghita/Mobile-Detect/issues/329
https://github.com/varnish/varnish-devicedetect/issues/17
https://twittercommunity.com/t/tweets-from-my-ios-5-app-still-via-ios-instead-of-my-app-name/5589/3

At the moment I need some explicit use cases: Twitter (iOS/Android), Facebook (iOS/Android), apps made with PhoneGAP

**Comment by serbanghita** [comment]
Facebook: https://github.com/browscap/browscap/issues/624

I just logged someone that browsed to our website from the Facebook app on a Sony Z3 Compact phone. The UA for the the Facebook in-app:
"Mozilla/5.0 (Linux; Android 5.0.2; D5803 Build/23.1.A.1.28; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/36.0.0.39.166;]”

When using the external Chrome browser on the same phone the UA is this:
"Mozilla/5.0 (Linux; Android 5.0.2; D5803 Build/23.1.A.1.28) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36"

here is another one. Facebook app on a Motorola XT890 Razr i phone.
"Mozilla/5.0 (Linux; U; Android 4.1.2; nl-nl; XT890 Build/9.8.2I-50_SMI-26) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 [FB_IAB/FB4A;FBAV/36.0.0.39.166;]"

**Comment by chris-ng-scmp** [comment]
Some Android mobile devices return 'Mozilla/5.0 (Android; U; Android 2.1; en-us;) AppleWebKit/525.10 (KHTML, like Gecko)' from Facebook in-app browser, not sure is this the only case when the user agent string not contains 'Mobile'.

Some other man mention this problem too: Mozilla/5.0 (Android; U; Android 2.1; en-us;) AppleWebKit/525.10 (KHTML, like Gecko)

**Comment by adambard** [comment]
I've noticed several android devices with the Android 2.1 UA string too, despite running on Android 5.x in all cases. In the link provided from @chris-ng-scmp , they suggest searching for an X-Requested-With header with a value of "com.facebook.katana", which does indeed seem to be present in my tests.

**Comment by chris-ng-scmp** [comment]
But is it hard to tell maybe some Android Tablet also return both Android 2.1 UA and "com.facebook.katana" for 'X-Requested-With '?

**Comment by chris-ng-scmp** [comment]
Seems the problem have been fixed in recent FB app update, my phone's user agent of FB in-app browser become normal now, any one can confirm too?

**Comment by wirelessed** [comment]
Facebook gives a different user agent for Android and iOS.
For iOS: is Safari: False. Agent returned is Mozilla.
For Android: is Chrome: True.

The temporary fix I found is to check the iOS version before checking Safari version.

**Comment by ankitch01** [comment]
In Ios, inappbrowser creates iframe. So you can check that if there is an iframe created in your html that means it is an inappbrowser otherwise its a regular mobile browser

`if(document.getElementById("_cdvIframeBridge")){ 
 alert('its an inappbrowser')}else{ 
 alert('its a mobile browser') 
}`
