### ISSUE TITLE
Mobile-Detect with Wordpress, LiteSpeed Cache and Wordfence Falcon Engine Issues

### ISSUE THREAD

**Issue by pcdg** [serbanghita/Mobile-Detect#425]
First off, this is amazing script. Thank you so much for all your work on it!

We've been utilizing it on a few of our Wordpress client sites and it works flawlessly until we enable LiteSpeed Cache or Wordfence Falcon Engine. The sites are responsive and we have certain portions of them that are excluded from mobile devices and tablets using (is_mobile and is_tablet) functions.

The issue is whichever device loads the page first, then that's the version that's stored in the cache – thus making the script entirely useless when used with a caching system.

Is there a solution that we might be missing?

**Comment by serbanghita** [comment]
Hi @pcdg 

1. What plugin are you using in Wordpress that has Mobile_Detect library? 
2. Do these caching mechanisms care about different User-Agents when composing the final cache files?

**Comment by nicktacular** [comment]
I suspect that whatever key the caching mechanism is using is incorrect. Keys should at the very least be some sort of hash on the full user agent. Not familiar with this cache. How do you integrate MobileDetect with LiteSpeed Cache. Can you provide example code please?

**Comment by pcdg** [comment]
Hey @serbanghita, thanks for getting back with us.

To answer question 1 (What plugin are you using in Wordpress that has Mobile_Detect library?)

We were placing a call to your detection script in the functions.php file and creating a few functions along side it to use in the theme. Works great. However, when Falcon Engine or LS Cache are enabled, it doesn't work. Here is what we were using...

functions.php
```php
// Mobile Detect Code
include $_SERVER['DOCUMENT_ROOT'].'/apps/mobile-detect.php';
$device_detect = new Mobile_Detect();

// Function is_mobile
function is_mobile() {
	global $device_detect;
	return $device_detect->isMobile();
}

// Function is_tablet
function is_tablet() {
	global $device_detect;
	return $device_detect->isTablet();
}
```
Theme files
```php
if(is_mobile()): 
	echo 'yep, mobile.'; 
elseif(is_tablet()): 
	echo 'yep, tablet.'; 
else: 
	echo 'yep, computer.'; 
endif;
```
I tried using the [Mobble](https://wordpress.org/plugins/mobble/) plugin, but had the same results when the caching was turned on.

I've done a bit more testing using the [demo.php](https://github.com/serbanghita/Mobile-Detect/blob/master/examples/demo.php) code while Falcon Engine is enabled. Oddly enough, Firefox 38 shows the correct user-agent information every time (despite what the cached version of the page shows.) However, on Safari 8, Safari on iOS9 beta 2 and Chrome 43, whichever one loads the page first is the one that gets cached and re-served to the other browsers from cache. So, if Chrome creates the cached version of the page, then when Safari and iOS Safari load the cached version, it shows that it's a computer running Chrome. Not cool.

To answer question 2 (Do these caching mechanisms care about different User-Agents when composing the final cache files?) Yes, but from what I understand, only before it creates a cached version of the page and whatever device created the first cached version is what is served on subsequent loads. Falcon Engine allows you to bypass the cache for specific devices by specifying User-Agents in the plugin settings. However, that defeats the purpose of utilizing the mobile detect script along side a caching engine if you're wanting to use both.

Ultimately, I think the issue is that both [Falcon Engine](http://docs.wordfence.com/en/Falcon_Cache) and [LiteSpeed Cache](https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:litespeed:cache) create HTML versions of the page and serve it without executing any PHP (which I realize I just answered my own question.) I'm not sure that your script can be used with either of these caching engines.

@nicktacular – We use the mobile detect script with LiteSpeed Cache much the same way we do with Falcon Engine. Both require a few changes to your .htaccess file. Here is the code that's used to enable LS Cache on Wordpress.

```htaccess
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule .* - [E=noabort:1]
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
## Default Wordpress rule
RewriteRule . /index.php [L]
## Enables LS Cache (comment out default WP rule)
#RewriteRule (.*) index.php
</IfModule>

## this part is for public cache.
RewriteCond %{REQUEST_METHOD} ^HEAD|GET$
RewriteCond %{HTTP_COOKIE} !loginuser
RewriteCond %{HTTP:Cookie} !^.*(comment_author_|wordpress_logged_in|wp-postpass_).*$
RewriteCond %{ORG_REQ_URI} !^/index.php$
RewriteCond %{ORG_REQ_URI} !^/wp-admin/
RewriteCond %{ORG_REQ_URI} (\.php|\.html|\.htm|\.feed|\.pdf|\.raw|/[^.]*)$  [NC]
RewriteRule .* - [E=Cache-Control:max-age=30,L]
# END WordPress
```

It's an awesome script, but we see tremendous benefits from Falcon Engine and LS Cache – we've seen dramatic reductions in server load with both of them and the speed is insanely fast. Since most of our sites are responsive, I'm not sure we'll be able to use the mobile detect script if we're using such an aggressive caching engine. Maybe the caching engines need to create different versions of the page if it's a mobile device, tablet or computer. Ultimately, that might solve the issue.

Any thoughts are appreciated. I'll be pinging LiteSpeed later on to see what their thoughts are and maybe we can find a good solution to be able to use both. That would make my day. :+1: 

Thanks again!

**Comment by serbanghita** [comment]
@pcdg thank you for the details! This is an interesting business case of Wordpress + Cache + Mobile Detect (or maybe any other plugin that needs to check stuff on each request).

Me and @nicktacular need to study the options inside the cache plugins Falcon Engine and LiteSpeed Cache, before coming up with a eligible solution to this. 

The fact that the user might never reach PHP, so the `isMobile()` or `isTablet()` conditions are never actually executed, makes me think if there is a way to store the cache keys and values by taking `isMobile` and `isTablet` into account:

```php
// Wordpress is starting.
// Wordpress loads the active modules.

// 1. Mobile Detect plugin is loaded by Wordpress.
class MyMobileDetectPlugin
{
    public static $userAgent = null;
    public static $isMobile = false;
    public static $isTablet = false;

    public function detect()
    {
        $detect = new Mobile_Detect;
        // Store these for later use.
        self::$userAgent = $detect->getUserAgent();
        self::$isMobile = $detect->isMobile();
        self::$isTablet = $detect->isTablet();
    }
}

// 2. Cache plugin.
class MyCachePlugin
{
    // $file = 'index.html'
    protected function saveCacheFile($file)
    {
        write('../cache/'.$file.'_'.MyMobileDetectPlugin::$isMobile.'_'.MyMobileDetectPlugin::$isTablet.'_'.sha1(MyMobileDetectPlugin::$userAgent));
    }
}
```

@nicktacular I think we should provide an official Wordpress Mobile Detect plugin so other plugin vendors could take it into account when loading theirs.

**Comment by Kenshino** [comment]
Or the easier way is - your function that is called in your theme should ideally check Mobile Detect before outputting to the template files.

functions.php is never cached so it's safe.

Eg.

````
locate_template( 'includes/Mobile_Detect.php', true );
global $detect;
$detect = new Mobile_Detect;

function add_body_class( $classes ){
	global $detect, $post;

	if ( $detect->isMobile() ):
		if ( $detect->isTablet() ):
			$classes[] = 'tablet';
		else:
			$classes[] = 'mobile';
		endif;

		if ( $detect->version('iPad') ):
			$classes[] = ' ipad';
		endif;

		// no need for iPhone detection as WordPress does it and is implemented by Canvas

		if ( $detect->version('Android') ):
			$classes[] = ' android';
		endif;
	endif;

	if ( isset( $post ) && ( !is_front_page() && !is_home() ) ) {
		$classes[] = $post->post_type . '-' . $post->post_name;
	}

	return $classes;
}

add_filter( 'body_class', 'add_body_class' );
````
