### ISSUE TITLE
Wrong browser detection

### ISSUE THREAD

**Issue by ERROPiX** [serbanghita/Mobile-Detect#426]
In your demo, it show that 
```
isFirefox() bool(false)
```
but I am using firefox 39, user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"

**Comment by serbanghita** [comment]
Hi @ERROPiX 

Thanks for the report, this is a known behavior for Mobile Detect 2.x, as we focused only on the mobile browsers, we will soon release an entirely new version 3.x that will deal with everything related to device detection, os detection, browser detection, etc.
