### ISSUE TITLE
Function Inlining

### ISSUE THREAD

**Issue by RoyBellingan** [serbanghita/Mobile-Detect#428]
I've done some profiling and the time spent in regex execution is less than calling the function match();

Be aware that this test was done using php 5.6.3 and NO opcode caching ON.

The case is of a failed detection (so all the 109 regex will be executed), please note the SELF time of the Mobile_Detect->match row in the left image.

![mobile_detect](https://cloud.githubusercontent.com/assets/368572/8589894/76cb9d20-261b-11e5-9e98-420d483dc0f6.png)

I suggest to "inline" the function from 

```
    foreach (self::$tabletDevices as $_regex) {
        if ($this->match($_regex, $userAgent)) {
            return true;
        }
    }
```

to 

```
foreach (self::$tabletDevices as $regex) {
    $match = (bool) preg_match(sprintf('#%s#is', $regex), (false === empty($userAgent) ? $userAgent : $this->userAgent), $matches);
    // If positive match is found, store the results for debug.
    if ($match) {
    $this->matchingRegex = $regex;
    $this->matchesArray = $matches;
    }

    if($match){
        return true;
    }
}
```

I do undestard this is NOT a common good coding practice, but as you can see the gain is quite effective.
I'll install the Opcode cache plugin and to some other benchmark asap.

**Comment by RoyBellingan** [comment]
I've installed opcode cache and the result is similar, I've runned the script a good number of time to have a good cache.

![schermata2](https://cloud.githubusercontent.com/assets/368572/8590103/8768dfa6-261d-11e5-82f8-a957ac15fc90.png)

As you can see after caching the result are very close, but the function time still very high!

**Comment by nicktacular** [comment]
Thanks for the feedback, @RoyBellingan. We are currently working on 3.0 so we'd like to get some profiling for our 3.0 work. I'll assign this to myself and when we're ready for performance evaluation on our 3.0 branch I'll let you know.
