### ISSUE TITLE
iPad still detected as mobile device

### ISSUE THREAD

**Issue by udarts** [serbanghita/Mobile-Detect#429]
I have added the following code to detect mobile (phone) devices

$detect->isMobile()

This way I can display certain html on my website, but when I check with my iPad, it shouldn't show the mobile html, but it does.

**Comment by Kenshino** [comment]
That's because the iPad is still a mobile device.

Read https://github.com/serbanghita/Mobile-Detect/wiki/Code-examples

**Comment by chuckreynolds** [comment]
I think what you want to do @udarts is this 
`if ( $detect->isMobile() && !$detect->isTablet() ) :`

**Comment by serbanghita** [comment]
Thanks @chuckreynolds for the assistance :+1:

**Comment by sergekukharev** [comment]
I have similar issue, I following code:

        if (!$this->detector->isMobile()) {
            return self::DEVICE_DESKTOP;
        } elseif ($this->detector->isTablet()) {
            return self::DEVICE_TABLET;
        } elseif ($this->detecor->isMobile() && !$this->detector->isTablet()) {
            return self::DEVICE_MOBILE;
        } else {
            throw new \UnexpectedValueException('Unknown device type detected');
        }

ChromeDevTools are set to emulate iPad and I still get that iPad is mobile. I have no way to test this with real iPad.

**Comment by sergekukharev** [comment]
OK, seems like this is chrome bug, found it in https://github.com/serbanghita/Mobile-Detect/issues/200
