### ISSUE TITLE
Support for LG G3 phones

### ISSUE THREAD

**Issue by shmilky** [serbanghita/Mobile-Detect#432]
Can't recognize LG G3 different devices.
I encountered the issue on the LG G3 D855 but I can also see that there are devices of types:
D850 D851 D724 D690

I found the following link http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand574739/lg-g3

For the LG G4 I read somewhere that it supposed to be H810 but again I didn't investigate it thoroughly.

**Comment by tareiking** [comment]
@serbanghita we also require support for the LG D855. The user-agent we are seeing is `User-agent: Mozilla/5.0 (Linux; Android 5.0; LG-D855 Build/LRX21R.A1422018487)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 MobileSafari/537.36`

Would a PR speed up the process?
