### ISSUE TITLE
Tablet IDed as phone

### ISSUE THREAD

**Issue by MervRenton** [serbanghita/Mobile-Detect#434]
Mozilla/5.0 (Linux; U; Android 4.2.2; en-au; TBLT10Q-32GB Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30

This is the ID string of a Leader branded white-label tablet quite popular in Australia.

It currently identifies as Phone.

Can it be added to the detection list?

Thanks,

Merv

**Comment by serbanghita** [comment]
Done, added several tablets from Leader Online. Thanks :+1:
