### ISSUE TITLE
isWebOS() return false

### ISSUE THREAD

**Issue by Ghanshyam-K-Dobariya** [serbanghita/Mobile-Detect#437]
Please specify the User-Agent. Go to http://is.gd/mobiletest and copy-paste it here.

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.130 Chrome/43.0.2357.130 Safari/537.3

iswebOS() returns false

how can we come to know user is from desktop site.

**Comment by serbanghita** [comment]
@Ghanshyam-K-Dobariya  try 
```php
$detect = new Mobile_Detect;
$isDesktop = !$detect->isMobile();
```

**Comment by Ghanshyam-K-Dobariya** [comment]
@serbanghita Thanks.
