### ISSUE TITLE
isMobile() false positives

### ISSUE THREAD

**Issue by 5lava** [serbanghita/Mobile-Detect#440]
Avant Browser (http://www.avantbrowser.com):
`Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; Avant Browser; rv:11.0) like Gecko`
`Mozilla/5.0 (Windows NT 6.1; WOW64; Avant TriCore) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36`
`Mozilla/5.0 (Windows NT 5.1; rv:27.0; Avant TriCore) Gecko/20100101 Firefox/27.0`

**Comment by serbanghita** [comment]
@5lava it's a valid bug, thanks for reporting this. I have corrected the regex causing this! Check `2.8.17` version. Thanks!
