### ISSUE TITLE
[Nexus 5] app webview will be detected as Tablet

### ISSUE THREAD

**Issue by tashuo** [serbanghita/Mobile-Detect#442]
ua: "Mozilla/5.0 (Linux; Android 5.1; Nexus 5 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 momoWebView/6.3.1 android/404(Nexus 5;android 5.1;zh_CN;10;netType/1)"

Maybe the last string the app add to ua makes it.

**Comment by tashuo** [comment]
To solve it, I change the $tabletDevices['NexusTablet']     from     "Android.*Nexus[\s]+(7|9|10)|^.*Android.*Nexus(?:(?!Mobile).)*$"       to     "Android.*Nexus[\s]+(7|9|10)|^.*Android.*Nexus(?!(?:Mobile).)*$"

    Anyone gives me a better way to solve it?
    thanks.

**Comment by serbanghita** [comment]
@tashuo thanks for reporting this, I have modified the regex. Please check `2.8.17` version
