### ISSUE TITLE
New release, "wrong" branch

### ISSUE THREAD

**Issue by cognusion** [serbanghita/Mobile-Detect#443]
Hi,
The latest release was done out of the "dev" branch, and "master" is out of touch. It's your project, so you can release wherever you'd like, but selfishly if "master" isn't updated, my automated tools won't update my builds. I'm not sure if this was intentional or an oversight, that's the only reason I bring it up.
Cheers,
M@

**Comment by serbanghita** [comment]
Hi @cognusion 

Sorry, that was my bad. I usually update both `devel` and `master`. Thanks!
