### ISSUE TITLE
Mobile (iOS) Gmail App, viewing email returns 'desktop' view not mobile

### ISSUE THREAD

**Issue by Braunson** [serbanghita/Mobile-Detect#444]
Context: I'm loading an image in an email that is a php file that determines where it's loaded from (using Mobile-Detect), but it always says it's from the desktop.

Any ideas around this for Gmail Mobile? If it helps, the User Agent is:

`Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)`

**Comment by artegic** [comment]
I have the same problem.

Any further informations yet?

thanks
