### ISSUE TITLE
Missing user agent: Sony Xperia Z4 tablet

### ISSUE THREAD

**Issue by eerootsus** [serbanghita/Mobile-Detect#446]
Came across a UA not detected as tablet:
`Mozilla / 5.0 (Linux; Android 5.0.2; SOT31 Build / 28.0.D.6.71) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 39.0.2171.93 Safari / 537.36`

**Comment by serbanghita** [comment]
@eerootsus thanks, I'm going to update the regex in the next minor release!

**Comment by serbanghita** [comment]
Fixed in `2.8.17` :beers:
