### ISSUE TITLE
Prestigio Multipad Wize 5002 recognized as Phone

### ISSUE THREAD

**Issue by adapterek** [serbanghita/Mobile-Detect#448]
I think the list of PrestigioTablet devices is incomplete.

According to http://www.prestigio.com/support  there could be added:

PMP812E|PMP812E3G|PMP812F|PMP810E|PMP880TD|PMT3017|PMT3037|PMT3047|PMT3057|PMT7008|PMT5887|PMT5001|PMT5002

For Multipad Wize 5002 works PMT5002

Thanks for looking into it.

**Comment by serbanghita** [comment]
@adapterek Thanks for reporting this! I've added them in `2.8.17` and added some tests.
