### ISSUE TITLE
IOS9 is not recognized as a mobile device

### ISSUE THREAD

**Issue by mikevrind** [serbanghita/Mobile-Detect#449]
The (safari?) user agent on IOS9 no longer contains the iPhone/iPod value which is being used to recognize the iPhone as a mobile device.

**Comment by serbanghita** [comment]
@mikevrind can you pass an user-agent? I was looking through our db and I cannot find any evidence of that

**Comment by mikevrind** [comment]
Well... shoot me! When I print the user agent I get the following response: 

"Mozilla/5.0 (**iPhone**; CPU ***iPhone*** OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A344 Safari/601.1".

I could swear that this was not there earlier... I even compared it with an IOS8 device...
I'm ashamed and going to hide for a couple of days!

**Comment by serbanghita** [comment]
@mikevrind no problem, if you find anything in the future just let us know! Thanks :beer:
