### ISSUE TITLE
Can't detect IE 11

### ISSUE THREAD

**Issue by zkelo** [serbanghita/Mobile-Detect#450]
Mobile Detect version 2.8.14 (on the demo site) and latest version on the moment at make issue, MDetect can't detect IE browser v. 11. Method isIE is false.
![17-09-2015 18-08-19](https://cloud.githubusercontent.com/assets/13527447/9937006/58904c6a-5d67-11e5-9f64-39fef2615e05.jpg)

**Comment by nicktacular** [comment]
Can you please provide the full user agent string?

**Comment by alxndrr** [comment]
Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko

**Comment by deepacitpl** [comment]
For me, Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0;Touch;rv: 11.0) like Gecko returning the output as "mobile" device, but I am accessing from laptop.

**Comment by koltejas** [comment]
Still cant detect IE 11 on desktop. 
UA string  Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by llaville** [comment]
Just test it today and I confirm this issue with  IE 11.0.9600.17959 and user agent "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by zkelo** [comment]
Oh... 3 years ago I opened this issue. And today I have 
same problem in IE 11 on Windows 10.

UA: `Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`

![1542034676](https://user-images.githubusercontent.com/13527447/48355586-6dbe9900-e6a5-11e8-946b-ce995aec12e7.jpg)

**Comment by coderintherye** [comment]
@zkelo Reading the regex that previously resolved this it's:
"match": "Mozilla\/5.0 (#PLATFORM#Trident\/7.0*",
And what I see different in what you posted is that your user agent string is including WOW64; which is probably throwing off that regex.
Maybe a simple change to the below would fix it (note the extra star)
"match": "Mozilla\/5.0 (#PLATFORM#*Trident\/7.0*",

**Comment by wowcut** [comment]
Same here, IE11 not detected - this browser unfortunately is still used inside many companies, would you please like to fix that? Thanks!

```Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko```

BTW this is IE11 from the freely available [MS Virtual Machines](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) - as I am doing some web related dev I have these always avaliable on my Linux box so I can test IE browsers. Might be worth looking at, then you can check these horrible browsers yourself :) !
