### ISSUE TITLE
Windows Surface RT tablet detected as phone

### ISSUE THREAD

**Issue by scottastrophic** [serbanghita/Mobile-Detect#461]
UA: Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0; Touch; rv:11.0) like Gecko

**Comment by serbanghita** [comment]
@scottastrophic it's impossible to tell if the device is a tablet in the given conditions. We have no indicator of device code or type, this is why it falls back to `mobile`

**Comment by scottastrophic** [comment]
Thanks @serbanghita 

Does that mean MobileDetect will never support Surface RTs? That is the full UA string provided by IE on those devices. Do you recommend creating an exception just for those devices?
