### ISSUE TITLE
Samsung smart TV 2015

### ISSUE THREAD

**Issue by FDiskas** [serbanghita/Mobile-Detect#475]
Mozilla/5.0 (SMART-TV; X11; Linux armv7l) AppleWebkit/537.42 (KHTML, like Gecko) Safari/537.42

**Comment by five1** [comment]
**User agent string (Feb 15, 2017):**
Mozilla/5.0 (SMART-TV; X11; Linux armv7l) AppleWebkit/537.42 (KHTML, like Gecko) Chromium/25.0.1349.2 Chrome/25.0.1349.2 Safari/537.42

Can the 'TV value be modified in the $utilities array to include 'SMART-TV'?
``` php
        'TV'          => 'SonyDTV|HbbTV|SMART-TV', // experimental
```
