### ISSUE TITLE
Firefox detection on IOS devices.

### ISSUE THREAD

**Issue by pawcioma** [serbanghita/Mobile-Detect#478]
Hello,
Firefox browser is detected as Safari. Guys you should add to browsers:
Firefox = '...|FxiOS/[0-9.]+';
and to properties:
'Firefox'     => array(9'Firefox/[VER]', 'FxiOS/[VER]')

https://user-agents.me/browser/mozilla50-iphone-cpu-iphone-os-8_4_1-like-mac-os-x-applewebkit60014-khtml-like-gecko-fxios11-mobile12h321-safari60014

https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference#Firefox_for_iOS

**Comment by sylouuu** [comment]
Same here, check for iOS and Safari, this will be true if you are on iOS with Firefox.
