### ISSUE TITLE
Windows Phone Detected as iOS

### ISSUE THREAD

**Issue by h3nr1ke** [serbanghita/Mobile-Detect#480]
the test using `isiOS();` and `isWindowsPhoneOS();` return true using the Internet Explorer on Windows Phone on Microsoft Lumia 640

The **HTTP_USER_AGENT** is

`Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1074) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537`

**Comment by Rahulshahare** [comment]
yeah same bug i have found. 
its microsoft lumia 535 
isMobile()- true
isiPhone()-true
isAndroidOS()-true
isWindowsMobileOS()-true
isWindowsPhoneOS()-true
isiOS()-true
isIE()-true

The **HTTP_USER_AGENT** is
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft;Lumia 535 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

how about adding a Microsoft lumia devices in $phoneDevice array? will it work or how we can figure this issue

**Comment by svenwe1987** [comment]
Same issue for me, is there a way to fix this?

**Comment by Rahulshahare** [comment]
if Windows Phone are so important for our projects then we ca grab them like this

```
if($detect->isMicrosoft()){
                    $DeviceName = "Windows Phone";
     }
```

isit good?? or we have any other way
