### ISSUE TITLE
Mobile-Detect in a MVC Application

### ISSUE THREAD

**Issue by ghost** [serbanghita/Mobile-Detect#484]
Hello there !

I'm really love this project and I wanna applicate this in a `MVC Application`. Talking about performance and organise:
- Where is the better place to instantiate the `Mobile Detect` object?
- Do I manipulate the ifs and elses in the `Controller`, or in the `View`?

Thanks for the help :smile:

**Comment by serbanghita** [comment]
If you show us your project repo we might be able to discuss this there. This is not a Mobile Detect issue. Thanks!
