### ISSUE TITLE
Detects ONLY after page refresh

### ISSUE THREAD

**Issue by vakh777** [serbanghita/Mobile-Detect#487]
Greetings!
Site http://forward-ua.com on first enter displays desktop version. Switching to mobile template ONLY after refreshing page. On other site http://vakh.net it works perfect!
HELP!

Thank you!

**Comment by ThaDafinser** [comment]
This has nothing todo with MobileDetect.

**Comment by vakh777** [comment]
I think so, too. But can you tell me what can block it while first enetering?

**Comment by vakh777** [comment]
P.S. Sorry for my english.

**Comment by ThaDafinser** [comment]
@vakh777 sorry, no `free support` for `paid projects`
