### ISSUE TITLE
Can't detect my browser Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

### ISSUE THREAD

**Issue by Misikir** [serbanghita/Mobile-Detect#489]
My UA is Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0 it doesn't detect it as Firefox actually it is Firefox Developer Edition

Application Basics
------------------

Name: Firefox
Version: 44.0a2
Build ID: 20151213004008
Update Channel: aurora
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Multiprocess Windows: 0/1 (default: false)

**Comment by serbanghita** [comment]
@Misikir this is a known limitation with `Mobile Detect 2.x`, we targeted for detection only of mobile browsers. We're working on upgrading this on `3.x`
