### ISSUE TITLE
Problem with the Asus tablets 

### ISSUE THREAD

**Issue by Bwai** [serbanghita/Mobile-Detect#495]
User-Agent
Mozilla/5.0 (Linux; Android 5.0; PO1MA build/LRX21V)
AppelWebKit/537.36 (KHTML, like Gecko)
Chrome/39.0.2171.93
Safari/537.36

Hello,

Thank you for your excellent work.
I wanted to tell you that there was a problem with the Asus tablets that are detected as an mobile.

Best regards.

**Comment by serbanghita** [comment]
Thanks, I'm looking into this!
