### ISSUE TITLE
Please add IOS/Android detection - redirect

### ISSUE THREAD

**Issue by kvbappinio** [serbanghita/Mobile-Detect#496]
Hello,

thanks for your work. A suggestion would be to make
a Plugin for YOURLS (URL Shortener) so the short url
can redirect the user if mobile/ android / ios etc. to the right
stores/locations.

Thanks

**Comment by romanitalian** [comment]
This "Mobile-Detect" - is like model in mvc (in your application). For this reason "Mobile-Detect" shouldn't redirect or do any routing.

**Comment by kvbappinio** [comment]
hmm not sure were talking about the same thing here.
Im talking about ONE short url wich detects via YOURLS 
if the user is coming through via ios/android and redirects to the 
right store. - thats a feature bit.ly offer for only 1000 bucks/ month :(

**Comment by verybigelephants** [comment]
you mean like a third party service? this is kind of a php library :S  
if you have a domain you can include the library and do the redirecting yourself
