### ISSUE TITLE
Cookie Support for performance

### ISSUE THREAD

**Issue by ewwink** [serbanghita/Mobile-Detect#507]
Hi,
Please add Cookie Support for performance, like

```
function isMobile($cookie = false)
{
  if($cookie && isset($_COOKIE["isMobile"]))
  {
    return $_COOKIE["isMobile"] == "yes" ? true : false;
  }
  .........
}
```

**Comment by u-mulder** [comment]
This lib just detects your device type. You can write your wrapper on it using cookies, key-value storages, whatever and use.
