### ISSUE TITLE
Samsung Galaxy Tab E

### ISSUE THREAD

**Issue by jkrassman** [serbanghita/Mobile-Detect#509]
Hi, nice library - but it reports my Samsung Galaxy Tab E as a phone, but it is a tablet?

Regards, Joakim

**Comment by Allan-iam** [comment]
A tablet is still a mobile device.

isMobile() && !isTablet()

This is the condition to know whether the device is a phone.





   

Allan Ayamah

**Comment by jkrassman** [comment]
Thats really strange, because it reports "Tablet" for my iPad Air - with the exactly same functions. 

The worst thing is that I must have been tricked when I bought it today, I cant even manage to make a phonecall on it :dart:

**Comment by serbanghita** [comment]
Thanks @Allan-iam for assisting this :+1:
