### ISSUE TITLE
isiOS() and is('iOS') fails to recognise iOS platform

### ISSUE THREAD

**Issue by bojanpejic** [serbanghita/Mobile-Detect#510]
For example the `$_SERVER['HTTP_USER_AGENT']` looks like following:
`AppName/com.appname.iphone (2.0.11; OS Version 9.2.1 (Build 12ABD))`

Both `$detect->isiOS()` and `$detect->is('iOS')` returns false value, 
when in other case `$detect->iPhone()` returns true.

**Comment by ThaDafinser** [comment]
Is `AppName/com ...` a real UserAgent and not modified? 
Just currious, if this is not a fake, because it gets at least detected by 3 libs

[Results](http://useragent.mkf.solutions/?userAgent=AppName%2Fcom.appname.iphone+%282.0.11%3B+OS+Version+9.2.1+%28Build+12ABD%29%29)

**Comment by bojanpejic** [comment]
Well, it's only fake in the way that I've replaced the original application name with ``AppName``.

In my opinion looks like Mobile-Detect is having troubles for detecting with ``->isiOS()`` and ``->is('iOS')`` because the following matching conditions:
https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php#L481
```
'iOS'               => '\biPhone.*Mobile|\biPod|\biPad',
```

**Comment by serbanghita** [comment]
@bojanpejic this looks like an in app browser / webview. Current branch `2.x` doesn't support detection. I'm investigating this in `3.x`. Thanks for the report!
