### ISSUE TITLE
HTC One M8

### ISSUE THREAD

**Issue by VinceCamuto** [serbanghita/Mobile-Detect#511]
Doesn't detect this device as Mobile - HTC One M8

**Comment by VinceCamuto** [comment]
This problem seems only in the default browser

**Comment by ThaDafinser** [comment]
This device? Can you provide a real user agent?

**Comment by VinceCamuto** [comment]
http://prntscr.com/a7de5y - screenshot from this device

**Comment by VinceCamuto** [comment]
But in Chrome Browser all OK. this bug only in default android browser on this device

**Comment by serbanghita** [comment]
@VinceCamuto given the state of the User-Agent and HTTP Headers we cannot actually detect and identify the device.
