### ISSUE TITLE
Several Lumia User Agents are not detected correctly

### ISSUE THREAD

**Issue by danygielow** [serbanghita/Mobile-Detect#516]
Hi,

I came across some Nokia Lumia user agents that are detected as "computer" but should be "phone".
Used Version: 2.8.19

- Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 950 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
- Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 950) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
- Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 930) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
- Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 730 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

Maybe the problem is, that there is no "NOKIA" substring in the user agent. I don't know.

Regards
Dany

**Comment by rickyhub** [comment]
nokia lumia 520 is still not detected.

regards
rick

**Comment by NielsLeenheer** [comment]
This is Windows 10 Mobile in Continuum mode. These are mobile devices, but connected to an external monitor, keyboard and mouse. So in one way they are desktop devices running the desktop version of Edge.

**Comment by serbanghita** [comment]
@NielsLeenheer thanks for mentioning that. I will add Nokia Lumia to the mobile regex because of this situation. :+1: 

@danygielow thanks for the User-Agents!
