### ISSUE TITLE
Samsung Galaxy Tab A 8: Tablet Not Detected

### ISSUE THREAD

**Issue by tsteuwer** [serbanghita/Mobile-Detect#517]
Mozilla/5.0 (Linux; Android 5.0.2; SM-T357T Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.95 Safari/537.36.

This should simply be added/appended to ``$tabletDevices`` under the ``'SamsungTablet'`` regex as "SM-T357T".

**Comment by serbanghita** [comment]
@tsteuwer thanks, will do, I have a release pending and I'm going to include this!

**Comment by tsteuwer** [comment]
Awesome. Do you have an ETA on when to expect this out? Our company would like to update to it ASAP.

**Comment by serbanghita** [comment]
Yes, tonight at 12:00 EET time. I'll notify you!

**Comment by renekreijveld** [comment]
Was this already added in current stable version? I see that the following user agent is still detected as a phone:
Mozilla/5.0 (Linux; Android 5.0.2; SANSUNG SM-T555 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Safari/537.36

**Comment by serbanghita** [comment]
Both user agents are in the latest release

cc: @tsteuwer @renekreijveld - thanks as always!
