### ISSUE TITLE
Wrong device detect

### ISSUE THREAD

**Issue by wkaminsk** [serbanghita/Mobile-Detect#521]
Hi,
first of all thank you for brilliant tool !

We've found out that it's working incorrectly Kindle Fire HD7. It's showing a mobile version, instead of the desktop version.

Thanks,
Wojtek

**Comment by serbanghita** [comment]
@wkaminsk thanks for reporting! Do you have the user-agent? Did you submit the feedback in http://demo.mobiledetect.net ?

**Comment by wkaminsk** [comment]
@serbanghita sorry for delay.
I'm using browser stack to test it. This is what I get: http://screencast.com/t/zMbppr3o

Thanks

**Comment by serbanghita** [comment]
Oh i see, this is a problem with BrowserStack not setting the real user-agents for that specific devices. Notice is the generic `Android SDK`
