### ISSUE TITLE
isFirefox() returns false on my UA

### ISSUE THREAD

**Issue by AfonsoFG** [serbanghita/Mobile-Detect#523]
This is a computer. Your UA is Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

How come isFirefox() returns bool(false) and then version(Firefox) is populated with string(4) "44.0"

**Comment by cyberwani** [comment]
Yes, I am facing the same issue on Firefox 45.0.2 and 46.0.1.

**Comment by javierenciso** [comment]
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

isFirefox:

boolean false


same here!!
/best
/j

**Comment by koltejas** [comment]
Returns false on Firefox 48. Strangely isFirefox() returns true for Firefox on android...

**Comment by medatech** [comment]
Not sure if it's related, but the demo page return FALSE for all isBrowser for me on both Chrome and Firefox.
http://demo.mobiledetect.net

I'm assuming the supported methods on the page live update depending on your browser.
