### ISSUE TITLE
Possible detection error with Firefox in Ubuntu Mate 15.10

### ISSUE THREAD

**Issue by demoniodojo** [serbanghita/Mobile-Detect#527]
Please specify the User-Agent. Go to http://is.gd/mobiletest and copy-paste it here.

This is a computer. Your UA is Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

It detects that this is a computer, but it says: isFirefox() 	bool(false).
I'm using firefox in ubuntu mate 15.10.

**Comment by serbanghita** [comment]
@demoniodojo yes this is a known limitation, on the `2.x` branch we are focusing only on mobile browsers. From `3.x` we will be able to detect this as `Firefox`
