### ISSUE TITLE
mobile-detect.php does not exist

### ISSUE THREAD

**Issue by codyme** [serbanghita/Mobile-Detect#530]
hi there. first of all I want to thank you for the awesome plugin.
I installed mobile detect for wp plugin on a wordpress multi-site installation, and when I activated the plugin I got this error message that mobile detect does not exist in the directory (refering to line 33 wp-mobile-detect.php file, require_once('mobile-detect.php');).
I fixed this by changing it to require_once( plugin_dir_path( __FILE__ ) . 'mobile-detect.php'); I thought to mention it here in case someone else is experiencing the same issue.

**Comment by serbanghita** [comment]
Thank you for pointing this out. Can you tell me which plugin exactly did you used so I can notify the author?

**Comment by codyme** [comment]
Sure. It's WP Mobile Detect: https://wordpress.org/plugins/wp-mobile-detect/
