### ISSUE TITLE
Your demo page's contribute section is apparently not being regarded

### ISSUE THREAD

**Issue by seomaton** [serbanghita/Mobile-Detect#531]
The following browser is mistaken for a phone.

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.9) Gecko/20100101 Goanna/2.0 Firefox/38.9 PaleMoon/26.1.1

Your demo page's contribute section is apparently not being regarded. Therefore I am posting it also here.

**Comment by gremboloid** [comment]
#500 
fixed
https://github.com/serbanghita/Mobile-Detect/pull/528

**Comment by serbanghita** [comment]
@seomaton I'm looking at the demo page answers but I'm taking tablets as a priority. I'm looking into this bug asap. Thanks @gremboloid for the reminder!

**Comment by seomaton** [comment]
Thank you. A donation for the library was wired to your Paypal account.

**Comment by serbanghita** [comment]
@seomaton, @gremboloid  Thank you for the bug, I've pushed the changes in the `2.8.21` version.

@seomaton Thank you for the donation! That is very kind! :beer:
