### ISSUE TITLE
New 3rd party module for NGINX (Lua)

### ISSUE THREAD

**Issue by yourpalmark** [serbanghita/Mobile-Detect#534]
**Name / Link:** [mobile-detect.lua](https://github.com/yourpalmark/mobile-detect.lua)

**Description:** A port of Mobile-Detect to Lua for NGINX HTTP servers.
Follows closely to [mobile-detect.js](https://github.com/hgoebl/mobile-detect.js).
Supports all methods that server-side mobile-detect.js supports.
Fully unit-tested and synced with Travis CI (Build Passing badge included).

**Comment by yourpalmark** [comment]
[mobile-detect.lua](https://github.com/yourpalmark/mobile-detect.lua) source is now generated by a script and template based on Mobile-Detect patterns.
This will allow for Mobile-Detect updates to easily cascade to mobile-detect.lua.

**Comment by serbanghita** [comment]
@yourpalmark wow this is incredible, I am thinking of promoting the module up to mobiledetect.net
For the moment I dont have time to update that page, but I'm working on it. Meanwhile I'm putting this in the README

**Comment by yourpalmark** [comment]
Thanks @serbanghita ! Really appreciate it. And of course would love to see it on the site! :)
