### ISSUE TITLE
Kindle fire hd6 not recognised as Kindle

### ISSUE THREAD

**Issue by julia-r** [serbanghita/Mobile-Detect#538]
The Kindle hd6 is correctly identified as mobile and Android, but not as Kindle.

Here is the user agent:

Mozilla/5.0 (Linux; Android 5.1; KFARWI Build/LMY47O) AppleWebKit/537.36 (KHTML, like Gecko) Silk/47.1.79 like Chrome/47.0.2526.80 Mobile Safari/537.36

**Comment by serbanghita** [comment]
@julia-r :+1: thanks!
