### ISSUE TITLE
Vivaldi browser detection

### ISSUE THREAD

**Issue by vitalybaev** [serbanghita/Mobile-Detect#543]
User-Agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Safari/537.36 Vivaldi/1.1.453.47` should be `Vivaldi 1.1.453.47`, but got `Chrome 50.0.2661.89`

**Comment by serbanghita** [comment]
See https://github.com/serbanghita/Mobile-Detect/issues/600
