### ISSUE TITLE
add 'asus MeMo Pad 7'

### ISSUE THREAD

**Issue by bnadji** [serbanghita/Mobile-Detect#546]
I am a long time and happy user of Mobile Detect.  Not sure what the proper channel for requests like this are but some of my users have "ASUS MeMo Pad 7" and it is not properly detected as a Tablet.  

The user agent is:

`Mozilla/5.0 (Linux; Android 5.1.1; ASUS MeMO Pad 7 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Safari/537.36`

I have manually added `|MeMo Pad 7|` in `'AsusTablet' =>` but it will be good if it is a permanent part of the build.

Thanks.

**Comment by mimmi20** [comment]
@bnadji Please create a pull request with your change.
