### ISSUE TITLE
Desktop Chrome

### ISSUE THREAD

**Issue by harlet** [serbanghita/Mobile-Detect#547]
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

isChrome() not working. :)

**Comment by mgsmus** [comment]
This is a computer. Your UA is Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

Same here. isChrome() returns false.

**Comment by javierenciso** [comment]
same here!

/best
/j

**Comment by crazyx13th** [comment]
same here!

/best
/c

**Comment by KiddingMe42** [comment]
Is there any solution for this issue? I have the same problem in Chrome and in each other browser too.

**Comment by serbanghita** [comment]
Guys, Mobile Detect 2.x was not designed to sniff browsers, but only to detect mobile and differentiate the tablets. The browser sniff support will be added when 3.x is ready in 2017.
