### ISSUE TITLE
Edge in master branche fail

### ISSUE THREAD

**Issue by Muskos** [serbanghita/Mobile-Detect#552]
I take MobileDetect from here:
https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php
Test on desktop Edge - $detect->isMobile() returned 1

Plz check this. I take release version - all right.
thx for your work

**Comment by serbanghita** [comment]
I'll check, is because I merged a commit without tests :(
Thanks for catching this!

**Comment by Muskos** [comment]
np 
Thanks for you)

**Comment by javierenciso** [comment]
Hi there...
is this solved?
/thanx
/j

**Comment by serbanghita** [comment]
This should not reproduce anymore. I've tested from my Edge.
