### ISSUE TITLE
ipad pro 

### ISSUE THREAD

**Issue by Muskos** [serbanghita/Mobile-Detect#554]
user-agent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12`

`$detect->isMobile()` false
`$detect->isTablet()` false

Maybe you have already corrected it?

**Comment by nokimaro** [comment]
Is this user-agent of real device, not emulator or test-app?

**Comment by ThaDafinser** [comment]
I would say it's a real one.
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_10_4%29+AppleWebKit%2F600.7.12+%28KHTML%2C+like+Gecko%29+Version%2F8.0.7+Safari%2F600.7.12

**Comment by codexpert** [comment]
Same problem here. Is there any workaround?

**Comment by serbanghita** [comment]
@Muskos @codexpert unfortunately from the user-agent Mobile Detect cannot figure out any signs that the device is mobile.
