### ISSUE TITLE
Aquarius M10 not detected as tablet!

### ISSUE THREAD

**Issue by weiddolo** [serbanghita/Mobile-Detect#557]
My tablet name and model is: 
**Brand**: Aquarius
**Model**: Aquarius M10 Build/LMY47I

`HTTP_USER_AGENT Mozilla/5.0 (Linux; Android 5.1; Aquaris M10 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Safari/537.36`

I have added in $tabletDevices array this and now works:
 'Aquaris'           => 'LMY47I',

**Comment by serbanghita** [comment]
Fixed
