### ISSUE TITLE
"Hisense Sero 8 Pro" not detected as a tablet

### ISSUE THREAD

**Issue by staabm** [serbanghita/Mobile-Detect#561]
UA is 

Mozilla/5.0 (Linux; Android 4.4.4; F5281 Build/KTU84Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/260.1985.135 Safari/537.36

we already used the "contribute - is your device really a phone" feature and told that this was a wrong guess.

**Comment by serbanghita** [comment]
Done in `2.8.24` 👍
