### ISSUE TITLE
desktop Edge13 + Edge14 on win10 detected as isMobile()=true!

### ISSUE THREAD

**Issue by javierenciso** [serbanghita/Mobile-Detect#564]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

Hi, this browser is detected as isMobile() but it is a desktop browser on windows 10!

**Comment by serbanghita** [comment]
Should be fixed in `2.8.23`. Thank you!

**Comment by javierenciso** [comment]
thanks! I'll test it right away... ;-)
