### ISSUE TITLE
oneplus devices discover as desktop 

### ISSUE THREAD

**Issue by eliya111** [serbanghita/Mobile-Detect#568]
Hi 
can you please add oneplus devices to the mobile check class?
Thanks.
Eli

**Comment by ThaDafinser** [comment]
> Please specify the User-Agent. Go to http://is.gd/mobiletest and copy-paste it here.

**Comment by eliya111** [comment]
Hi the user-Agent is: Mozilla/5.0 (Linux; Android 6.0.1; A0001 Build/MHC19Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537.36

**Comment by nokimaro** [comment]
Looks like there is no bug.
![xxx](https://cloud.githubusercontent.com/assets/1027608/16896399/92ebfd34-4ba3-11e6-86f1-194824c9d33d.PNG)

**Comment by eliya111** [comment]
you right. its work my mistake. 
Thanks
