### ISSUE TITLE
ASUS ME 103 K tablet UA not detected as tablet - description gives UA

### ISSUE THREAD

**Issue by jansangill** [serbanghita/Mobile-Detect#570]
UA:

Mozilla/5.0 (Linux; Android 5.0.2; K01E Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36

Can this be added?

**Comment by serbanghita** [comment]
Yes, it will be available in the next release. Thanks a lot!
