### ISSUE TITLE
MobileDetect isMobile Returns Empty Variable

### ISSUE THREAD

**Issue by DavidB-TPW** [serbanghita/Mobile-Detect#573]
I am trying to use MobileDetect on my website, but I am having an unusual problem. For whatever reason, when I try to use isMobile to determine if I should have my website load in "mobile mode", the function does not return true or false. It simply returns an empty variable.

I am not sure what is causing this, and I do not receive any errors. I am sure that the issue has something to do with my website because I have used this same version of MobileDetect on an older version of my website with no problems, so this is not so much a bug request as much as it is a request for assistance in figuring out what the problem could be.

**Comment by hgoebl** [comment]
You should create a post on StackOverflow and show your source code as well, otherwise nobody can help you. There you should explain what an "empty variable" is.

**Comment by DavidB-TPW** [comment]
I have discovered the fault that prevented this from working properly, and since it is not a bug with Mobile Detect, I am closing the issue.
