### ISSUE TITLE
Nexus 9 tablet detected as a mobile

### ISSUE THREAD

**Issue by Mattgic** [serbanghita/Mobile-Detect#581]
From the demo page :

This is a **phone**. Your UA is Mozilla/5.0 (Linux; Android 4.4.99; Build/LFW73W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.59 Safari/537.36
...
Matching Regex      :     string(48) "\bCrMo\b|CriOS|Android.*Chrome/[.0-9]* (Mobile)?"
Matching Array       :     array(1) { [0]=> string(89) "Android 4.4.99; Build/LFW73W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.59 " }

**Comment by serbanghita** [comment]
@Mattgic thanks for this, unfortunately there is no indication in the User-Agent string to identify it as a tablet.

**Comment by jasperf** [comment]
This is major bummer. One of the virtual devices I tend to use in Android Studio as well. Also saw a mobile display. And also a bummer for customers using the Nexus 9. Any news on this?
