### ISSUE TITLE
Mobile-Detect doesn't recognize Google PageSpeed Insights PC performance test

### ISSUE THREAD

**Issue by AndrewRadchenko** [serbanghita/Mobile-Detect#583]
Mobile_Detect doesn't recognize device type of Google PageSpeed Insights PC performance test.
isMobile() = true both mobile and pc performance test...

Request headers for pc test are "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36"

Request headers for mobile test are "Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Mobile Safari/537.36"

**Comment by mimmi20** [comment]
@AndrewRadchenko Is the second UA complete as you wrote it above?

**Comment by AndrewRadchenko** [comment]
@mimmi20 I was wrong when I opened the issue. Everything is working ok. The problem is because Google PageSpeed don't support $_SESSION.

**Comment by mimmi20** [comment]
@AndrewRadchenko I would like to detect the sesond useragent with the browscap project, but it looks like something like "Mozilla/5.0..." is missing at the beginning.
