### ISSUE TITLE
Not detecting or reading Vivaldi correctly

### ISSUE THREAD

**Issue by ajmaske** [serbanghita/Mobile-Detect#584]
Our site has been getting reports that this user agent isn't being properly detected and/or read ...

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.80 Safari/537.36 Vivaldi/1.3.582.3`

**Comment by serbanghita** [comment]
I will postpone this, for the moment Mobile Detect 2.x only detects mobile browsers. It was never meant to be a browser sniffer. That is being worked in 3.x version.
