### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by kleinadam** [serbanghita/Mobile-Detect#585]
No more new releases after 2.8.22?

**Comment by kleinhev** [comment]
I was wondering the same. Last update was nearly half a year ago.

**Comment by nicktacular** [comment]
I can't speak for @serbanghita but I've not been in any position to contribute to this project from earlier this year. Unfortunately work on v3 is stale although in the ~90% completion state. I expect to be able to resume contributions to get work on v3 within the next few months.

**Comment by serbanghita** [comment]
Hi everyone! On `2.x` I couldn't update it so far because of the amount of work I had since I changed my job. I will resume work in the following week! Sorry about inconveniences, I'm keeping an eye on pull requests!

**Comment by lukyrys** [comment]
Project is dead? No more updates, many issues, many PR and a half year old promise..

**Comment by kleinadam** [comment]
Maybe we can find a way to keep 2.x on running? I, and maybe a lot of others would pay a yearly/monthly update fee....

Or maybe someone can recommend a similar php service that provides just the device type (desktop, smartphone, tablet) info? 

For example: updating our GeoIP-databases there's a fee with each update as well to pay.

**Comment by webgeek154** [comment]
I'd be willing to contribute yearly/monthly to this.   I also just need device type info.

**Comment by serbanghita** [comment]
Guys, our motivation was never money, we will never sell or accept money to go with the product in a `freemium` direction. This will always be free! We, of course accept donations, but that is for experiments and hosting. 

The best way to help is to submit pull requests and tests!

**Comment by webgeek154** [comment]
We REALLY do appreciate your investment of time and effort into this!  Thank you :)
