### ISSUE TITLE
Samsung Galaxy TAB A SM-T280 is not detected

### ISSUE THREAD

**Issue by Codenetz** [serbanghita/Mobile-Detect#586]
Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-T280 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Safari/537.36

**Comment by serbanghita** [comment]
@Codenetz thanks a lot! This is included in the next patch!
