### ISSUE TITLE
how to find battery status device specifications using PHP of an android device?

### ISSUE THREAD

**Issue by Singh-Aish** [serbanghita/Mobile-Detect#587]
I need to find battery status just by entering DeviceId or DeviceToken, all device specifications are shown as API is hit.
![capture](https://cloud.githubusercontent.com/assets/16304806/19338324/e5bfca5a-9139-11e6-9fd7-e6c85d2f507b.PNG)

**Comment by serbanghita** [comment]
@Singh-Aish that seems like an API that should be available in JavaScript. Look for https://developer.mozilla.org/en/docs/Web/API/Battery_Status_API
