### ISSUE TITLE
Cannot detect Opera Mini Browser,Only Opera is getting detected

### ISSUE THREAD

**Issue by AmrataRamchandani** [serbanghita/Mobile-Detect#588]
There is no way to detect Opera Mini Browser separately.
writing only Opera detects both Opera and Opera Mini.
Which I don't require, As I have to put exceptions for Opera Mini Specifically !

**Comment by serbanghita** [comment]
@AmrataRamchandani yes, at the moment Mobile Detect 2.x is not made for browser detection but for general mobile and tablet detection.
