### ISSUE TITLE
"Cloaking" issue 

### ISSUE THREAD

**Issue by djarrin** [serbanghita/Mobile-Detect#589]
I am using this plugin to split traffic based on whether a user is on a mobile device or not. My company recently ran into an issue where we were reported for "cloaking" https://en.wikipedia.org/wiki/Cloaking. Is there any reason why version 2.8.22 would direct spiders to different pages than users?

**Comment by djarrin** [comment]
Could this have something to do with the $utilities array on line 547 of Mobile_Detect.php? I notice there is some stuff in there about bots (specifically Googlebot). If I just got rid of that (delete line 981 of Mobile_Detect.php) I would then be in the clear and bots and users would be redirected the same?

**Comment by serbanghita** [comment]
@djarrin for the moment Mobile Detect doesn't treat bots as mobile. You need to use `$mobile->isBot()` or `$mobile->isMobileBot()`
