### ISSUE TITLE
Samsung Tab A SM-T335Y 8 inch Tab detecting as Phone

### ISSUE THREAD

**Issue by hzzg6y** [serbanghita/Mobile-Detect#590]
Please see the below result. Recently I brought at 8 Inch Samsung Tab A SM-T335Y  ... This is clearly a tab however it is showing as phone. ... Please advice.  

Mobile_Detect v. 2.8.21

The lightweight PHP class for detecting mobile devices.

This is a phone. Your UA is Mozilla/5.0 (Linux; Android 6.0.1; SM-T355Y Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Safari/537.36

Please help us improve the mobile detection by choosing the correct answer.
Before sending an answer double check if you are using the browser in 'Desktop mode'.
You can contribute by:
1. forking the project
2. submiting an issue
3. sending us feedback below

Contribute
Is your device really a phone?

Additional feedback:

♥ Yes, it's correct. No, it's wrong!
Supported methods

Basic detection methods
isMobile() bool(true)
isTablet() bool(false)
Custom detection methods
isiPhone() bool(false)
isBlackBerry() bool(false)
isHTC() bool(false)
isNexus() bool(false)
isDell() bool(false)
isMotorola() bool(false)
isSamsung() bool(false)
isLG() bool(false)
isSony() bool(false)
isAsus() bool(false)
isMicromax() bool(false)
isPalm() bool(false)
isVertu() bool(false)
isPantech() bool(false)
isFly() bool(false)
isWiko() bool(false)
isiMobile() bool(false)
isSimValley() bool(false)
isWolfgang() bool(false)
isAlcatel() bool(false)
isNintendo() bool(false)
isAmoi() bool(false)
isINQ() bool(false)
isGenericPhone() bool(false)
isiPad() bool(false)
isNexusTablet() bool(false)
isSamsungTablet() bool(false)
isKindle() bool(false)
isSurfaceTablet() bool(false)
isHPTablet() bool(false)
isAsusTablet() bool(false)
isBlackBerryTablet() bool(false)
isHTCtablet() bool(false)
isMotorolaTablet() bool(false)
isNookTablet() bool(false)
isAcerTablet() bool(false)
isToshibaTablet() bool(false)
isLGTablet() bool(false)
isFujitsuTablet() bool(false)
isPrestigioTablet() bool(false)
isLenovoTablet() bool(false)
isDellTablet() bool(false)
isYarvikTablet() bool(false)
isMedionTablet() bool(false)
isArnovaTablet() bool(false)
isIntensoTablet() bool(false)
isIRUTablet() bool(false)
isMegafonTablet() bool(false)
isEbodaTablet() bool(false)
isAllViewTablet() bool(false)
isArchosTablet() bool(false)
isAinolTablet() bool(false)
isSonyTablet() bool(false)
isPhilipsTablet() bool(false)
isCubeTablet() bool(false)
isCobyTablet() bool(false)
isMIDTablet() bool(false)
isMSITablet() bool(false)
isSMiTTablet() bool(false)
isRockChipTablet() bool(false)
isFlyTablet() bool(false)
isbqTablet() bool(false)
isHuaweiTablet() bool(false)
isNecTablet() bool(false)
isPantechTablet() bool(false)
isBronchoTablet() bool(false)
isVersusTablet() bool(false)
isZyncTablet() bool(false)
isPositivoTablet() bool(false)
isNabiTablet() bool(false)
isKoboTablet() bool(false)
isDanewTablet() bool(false)
isTexetTablet() bool(false)
isPlaystationTablet() bool(false)
isTrekstorTablet() bool(false)
isPyleAudioTablet() bool(false)
isAdvanTablet() bool(false)
isDanyTechTablet() bool(false)
isGalapadTablet() bool(false)
isMicromaxTablet() bool(false)
isKarbonnTablet() bool(false)
isAllFineTablet() bool(false)
isPROSCANTablet() bool(false)
isYONESTablet() bool(false)
isChangJiaTablet() bool(false)
isGUTablet() bool(false)
isPointOfViewTablet() bool(false)
isOvermaxTablet() bool(false)
isHCLTablet() bool(false)
isDPSTablet() bool(false)
isVistureTablet() bool(false)
isCrestaTablet() bool(false)
isMediatekTablet() bool(false)
isConcordeTablet() bool(false)
isGoCleverTablet() bool(false)
isModecomTablet() bool(false)
isVoninoTablet() bool(false)
isECSTablet() bool(false)
isStorexTablet() bool(false)
isVodafoneTablet() bool(false)
isEssentielBTablet() bool(false)
isRossMoorTablet() bool(false)
isiMobileTablet() bool(false)
isTolinoTablet() bool(false)
isAudioSonicTablet() bool(false)
isAMPETablet() bool(false)
isSkkTablet() bool(false)
isTecnoTablet() bool(false)
isJXDTablet() bool(false)
isiJoyTablet() bool(false)
isFX2Tablet() bool(false)
isXoroTablet() bool(false)
isViewsonicTablet() bool(false)
isOdysTablet() bool(false)
isCaptivaTablet() bool(false)
isIconbitTablet() bool(false)
isTeclastTablet() bool(false)
isOndaTablet() bool(false)
isJaytechTablet() bool(false)
isBlaupunktTablet() bool(false)
isDigmaTablet() bool(false)
isEvolioTablet() bool(false)
isLavaTablet() bool(false)
isAocTablet() bool(false)
isMpmanTablet() bool(false)
isCelkonTablet() bool(false)
isWolderTablet() bool(false)
isMiTablet() bool(false)
isNibiruTablet() bool(false)
isNexoTablet() bool(false)
isLeaderTablet() bool(false)
isUbislateTablet() bool(false)
isPocketBookTablet() bool(false)
isKocasoTablet() bool(false)
isHudl() bool(false)
isTelstraTablet() bool(false)
isGenericTablet() bool(false)
isAndroidOS() bool(true)
isBlackBerryOS() bool(false)
isPalmOS() bool(false)
isSymbianOS() bool(false)
isWindowsMobileOS() bool(false)
isWindowsPhoneOS() bool(false)
isiOS() bool(false)
isMeeGoOS() bool(false)
isMaemoOS() bool(false)
isJavaOS() bool(false)
iswebOS() bool(false)
isbadaOS() bool(false)
isBREWOS() bool(false)
isChrome() bool(true)
isDolfin() bool(false)
isOpera() bool(false)
isSkyfire() bool(false)
isIE() bool(false)
isFirefox() bool(false)
isBolt() bool(false)
isTeaShark() bool(false)
isBlazer() bool(false)
isSafari() bool(false)
isTizen() bool(false)
isUCBrowser() bool(false)
isbaiduboxapp() bool(false)
isbaidubrowser() bool(false)
isDiigoBrowser() bool(false)
isPuffin() bool(false)
isMercury() bool(false)
isObigoBrowser() bool(false)
isNetFront() bool(false)
isGenericBrowser() bool(false)
isPaleMoon() bool(false)
Experimental version() method
version(Build) string(6) "MMB29M"
version(Chrome) string(13) "53.0.2785.124"
version(Safari) string(6) "537.36"
version(Webkit) string(6) "537.36"
version(Android) string(5) "6.0.1"
Other tests
isiphone() bool(false)
isIphone() bool(false)
istablet() bool(false)
isIOS() bool(false)
isWhateverYouWant() bool(false)
Debug
Matching Regex string(48) "\bCrMo\b|CriOS|Android._Chrome/[.0-9]_ (Mobile)?"
Matching Array array(1) { [0]=> string(98) "Android 6.0.1; SM-T355Y Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 " }

**Comment by hzzg6y** [comment]
Please can you help or guide me in the code what changes are required & where I need to make the changes in Mobiledetect.php file to have correctly detect that it is tablet. Please advice.  I am using PHP file for detection instead of json.

**Comment by serbanghita** [comment]
@hzzg6y thanks, added this to the next patch! I'll close this when it's live!
