### ISSUE TITLE
Asus memo8, model K011 not detected as tablet

### ISSUE THREAD

**Issue by nvsdesign** [serbanghita/Mobile-Detect#592]
This is a phone. Your UA is Mozilla/5.0(Linus; Android 4.4.2; K011 Build/KOT49H)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/53.0.2785.124 Safari/537.36

**Comment by serbanghita** [comment]
@nvsdesign thank you, investigating

**Comment by nvsdesign** [comment]
Issue looks te be solved in the other threat, but does this fix automatically apply or do I have to modify the mobile_detect.php file?

**Comment by serbanghita** [comment]
Added this to the next patch.
