### ISSUE TITLE
Tablet Samsung Galaxy Tab A 10.1" SM-T580 is being detected as a Phone.

### ISSUE THREAD

**Issue by pantaluna** [serbanghita/Mobile-Detect#598]
Hi, thanks for your work for this project.
I accidentally came across this issue, and I thought it was more than fair to let you know.

PHP Mobile-Detect @version 2.8.22

This popular tablet is unfortunately detected as a phone, not a tablet. It is currently the top sold Samsung 10" tablet in Europe.

User Agent:
Mozilla/5.0 (Linux; Android 6.0.1; SM-T580 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.68 Safari/537.36

Product info:
    http://www.samsung.com/us/mobile/tablets/all-other-tablets/sm-t580nzkaxar-sm-t580nzkaxar/
    Android Marshmallow 6.0
    Google Chrome 54.0

Info from http://demo.mobiledetect.net/:
    This is a phone.
    isMobile() bool(true)
    isTablet() bool(false)
    ....
    isSamsung() bool(false)
    isAndroidOS() bool(true)
    isChrome() bool(true)
    ....
    Debug:
        Matching Regex: "\bCrMo\b|CriOS|Android.*Chrome/[.0-9]* (Mobile)?"
        Matching Array: array(1) { [0]=> string(96) "Android 6.0.1; SM-T580 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.68 " }

**Comment by serbanghita** [comment]
@pantaluna thanks a lot for this submission. I have included this in the next patch.
