### ISSUE TITLE
Vivaldi is only developed for computers (yet).

### ISSUE THREAD

**Issue by erolha** [serbanghita/Mobile-Detect#600]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.148 Safari/537.36 Vivaldi/1.4.589.41

Testing from the same computer; both Chrome and Firefox is recognized as computer. When using Vivaldi though, Mobile-Detect interpret the visit to be from a mobile phone.

**Comment by serbanghita** [comment]
My bad. Didn't add tests for Vivaldi. Fixing it now 👍

**Comment by serbanghita** [comment]
Fixed in `2.8.24`
