### ISSUE TITLE
How to switch from mobile view to desktop view

### ISSUE THREAD

**Issue by fx1987** [serbanghita/Mobile-Detect#601]
Hello,

how is it possible to redirect Smartphones / Tablets from the mobile View to the Desktop View. 
I want to have a Button in the Footer on my Mobile Site "Redirect to the Desktop View", for the pepole who want to see the desktop view. 

Thanks in advance

**Comment by serbanghita** [comment]
@fx1987 run this example in your browser: https://github.com/serbanghita/Mobile-Detect/blob/master/examples/session_example.php
