### ISSUE TITLE
Samsung Tablet Galaxy Tab S2 SM-T817A is not detected as a tablet

### ISSUE THREAD

**Issue by droooney** [serbanghita/Mobile-Detect#603]

**Comment by serbanghita** [comment]
@droooney thank you, I will release a patch soon

**Comment by droooney** [comment]
Here's an example of the UserAgent btw: "Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG-SM-T817A Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.98 Safari/537.36".

**Comment by serbanghita** [comment]
Thank a lot!

**Comment by droooney** [comment]
You're welcome!

**Comment by serbanghita** [comment]
@droooney fixed in the latest version.
