### ISSUE TITLE
Galaxy s6 support

### ISSUE THREAD

**Issue by abFx** [serbanghita/Mobile-Detect#608]
user agent

'Mozilla/5.0 (Linux; Android 5.0.2; **SM-G920F** Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36'

**Comment by myfashionhub** [comment]
Galaxy S6 `Mozilla/5.0 (Linux; Android 6.0.1; SM-G920V Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36` evaluates as null. Is there a way to add? It's a pretty popular device.

**Comment by serbanghita** [comment]
@abFx @myfashionhub thank you so much for reporting this, this is fixed in the latest version.
