### ISSUE TITLE
Pixel xl phone support

### ISSUE THREAD

**Issue by abFx** [serbanghita/Mobile-Detect#611]
ua 

'Mozilla/5.0 (Linux; Android 7.1; **Pixel XL Build/NDE63H**) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36'

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.30 thanks for reporting!
