### ISSUE TITLE
Moto X 2nd Gen

### ISSUE THREAD

**Issue by abFx** [serbanghita/Mobile-Detect#612]
ua 

'Mozilla/5.0 (Linux; Android 6.0; **XT1092** Build/MPE24.49-18) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36'

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.30 thanks for reporting!
