### ISSUE TITLE
Moto G 2nd Gen support

### ISSUE THREAD

**Issue by abFx** [serbanghita/Mobile-Detect#613]
ua 

'Mozilla/5.0 (Linux; Android 5.0.2; **XT1068** Build/LXB22.46-28) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36'

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.30 thanks for reporting!
