### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by flippinroo2** [serbanghita/Mobile-Detect#619]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

Hello, I'm trying to use your code for some device tracking. Unfortunately I can't get the code to work properly.

`require_once("php_driven_site/includes/Mobile-Detect-2.8.24/Mobile_Detect.php");
//Variables for device detection
$detect = new Mobile_Detect;
print_r($detect->isMobile());`

When I visit this page with a mobile agent, the code outputs "1". However when I visit the page with a desktop agent the code does not output anything. I've tried casting the output to a (bool) and a few other methods. Do you have any ideas as to what I'm doing wrong?

**Comment by u-mulder** [comment]
What do you expect? bool `true` is printed like `1`, bool `false` is an empty string.

**Comment by metrixsean** [comment]
@flippinroo2 you may want to use var_dump instead of print_r.

**Comment by flippinroo2** [comment]
@u-mulder I expect "true" or "false" to be printed
@metrixsean Thanks! I'll try that now.

**Comment by u-mulder** [comment]
@flippinroo2 Then you need to read a manual. `print_r` prints string representation of a variable. String represenation of a `true` is string `1`, of a `false` - empty string.

**Comment by flippinroo2** [comment]
@u-mulder Thanks for your wise words, I kinda figured false would be 0 like in javascript. Anyways it works now, the var_dump() suggestion worked perfect.
