### ISSUE TITLE
AppleCoreMedia user agent on iPhone and iPad devices is not recognized as iOS device when the client is requesting html5 video data

### ISSUE THREAD

**Issue by akosphp** [serbanghita/Mobile-Detect#620]
The following user agent string (just an example from the many) is not recognized as an iOS device ($detect->isiOS() returns false) when playing html5 video on an iPad or iPhone: 

AppleCoreMedia/1.0.0.11D201 (iPhone; U; CPU OS 7_1_1 like Mac OS X; hu_hu)

On Apple mobile devices the html5 video playback is not running inside the browser instead opened by AppleCoreMedia and therefore the user agent string is not the same as in Safari during a regular html request.

And it would be nice to have a method like isAppleCoreMedia() to detect Apple media player too.

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.30 thanks for reporting! Please check if this is still of interest for you!

**Comment by da2x** [comment]
The fix in commit 581af2b300 is wrong. AppleCoreMedia is also used on macOS so don’t assume it’s iOS.

macOS: `AppleCoreMedia/1.0.0.18A347e (Macintosh; U; Intel Mac OS X 10_14; en_us)`

iOS: `AppleCoreMedia/1.0.0.11D201 (iPhone; U; CPU OS 7_1_1 like Mac OS X; en_us)`
