### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class Mobile_Detect

### ISSUE THREAD

**Issue by Gregory9111** [serbanghita/Mobile-Detect#622]
Hello,

I`m getting following error :

[09-Jan-2017 06:53:42 UTC] PHP Fatal error:  Cannot redeclare class Mobile_Detect in /var/www/vhosts/website.com/httpdocs/libs/MobileDetect/Mobile_Detect.php on line 29

My version is @version     2.8.24

The issue is random for me and not very frequent - can you resolve ?

tnx
Grzegorz

**Comment by Gregory9111** [comment]
Hey all - any idea about that issue ?

**Comment by djarrin** [comment]
Did you edit the plugin at all or have a class declaration of Mobile_Detect anywhere else on your site?

**Comment by fmonts** [comment]
This is not an issue, you included the Mobile_Detect.php twice.

You can use include_once instead of include (or require_once instead of require), for example

**Comment by Gregory9111** [comment]
I use it like this

`	function isMobile()
	{
		
		if( !isset( $_SESSION['ips_mobile'] ) )
		{
			require( LIBS_PATH . '/MobileDetect/Mobile_Detect.php' );
			$detect = new Mobile_Detect;
			$mobile_detect = $detect->isMobile();
			$_SESSION['ips_mobile'] = $mobile_detect;
		}
		
		return $_SESSION['ips_mobile'];
	}`

How it should looks like to work properly ?

**Comment by u-mulder** [comment]
When you call your `isMobile` function more than once, you include `Mobile_Detect.php` more than once. Replace `require` with `require_once`.

**Comment by leegee** [comment]
Used Wordpress to install this, got the same error. Switching to another plugin, but thought you should know.

**Comment by serbanghita** [comment]
Thank you @u-mulder and everyone for the assist on this issue.
