### ISSUE TITLE
Windows 10 Tablets (Acer)

### ISSUE THREAD

**Issue by MackieeE** [serbanghita/Mobile-Detect#624]
Hi there,

Having an issue with Tablet detection for a Windows 10 Tablet, viewing with Firefox. Considering the User Agent String.. is this sadly going to be impossible to detect?

**Firefox**:
```
Mozilla/5.0 (Windows NT 10.0; rv:38.0) Gecko/20100101 Firefox/38.0 
```

**Windows Edge**
```
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, Like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
```

This is with an Acer Switch Tablet:

https://www.acer.com/ac/en/GB/content/model/NT.G8WEK.002

Results of Debug Page for the Windows Edge:
![capture](https://cloud.githubusercontent.com/assets/883702/21848593/7d879f2e-d7f9-11e6-9b91-21f1593e9df2.PNG)

Please let me know if there's anything else I can supply for info :) Love the Library!

**Comment by ThaDafinser** [comment]
@MackieeE can u check if the browser is in "tablet" mode?
I had a similar issue once https://github.com/WhichBrowser/Parser/issues/66

-> Its not possible to detect this way sadly...

**Comment by MackieeE** [comment]
I see! Now that I've read up more on it.. indeed there's not much that can be done.

However I do see this as a bit of a shame as I do think more & more devices will blur the difference between Tablet & Computer over the coming years.

Nor do I see any RFCs that I could find for HTTP 2.x in regards to adapting User-Agent Strings for the wider range of devices we have today.

**Comment by serbanghita** [comment]
@MackieeE @ThaDafinser I added a new section called https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md so that people know about this.

I don't think there is real interest in adding specs for User-Agent in the RFCs since it poses privacy issues.
