### ISSUE TITLE
Safari showing as Opera

### ISSUE THREAD

**Issue by Gazvenn** [serbanghita/Mobile-Detect#627]
Having issues with Safari on iOS devices being interpreted as Opera using  browser() function

fixed issue locally by running is('Safari') on a return if opera and swapping. 

Not sure if this is a local problem or something experienced by everyone but though't I'd raise it.

**Comment by mimmi20** [comment]
@Gazvenn Could you add the useragent here?

**Comment by Gazvenn** [comment]
"Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A405 Safari/601.1"

These are the results I get for the following functions
deviceType() =  string(5) "Phone" 
brand() = string(6) "iPhone" 
os() = string(10) "Unknown OS" 
browser() = string(9) "Opera 9.0"

This is an example which has come from the Iphone 6s test on browserstack. I've since put the check live for logging purposes and getting a return of Opera for almost all Ipads and Iphones which seems very improbable. 

I've put in a temporary fix which just uses the is() function on any that return Opera to check if('Safari') and if that comes back false i leave it otherwise do a str_replace on Opera to Safari leaving the version number.

I've had a look at the actual code used and can't see anything obvious to me that would cause it other than Opera appearing before Safari in the Browsers array.

**Comment by Gazvenn** [comment]
Another addition:

This is from browserstack again for OSX Sierra running safari 10.0 : 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50"

which is returning Opera and returning false on is('Safari')

**Comment by serbanghita** [comment]
Mobile Detect was created only to detect mobile devices, In `2.x` we're not focusing on browser detection.
@mimmi20 do you want me to tag you when similar issues occur?
