### ISSUE TITLE
What is wrong with my code?

### ISSUE THREAD

**Issue by picks44** [serbanghita/Mobile-Detect#631]
Hi, I have an app than runs on desktop, tablets (iOS + Android) and phones (iOS + Android), so I'm trying to register each user on a different device with this library. For some reason, my code is not working at all (all users are registered as "Desktop"). Here is it, can you help?

```php
require_once __DIR__.'/Mobile_Detect.php';
function getDevice() {
    $detect = new Mobile_Detect;
    $device = 'Desktop';
    if ($detect->isMobile() && !$detect->isTablet()){
        if ($detect->isiOS()) {
            $device = 'Mobile (iOS)';
        }
        if ($detect->isAndroidOS()){
            $device = 'Mobile (Android)';
        }
    }
    if ($detect->isTablet()){
        if ($detect->isiOS()){
            $device = 'Tablet (iOS)';
        }
        if ($detect->isAndroidOS()){
            $device = 'Tablet (Android)';
        }
    }
    return $device;
}
```

**Comment by carusogabriel** [comment]
Did you solve this problem?

**Comment by pothi** [comment]
Just wanted to say thanks for your code. It works fine for me! Tested it on real devices (mobile and tablet)!

If it doesn't work for you (or someone else), please post your User-Agent string! On a real device/s, the library is expected to work correctly.

Only once, the library didn't work. It was when I used the following...

`curl -A 'iPhone' http://localhost/test.php` where `test.php` contained the code mentioned by OP.

I hope this helps someone in the future!

**Comment by serbanghita** [comment]
Code looks good to me. This is clearly a debug issue. Thanks @pothi for the assist.
