### ISSUE TITLE
iPhone user agent not recognized

### ISSUE THREAD

**Issue by seattleannie** [serbanghita/Mobile-Detect#633]
The current mobile detect file fails to detect the following, which I believe was a recent Apple update:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1

Is an update of the mobile detect in the works? How soon will it be available?

**Comment by seattleannie** [comment]
Never mind! I resolved the issue.

**Comment by jasperf** [comment]
How did you solve this @seattleannie ?
