### ISSUE TITLE
Kindle Fire Gen. 5 and Fire Gen. 8 wont get detected by isKindle()

### ISSUE THREAD

**Issue by mafudelaptu** [serbanghita/Mobile-Detect#634]
isKindle() returns false at that User-Agent: 

> Mozilla/5.0 (Linux; Android android-version; product-model Build/product-build) AppleWebKit/webkit-version (KHTML, like Gecko) 
>     Silk/browser-version like Chrome/chrome-version Safari/webkit-version

Source: http://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html

Quickfix by me: 

on Line: 225 in Mobile_Detect.php:
'Kindle'            => 'Kindle|Silk.*Accelerated|Android.*\b(KFOT|KFTT|KFJWI|KFJWA|KFOTE|KFSOWI|KFTHWI|KFTHWA|KFAPWI|KFAPWA|WFJWAE|KFSAWA|KFSAWI|KFASWI|KFARWI)\b',

add: "Silk*" in Detection String

'Kindle'            => 'Kindle|Silk*|Silk.*Accelerated|Android.*\b(KFOT|KFTT|KFJWI|KFJWA|KFOTE|KFSOWI|KFTHWI|KFTHWA|KFAPWI|KFAPWA|WFJWAE|KFSAWA|KFSAWI|KFASWI|KFARWI)\b',

**Comment by serbanghita** [comment]
@mafudelaptu that will conflict with the desktop detection. I'm researching this.

**Comment by tr33m4n** [comment]
@serbanghita Any update on this?

**Comment by serbanghita** [comment]
@mafudelaptu @tr33m4n I close this because I couldn't find any decent solution to integrate `Silk*` regex.
