### ISSUE TITLE
Browser Detection doesnt work if loading from a PC

### ISSUE THREAD

**Issue by marlowmedia** [serbanghita/Mobile-Detect#635]
Hi,

I'm using your script to log information of my visitors when using a tablet and mobile, I've also created a if statement so if mobile or tablet isnt true then it means its a PC/Laptop. How ever for what ever reason your script fails to detect the browser used if a PC/Laptop is used?

I understand this script is used to detect mobile/tablet devices but you must understand that alot of people will also use this script to also help identify people who use a PC/Laptop. I've tried your script and also your demo page on both my laptop and my PC on Chrome, Firefox and IE and all browsers show as False.

Please could you fix this.

Thank you and great work by the way.

**Comment by serbanghita** [comment]
I think you need a browser sniffer. Can someone please recommend a PHP script that does that?
