### ISSUE TITLE
Update 7.x

### ISSUE THREAD

**Issue by gabriel-caruso** [serbanghita/Mobile-Detect#638]
What about that create a branch for PHP 7.x?

**Comment by serbanghita** [comment]
Please submit a pull-request, at the moment I don't have enough time on my hands to make a separate branch for PHP 7

**Comment by carusogabriel** [comment]
Did it
#639

**Comment by carusogabriel** [comment]
@serbanghita i did the #639 PR, but I realize I didn't create a branch and some other issues. I'll revise the code, create the branch and make another PR

**Comment by carusogabriel** [comment]
New PR #641
