### ISSUE TITLE
Tablet ARCHOS 97C Platinium / 1024 x 768 / Android 6.0 not detected as tablet

### ISSUE THREAD

**Issue by stephadz** [serbanghita/Mobile-Detect#642]
The user agent is : 
Mozilla/5.0 (Linux; Android 6.0; Archos 97c Platinum Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Safari/537.36

isMobile > true
isTablet > false

Archos 97c Platinum is a real tablet.

Screenshot of demo.mobiledetect.net
![mobile_detect_demo](https://cloud.githubusercontent.com/assets/18679896/24144616/3763522a-0e2e-11e7-8764-86ddccf20427.png)

**Comment by serbanghita** [comment]
This is already solved in the latest version
