### ISSUE TITLE
How to stop w3 total cache from caching mobile detect script?

### ISSUE THREAD

**Issue by a7medm7med** [serbanghita/Mobile-Detect#644]
Hello,
I used mobile detect script manually without any plugins and it's really perfect but I found a big issue that w3 total cache stopped mobile detect script from working, How can solve this issue?

Can I use Rejected user agents field to solve this issue ?

**Comment by serbanghita** [comment]
I think this is a known issue. I don't have a solution yet, there is one planned for `3.x`, but that version was delayed due to lack of time. See https://github.com/serbanghita/Mobile-Detect/issues/180

**Comment by topraf** [comment]
Hey! any news on this issue with caching on W3 total cache? Thanks!

**Comment by JuegosGames** [comment]
Hello, I have the same issue, but with WP-Rocket (at [https://juegos.games](Juegos.Games)), only when the cache is purged the mobile detection works.

**Comment by JuegosGames** [comment]
Hello, I have the same issue at [Juegos Games](https://juegos.games), but I think I solved it disabling page cache, and leaving "On" only minify and combine.
