### ISSUE TITLE
isChrome detected as false, on Computer

### ISSUE THREAD

**Issue by kingsley22** [serbanghita/Mobile-Detect#645]
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by kingsley22** [comment]
Version worked though.
Experimental version() method
version(Chrome)	string(12) "55.0.2883.87"
version(Safari)	string(6) "537.36"
version(Webkit)	string(6) "537.36"
version(Windows NT)	string(3) "6.1"

**Comment by serbanghita** [comment]
@kingsley22 yes, this is a known issue for `2.x`, we currently only focus on detecting `mobile` browsers.

**Comment by kingsley22** [comment]
Yeah I realised that after I made the comment!
