### ISSUE TITLE
can we use this to detect Wechat? 

### ISSUE THREAD

**Issue by videni** [serbanghita/Mobile-Detect#646]

**Comment by mimmi20** [comment]
Could you provide the useragent?

**Comment by serbanghita** [comment]
Someone previously suggested this https://github.com/serbanghita/Mobile-Detect/issues/498
That should pass as a mobile. If you provide a UA we can investigate.

**Comment by videni** [comment]
Mozilla/5.0 (Linux; Android 6.0; PRO 6 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043115 Safari/537.36 MicroMessenger/6.5.6.1020 NetType/WIFI Language/zh_CN
