### ISSUE TITLE
s4 mini & chrome

### ISSUE THREAD

**Issue by koutsenko** [serbanghita/Mobile-Detect#649]
Not new phone, but has Android official 4.4.2 fw and can run latest Chrome smoothly.
Problem is md.phone() output for Chrome:
- Android browser: Samsung
- Chrome 57: UnknownPhone

UserAgent is:
`Mozilla/5.0 (Linux; Android 4.4.2; GT-I9190 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36`

**Comment by serbanghita** [comment]
Fixed in the latest version. Thanks for reporting!
