### ISSUE TITLE
Missing UserAgentHeaders

### ISSUE THREAD

**Issue by jasonlam604** [serbanghita/Mobile-Detect#658]
Referring to **devel3-workinprogress** branch, are you going to commit your latest changes to this branch any time in the near future?  Current state seems to broken at least from unit test perspective.

```
MobileDetectTests\FunctionalTests\DetectingTest::testAnUserAgentOfAPhoneThatContainsBrowserAndOperatingSystemModelAndVersionInformationAreReturnedInThePropsArray
Error: Class 'MobileDetect\Repository\UserAgentHeaders' not found
```
I'm looking to contribute.

**Comment by serbanghita** [comment]
@jasonlam604 I haven't touched it in a while, I need to get back and finish it. Do you want to be notified when I have an MVP working version?

**Comment by serbanghita** [comment]
@jasonlam604 you can also join the Slack chan to keep in touch there
