### ISSUE TITLE
How to get browser and os directly?

### ISSUE THREAD

**Issue by slince** [serbanghita/Mobile-Detect#660]
The library is rellay helpful. However  I think it needs to be enhanced

Gets the current client details directly.
```
$detector->getOS(); //returns Android, IOS, Window10 .. and so on
$detector->getBrowser() //returns chrome,firefox,IE...
$detector->getBrowserVersion() //returns chrome,firefox,IE...
```

**Comment by dabajabaza** [comment]
@slince, hi. Why did you close this issue? Is there a way to detect browser, OS and device? If so how can I do it?

**Comment by u-mulder** [comment]
Issue is closed because it is **not** an issue. Detecting operation systems, browsers and other stuff is not this library's responsibility.

**Comment by slince** [comment]
@dabajabaza  Hi, u can see this [https://github.com/matomo-org/device-detector](https://github.com/matomo-org/device-detector)

**Comment by dabajabaza** [comment]
@u-mulder , @slince  thanks for helping me.

**Comment by serbanghita** [comment]
🍻  thank you for providing quick support!
