### ISSUE TITLE
Mobile detection accuracy

### ISSUE THREAD

**Issue by gety9** [serbanghita/Mobile-Detect#661]
Guys, newbie question here:

At the moment we are using matched expression to detect mobile(phone) users and load mobile theme, this is the expression:
`(iPhone|iPod|BlackBerry|Pre|Palm|Googlebot-Mobile|mobi|Safari Mobile|Windows Mobile|Android|Opera Mini|mobile)|(!iPad|Silk|Kindle|Xoom|SCH-I800|Tablet)`

We do not need to detect any detailed things - like browser, OS, Iphone or Android, etc.
Just mobile(phone) or not.

Would using Mobile-Detect isMobile() function be more accurate than 
matched expression i've mentioned above?

If yes, please explain why.

p.s. at the moment we are using magento default matched expression functionality:
https://puu.sh/w1K6w/047a4cbd5b.png

**Comment by gety9** [comment]
Guys, please comment on the question,
i need to understand it.

**Comment by serbanghita** [comment]
@gety9 I think you can never really rely on regexes. From the regex that you gave above you might have false positives, especially with `Pre` and `Palm`. You could use the Magento ports from here https://github.com/serbanghita/Mobile-Detect/blob/master/README.md
