### ISSUE TITLE
Fatal error: Cannot redeclare class Mobile_Detect

### ISSUE THREAD

**Issue by markota** [serbanghita/Mobile-Detect#665]
I have php report maker 10 and this issue appears 
Fatal error: Cannot redeclare class Mobile_Detect in C:\xampp\htdocs\q-panel\mobile_detect.php on line 29
Can you help?
Davor

**Comment by Barmaley74** [comment]
Hi!

You need add this line in file Mobile_Detect.php at the beginning of file before declaration of class Mobile_Detect

if ( !class_exists('Mobile_Detect') ) {

}

**Comment by serbanghita** [comment]
Thanks @Barmaley74 for the assist. @markota also you can make sure you use `require` instead of `include`.
