### ISSUE TITLE
Телефоны Lenovo

### ISSUE THREAD

**Issue by iPSWeb** [serbanghita/Mobile-Detect#666]
Отличная библиотека.
НО в библиотеке отсутствует определение телефонов Lenovo.
Как добавить определение телефонов Lenovo?
С Уважением

**Comment by u-mulder** [comment]
Do you think everyone on github speaks Russian?

**Comment by gremboloid** [comment]
iPSWeb, just add to List of mobile devices (phones)

**Comment by iPSWeb** [comment]
gremboloid, how can this be done?

**Comment by gremboloid** [comment]
in Mobile_Detect.php add item to array $phoneDevices
 something like:
'Lenovo'      => 'S2005A-H|Lenovo.*(A850|A916|A536|S820e|A859|A2010|P1a42)',

all UA Lenovo smartphones see in http://www.handsetdetection.com/properties/devices/Lenovo
