### ISSUE TITLE
Tablet Microsoft RT Surface 32 GB / 1366x768 / Windows / is not detected as tablet

### ISSUE THREAD

**Issue by bkosun** [serbanghita/Mobile-Detect#667]
The user agent is:
`Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0; Touch; rv:11.0) like Gecko`

```
isMobile() bool(true)
isTablet() bool(false)
```

Microsoft RT Surface 32 GB is a real tablet.

demo.mobiledetect.net:
![20170704_171925](https://user-images.githubusercontent.com/16259603/27834424-a1bf5264-60df-11e7-86ec-04c731fe29f8.jpg)

**Comment by rainmaker666** [comment]
+1
