### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by LuisMejiaF** [serbanghita/Mobile-Detect#668]
I'm not sure if this should be included in this package, but I'm having an issue where I need to know if the user is visiting the site from a Progressive Web App or the Mobile Browser.

The user agent string I get when I open my PWA in iOS is:

`Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89`

I'm using iPhone 5s, with iOS 10.3.2 (14F89).

**Comment by kavatari** [comment]
But it is still an iPhone (isiPhone()) and an mobile device. For which reason do you want to know is it an PWA?

**Comment by LuisMejiaF** [comment]
Mostly because analytics. I would like to know if the user made certain request to the API from the mobile website, or from the PWA. Know from where the user is navigating. Yes, it shows isiPhone true, but which browser? Chrome for iOS? Safari on iOS? or from the PWA? That's what we would like to know.

Also because we can limit certain features depending on the browser.... but I know, we should be using Modernizr for that instead.

**Comment by serbanghita** [comment]
@LuisMejiaF but PWA is just a concept [0], we cannot detect that, unless you are referring to something else.

[0] https://developers.google.com/web/progressive-web-apps/
