### ISSUE TITLE
VERIZON ELLIPSIS 8" TABLET not detected

### ISSUE THREAD

**Issue by oscar-castaneda** [serbanghita/Mobile-Detect#671]
This tablet today was detected as mobile but not as a tablet.

**Comment by mimmi20** [comment]
Please add the useragent.

**Comment by oscar-castaneda** [comment]
Mozilla/5.0(LInux;Android 5.1.1;QTAQTZ3 Build/LMY47V) 
AppleWebKit/537.36(KHTML, like Gecko)
Chrome/59.0.3071.125 Safari/537.36

**Comment by oscar-castaneda** [comment]
Any news on this?
Is there a way I can help to make it work?

**Comment by oscar-castaneda** [comment]
Serbanghita, I just tested the tablet and still shows as a phone.

**Comment by serbanghita** [comment]
@oscar-castaneda change will be available in `2.8.29`. Thanks for the info!
