### ISSUE TITLE
Oreo on Pixel

### ISSUE THREAD

**Issue by ontoplocal** [serbanghita/Mobile-Detect#679]
Pixel just got Oreo (Android 8.0) and now is not found to be "isMobile".

**Comment by jasonswan** [comment]
Can you provide the output from http://demo.mobiledetect.net/?

I just tried this on my Pixel XL which has Android 8.0 on it and its working corectly:

![screenshot_20170913-165231 1](https://user-images.githubusercontent.com/2192881/30406088-73597b78-98a4-11e7-9f16-aee7bc5783c7.png)

**Comment by serbanghita** [comment]
@ontoplocal I need the UA.
@jasonswan thank you for the assist
