### ISSUE TITLE
FreeFind search engine Missing

### ISSUE THREAD

**Issue by Fede72** [serbanghita/Mobile-Detect#681]
Hi, 

may you add also the FreeFind user agent? Is related to FreeFind search engine.

Thanks

 "Mozilla/5.0 (compatible; freefind/2.1; +http://www.freefind.com/spider.html)"

**Comment by serbanghita** [comment]
@JayBizzle this could be in your interest. Let me know if you want to forward this kind of issues to you.

@Fede72 In `2.x` we are not adding any new bots. We're focusing on mobile detection only.

**Comment by JayBizzle** [comment]
@serbanghita yeah, feel free to tag me in anything you think relevant! 

Having said that, this one is already covered by us...

https://crawlerdetect.io/?q="Mozilla/5.0%20(compatible;%20freefind/2.1;%20+%20http://www.freefind.com/spider.html%20)"

Thanks again! 👍
