### ISSUE TITLE
isBot() ? Version 2

### ISSUE THREAD

**Issue by timothymarois** [serbanghita/Mobile-Detect#682]
Shouldn't there be a way to detect if it's a bot? You already have the user agent check for `utilities` so there should be a method for `isBot()`, maybe there is, but I didn't see it within the code.

**Comment by webgeek154** [comment]
That would be great.  It would allow me to block bots easily!

**Comment by timothymarois** [comment]
Requesting this pull here, It looks like someone already started that process #656

**Comment by serbanghita** [comment]
Not on the `2.x` current version, I don't have time to focus my energy on bot detection.
