### ISSUE TITLE
How to detect iPod Touch?

### ISSUE THREAD

**Issue by ownJakeProject** [serbanghita/Mobile-Detect#684]
Hey,
How would I detect an iPod Touch? I can see iPod in the code, however I don't see an function...
Any help is appreciated, thanks!

**Comment by serbanghita** [comment]
@ownJakeProject iPod touch has these variants:

`Mozilla/5.0 (iPod touch; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1`
or 
`Mozilla/5.0 (iPod; CPU iPhone OS 6_1_6 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B500 Safari/8536.25`

you could use the `\bipod\b` regex
