### ISSUE TITLE
isFirefox() | bool(false) > wrong

### ISSUE THREAD

**Issue by daybugging** [serbanghita/Mobile-Detect#686]
This is a computer. Your UA is Mozilla/5.0 (Windows NT 6.1; rv:56.0) Gecko/20100101 Firefox/56.0

```
isFirefox() | bool(false)
```

.. which is false? See #635 and #523, any ideas how to fix it?

**Comment by serbanghita** [comment]
@daybugging it's because the Mobile Detect was not intended to be a browser sniffer but rather a mobile detector. This will work in the next major version.
