### ISSUE TITLE
Edge Preview on Android 

### ISSUE THREAD

**Issue by Findiglay** [serbanghita/Mobile-Detect#687]
Edge Preview 1.0.0.1008 on Android 7.0.0 (Samsung S6) has the following user agent string:

```
Mozilla/5.0 (Linux; Android 7.0; SM-G920F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.0 Mobile Safari/537.36
```
It wouldn't seem there is any way to distinguish this as Edge?

**Comment by serbanghita** [comment]
@Findiglay unfortunately there is no clue in the UA.
