### ISSUE TITLE
Fatal error: Cannot redeclare class Mobile_Detect

### ISSUE THREAD

**Issue by alrawhani** [serbanghita/Mobile-Detect#688]
Hello,
I am getting this error when activating the shoppystore theme in the wordpress,
Error:
Fatal error: Cannot redeclare class Mobile_Detect in /home/UserName/DomainNameHere/wp-content/themes/shoppystore/lib/mobile-detect.php on line 29

Any help please to remove this error and activate the theme

**Comment by u-mulder** [comment]
`Cannot redeclare class` is a standard php error. YOu can google __what__ to do in this case.

**Comment by emirb** [comment]
You're probably using require instead of require_once in your WP theme to load mobile detect.

**Comment by pothi** [comment]
To add to what's already mentioned...

Here's the code that'd make sure the library is included only once...

`if( ! class_exists( 'Mobile_Detect' ) ) require_once( __DIR__ . '/path/to/Mobile_Detect.php' );`

**Comment by serbanghita** [comment]
Thanks @u-mulder , @emirb and @pothi for the assist!
