### ISSUE TITLE
Fatal error: Class 'Detection\MobileDetect' not found

### ISSUE THREAD

**Issue by Mr-viv1gupta** [serbanghita/Mobile-Detect#689]
After installing Mobile-Detect Module on Magento 2, i'm facing this problem on reloading my website.
Fatal error: Class 'Detection\MobileDetect' not found in /var/www/html/xxxxx/xxxxxxx/app/code/Eadesigndev/Mobiledetect/Helper/MobileDetectModifier.php on line 30 .

Can anyone tell me what has happened. How to solve this?
Please help

**Comment by serbanghita** [comment]
@Mr-viv1gupta I have no idea because I'm not using Magento and I cannot test it. Can you redirect this to the devs who created the Magento module?
