### ISSUE TITLE
Chrome is detected as Android

### ISSUE THREAD

**Issue by davidsielert** [serbanghita/Mobile-Detect#693]
Chrome Version 62.0.3202.89 (Official Build) (64-bit) on OSX is detecting as android !

**Comment by davidsielert** [comment]
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Mobile Safari/537.36

**Comment by davidsielert** [comment]
This happens when Chrome Devtools is open..

**Comment by jayant-lumino** [comment]
@davidsielert Did you find the solution?

**Comment by serbanghita** [comment]
@jayant-lumino the problem here was the user agent which contains: 'Android 6.0' + 'Nexus 5'
