### ISSUE TITLE
iPhone not detected as Mobile

### ISSUE THREAD

**Issue by fvhaaren** [serbanghita/Mobile-Detect#699]
I just downloaded the 2.8.26 verion and used the class on my webpage. When I open my page on my iPhone 6 then the current version doesnt detect it as a phone.

When using print_r of the variable that is used to call the Mobile_Detect class I get that the useragent is as follows:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/10.0 Safari/602.1.31

Am I doing something incorrect?

**Comment by mimmi20** [comment]
Did you activate the desktop mode?
