### ISSUE TITLE
New 3rd party module

### ISSUE THREAD

**Issue by pothi** [serbanghita/Mobile-Detect#700]
Name, Link and Description of the module

**Name**: Mobile Detect (for WordPress)
**Link**: https://wordpress.org/plugins/tinywp-mobile-detect/
**Description**: WordPress has a built-in function (`wp_is_mobile()`) to detect mobile devices. There is (at least) one catch, though. It considers iPad (iPad pro, and any tablet) as a mobile. So, this 3rd party module changes the way `wp_is_mobile()` works with the help of Mobile Detect PHP library!

**Comment by serbanghita** [comment]
Added to `README.md`
