### ISSUE TITLE
Public Slack invite please?

### ISSUE THREAD

**Issue by pothi** [serbanghita/Mobile-Detect#701]
With version 2.8.28, I see, a new Slack chat badge has been added. It'd be awesome to have a public invite so that anyone can join. Probably, you may consider something like [SlackIn](https://github.com/rauchg/slackin). Thank you.

**Comment by serbanghita** [comment]
@pothi I had no idea that the channel needs invite. What happens when you click on the Slack badge from the README.md?

**Comment by serbanghita** [comment]
Ok I get it, I'm going to update the link to https://join.slack.com/t/mobiledetect/shared_invite/enQtMjg1NDY0OTg5NzgzLTcwMzEzMWJjZjRlOWFkY2ZiNzE1ZmRmNzEwM2VhOGY5OGVkYWMxNjdkZDU5YjQ5MmM5MGUxYjhlZDQwOGVjZjE

@pothi thanks for pointing this out!
