### ISSUE TITLE
Lenovo Tab3 8 Plus TB-8703F not detected as tablet

### ISSUE THREAD

**Issue by PaddyHu** [serbanghita/Mobile-Detect#704]
**Issue description**
Lenovo Tab3 8 Plus TB-8703F  is detected as a mobile, but not as a tablet.

**User-Agent(s)**
Mozilla/5.0 (Linux; Android 6.0.1; Lenovo TB-8703F Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.30 thanks for reporting!
