### ISSUE TITLE
Add Lenovo Mobiles

### ISSUE THREAD

**Issue by Faisal-Manzer** [serbanghita/Mobile-Detect#706]
Mozilla/5.0 (Linux; Android 7.0; Lenovo P2a42 Build/NRD90N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36

Add Lenovo to the list...

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.30 thanks for reporting!
