### ISSUE TITLE
How can I detect browser version, if at all?

### ISSUE THREAD

**Issue by yehudaTiram** [serbanghita/Mobile-Detect#710]
I develop a WP theme and I use CSS Grid for the layout. CSS Grid is not supported by all browsers, so I need to detect (PHP) the browser version.
I already use Mobile-Detect in my theme and it works great and detect the mobile devices, but I am not sure if browser version detection is included in its functions. 
(I tried to look into the code but could not find any)
I hope my question is clear.

User-Agent(s) - any

If this feature is not supported, I suggest adding it if possible. It will help a lot with code incompatibilities issues. CSS Grid is just one example.
Thanks,
Yehuda

**Comment by serbanghita** [comment]
@yehudaTiram Mobile Detect doesn't replace the your responsive web design strategy. You can create your own strategy by looking at https://caniuse.com/css-grid and see what browsers are supporting it. Then you can also use a Graceful Degradation or Progressive Enhancement technique depending on your website. This basically means that you offer a different but good experience for browsers that don't support CSS Grid.

If I were you I would build the website using CSS Grid and then test it in IE, Edge and provide either hacks or a good degradation/fallback CSS.

**Comment by yehudaTiram** [comment]
@serbanghita Thank you. I already did use Graceful Degradation. Just thought it could be a good use for this class. 
I get your point though.
Thanks.

**Comment by hgoebl** [comment]
@yehudaTiram you might have a look at https://modernizr.com/

**Comment by yehudaTiram** [comment]
@hgoebl thank you. Didn't think of it.
