### ISSUE TITLE
HUAWAI P8 phone recognized as UnknownTablet

### ISSUE THREAD

**Issue by kaYcee** [serbanghita/Mobile-Detect#711]
**Issue description**
Great lib, but HUAWEI P8 mobile phone detected wrongly as "UnknownTablet"
Edit 1/16: same applies for HUAWEI Honor 8

**User-Agent(s)**
HUAWEI P8:
"Mozilla/5.0 (Linux; Android 6.0; HUAWEI GRA-L09 Build/HUAWEIGRA-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36"

HUAWEI Honor 8:
"Mozilla/5.0 (Linux; Android 7.0; FRD-L09 Build/HUAWEIFRD-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36"

**Suggestions**

**Comment by serbanghita** [comment]
Thanks, I'm looking into this, I think it collides with another regex
