### ISSUE TITLE
Edge on mobile not recognized

### ISSUE THREAD

**Issue by Lupusthai** [serbanghita/Mobile-Detect#715]
Mozilla/5.0 (Linux; Android 7.0; SM-G955F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36 EdgA/41.0.0.1561

I have been browsing with Edge on Samsung S8+ 
Mobile-Detect reports I'm using Chrome 63.0.3239.111

**Comment by bitfrei** [comment]
another UAA (Samsung S7) for Edge Browser:
Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/46.02.4.5145
