### ISSUE TITLE
Confliction in registered Model Name

### ISSUE THREAD

**Issue by anliangdong** [serbanghita/Mobile-Detect#717]
Dear Mobile-Detect Team,

We found our mobile phone model name (Z999 )has been registered by another Indian company named Zync.

// @ref: http://www.zync.in/index.hph/our-products/tablet-phablets

'ZyncTablet'    => 'z1000 | Z99 2G  |z99 | z930 | **z999** | z990 | z909 | z919 | z900'

Mobile-detect recognized our device as "Tablet", and our mobile phone can not display webpage correctly.
[Z999.txt](https://github.com/serbanghita/Mobile-Detect/files/1761149/Z999.txt)

How could we handle this situation? Could M-D team give us some suggestion to fix this issue?
Thanks a lot.

**Comment by serbanghita** [comment]
@anliangdong The `Z999,txt` doesn't help me much. Give me the User-Agents of your devices so I can put them in the unit tests and fix the regexes.

**Comment by anliangdong** [comment]
@serbanghita 
Thanks a lot for your feedback, you could check the attached picture with the UA got by Z999 device.
Z999 is a dual LCDs display mobile phone, not a "tablet", however, it show us "tablet" in picture.
Left side check by default browser called "Weimi", right side check by third party browser called "UC".
Little difference UA values we got between the two browsers.

BTW, Our R&D engineers arranged some comparision test and they tried to modify the model name from Android  [ro.product.model] , just modify the model name from Z999 to another one (for example "ZTE Axon" ). After the modification, this dual LCDs device was detected as "mobile phone".

So, we guess mobile-detect use the device model name from Android[ro.product.model] as one of the conditions to decide the device is phone or tablet... 
Anyway, there are some information we got as your reference, if you need more details please let me know. Thanks a lot.




![img_1177](https://user-images.githubusercontent.com/36431782/36771413-24bf9b5a-1c48-11e8-819f-e1b2a1fd9aae.JPG)

**Comment by serbanghita** [comment]
@anliangdong thanks for this, I will add both User-Agents to the tests and fix the problem. Mobile Detect is written in PHP so it reads the HTTP headers (including the User-Agent) - that's all we know about the device. I'll be back with the fix

**Comment by anliangdong** [comment]
@serbanghita 
Could you please let us know when the 2.8.32 will be released? Thanks.

**Comment by serbanghita** [comment]
@anliangdong I'm trying this week
