### ISSUE TITLE
ASUS ZenPad 8.0 tablet is detected as phone

### ISSUE THREAD

**Issue by officeutils** [serbanghita/Mobile-Detect#718]
Mozilla/5.0 (Linux; Android 6.0.1; P024 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.1.628.01 Safari/537.36

**Comment by serbanghita** [comment]
Was fixed in 2.8.32
