### ISSUE TITLE
Chrome on iOS (CriOS) detection

### ISSUE THREAD

**Issue by peterbo** [serbanghita/Mobile-Detect#72]
Hi there, I stumbled upon a problem, using Chrome on iOS. The Browser is detected as "Chrome". But since CriOS in Browser-Detection resolves to "Chrome" and you use the Browser-Name as property to get the Browser's version, no version can be detected (because it searches for Chrome/[VER] instead of CriOS/[VER]). 2 possible solutions:
- split the userAgent detection into Chrome and CriOS or
- merge the properties Chrome and CriOS to correctly match the version

Cheers
Peter

**Comment by rupendrablogger** [comment]
wow this is great browser - https://www.insurancetips.info/
