### ISSUE TITLE
MobileDetect not working on my hosting server

### ISSUE THREAD

**Issue by yachtkeel** [serbanghita/Mobile-Detect#720]
The plugin seems to work perfectly fine on my localhost, but throws an error on my hosting server.
Am postive that the files exists on the server and linked corrctly; yet am getting an error as if it is not

Warning: require_once(/storage/ssd1/524/4955524/public_html/lib/php/libraries/mobileDetect/mobileDetect.php): failed to open stream: No such file or directory in /storage/ssd1/524/4955524/public_html/index.php on line 7

-------------delete this message-------------
* By submitting a new issue I acknowledge that I already read the README, CODE EXAMPLES and KNOWN LIMITATIONS. 
* I understand that the current version `2.x` is only meant to detect `mobile` devices.
* Please post your User-Agent string! On a real device/s, the library is expected to work correctly.
-------------delete this message-------------

**Issue description**

**User-Agent(s)**

**Suggestions**

**Comment by u-mulder** [comment]
Any other files from this folder can be included?

**Comment by yachtkeel** [comment]
My bad, the testing server is the problem. Sorry guys

**Comment by derUli** [comment]
If your Server is an Unix/Linux based Server the system is case sensitive.
Are you sure that the filename starts with an lowercase m?

**Comment by serbanghita** [comment]
@u-mulder , @derUli thanks for the assist!
