### ISSUE TITLE
Lenovo Tab2 TB2-X30L is detected as phone

### ISSUE THREAD

**Issue by officeutils** [serbanghita/Mobile-Detect#725]
Mozilla/5.0 (Linux; Android 6.0.1; Lenovo TB2-X30L Build/LenovoTB2-X30L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Safari/537.36

**Comment by serbanghita** [comment]
@officeutils thank you, I'm extremely grateful for you providing the UA
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33
