### ISSUE TITLE
Size screen

### ISSUE THREAD

**Issue by ArmandArthur** [serbanghita/Mobile-Detect#728]
Hello,

Is the lib give the size of the screen?

Like this : https://mydevice.io/
Thanks

**Comment by u-mulder** [comment]
You can find size of the screen with javascript. Period.

**Comment by ArmandArthur** [comment]
Yes i can find the size of screen with javascript. But how know determine the name of mobile which the size screen?

**Comment by ArmandArthur** [comment]
Like this : 
id_mobile / name_mobile / size_x / size_y
1             /Samsung Galaxy / 480 / 600

**Comment by serbanghita** [comment]
@ArmandArthur the scope of the library is limited to `isMobile` and `isTablet`, we don't provide device information like resolution. Thanks @u-mulder for the assist!
