### ISSUE TITLE
Onda V10 tablet is detected as phone

### ISSUE THREAD

**Issue by officeutils** [serbanghita/Mobile-Detect#729]
Mozilla/5.0 (Linux; Android 7.0; V10 4G Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.1.628.01 Safari/537.36

**Comment by serbanghita** [comment]
@officeutils thank you 👍 
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33
