### ISSUE TITLE
Mediacom tablets are not parsed as tablets

### ISSUE THREAD

**Issue by ramonavic** [serbanghita/Mobile-Detect#733]
Hi there, 

The following Mediacom tablets are not parsed as tablets: 

Mozilla/5.0 (Linux; Android 6.0.1; M-MPI10C3G Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Safari/537.36

and 

Mozilla/5.0 (Linux; Android 6.0; M-SP10HXAH Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Safari/537.36

**Comment by microchip8** [comment]
What do you think tablets are? They're mobile devices

**Comment by frankvanrest** [comment]
I think what @ramonavic means is that these devices are not recognised as tablets (isTablet() returns false).

**Comment by ramonavic** [comment]
That's what I mean.  I've changed the issue. Thanks @frankvanrest!

**Comment by serbanghita** [comment]
@frankvanrest @ramonavic thanks for clarifying, I've added this to the next minor release

**Comment by serbanghita** [comment]
Thank you for your comments and contributions, I'm extremely grateful for the UAs you provided!
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33
