### ISSUE TITLE
Is there any online tool to check this script?

### ISSUE THREAD

**Issue by csandreas1** [serbanghita/Mobile-Detect#734]
Hello, not an issue with this script. I just want to ask how i can test that. It is important to see if it works on some devices

**Comment by JayBizzle** [comment]
http://demo.mobiledetect.net/

**Comment by serbanghita** [comment]
@JayBizzle thanks for the assist!

**Comment by gety9** [comment]
@JayBizzle @serbanghita 

Is it possible to add option to input user agent on demo page?

Cause now it shows details only for device you are on, which is not convenient if i want to test specific user agent of device that i do not have but that was recorded in GA or internal tracking system.

Now i have to use chrome extension User-Agent Switcher and imput each user agent i want to test, and than revisit the page. It will be much more convenient to have option to enter user agent directly on demo page. 

On first visit you can populate user agent with current device data, and make field editable so it can be easily changed and tested, similar to what they have here:
http://devicedetector.net/
http://litedetection.apachemobilefilter.org/
