### ISSUE TITLE
istablet is false for tablet Google Pixel C

### ISSUE THREAD

**Issue by niklouf** [serbanghita/Mobile-Detect#736]
**Issue description**
Google Pixel C is not identified as a tablet.

**User-Agent(s)**
Mozilla/5.0 (Linux; Android 8.1.0; Pixel C Build/OPM1.171019.026) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.126 Safari/537.36

**Suggestions**

**Comment by niklouf** [comment]
@jasperf No, I didn't received any answers.
We found a workaround (using our own tools) and we closed the case.

**Comment by jasperf** [comment]
@niklouf I see. So if you don’t mind me asking. What type of solution did you use? A hybrid adaptive / responsive approach using media queries as well ? Or did you create your own device filter using this same package ? If so using what agent filter?

**Comment by niklouf** [comment]
@jasperf We added our own rule using the this agent filter:
Mozilla/5.0 (Linux; Android 8.1.0; Pixel C Build/OPM4.171019.021.Z1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
