### ISSUE TITLE
Chrome 66 detected as Opera

### ISSUE THREAD

**Issue by andrey-helldar** [serbanghita/Mobile-Detect#738]
**User-Agent(s)**
`Mozilla/5.0 (Linux; Android 8.0.0; TA-1021 Build/OPR1.170623.026) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.126 Mobile Safari/537.36`

I using a [jenssegers/agent](https://github.com/jenssegers/agent) package.

**Comment by andrey-helldar** [comment]
Another one user agent string:
```
Mozilla/5.0 (Linux; Android 8.0.0; FS8010 Build/OPR1.170623.027) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
```

![photo_2018-07-10_10-08-45](https://user-images.githubusercontent.com/10347617/42494533-3e84ff00-8429-11e8-9d23-8e7cfbd8216c.jpg)

![2018-07-10 10-09-37 slack - avangard](https://user-images.githubusercontent.com/10347617/42494584-617cc600-8429-11e8-83b4-91512adcec20.png)

Browser: Opera
Version: Unknown

**Comment by serbanghita** [comment]
@andrey-helldar thanks a lot, apparently the regex https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php#L522 is too wide, I'm going to fix this.

**Comment by andrey-helldar** [comment]
Thanks!

**Comment by serbanghita** [comment]
@andrey-helldar should be fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33
