### ISSUE TITLE
Bad IE version

### ISSUE THREAD

**Issue by usb248** [serbanghita/Mobile-Detect#739]
I'm on IE11 (win 10 version 1709 build 16299.431) and the library detect IE7.
See screenshot :

![capture](https://user-images.githubusercontent.com/7659927/40163695-c4bd22ec-59b7-11e8-873f-fe02712730fd.PNG)

**Comment by usb248** [comment]
You can close the issue. My IE sent bad user agent owing to a checkbox in "Tools | Compatibility View settings" and the checkmark next to "Display intranet sites in Compatibility View" .... I hate IE

**Comment by serbanghita** [comment]
@usb248 thank you for the details
