### ISSUE TITLE
using libaray globaly

### ISSUE THREAD

**Issue by ezosher** [serbanghita/Mobile-Detect#742]
hey guys, I couldn't find any answers to my issue so I'm posting it here.
I'v required the library by using the docs code `require_once` and declared the new class via `$detect = new Mobile_Detect;` . i'v added this code to my wordpress site in the `functions.php` file.

**Issue description**

the issue is that when I'm trying to write a costume function in the `function.php` file to execute I keep on getting `Fatal error: Uncaught Error: Call to a member function isMobile() on null in `

I'v tried so many varations I lost my mind hope and sure you guys can give some tips and help
cheers to all :) 

sorry in advance if these is not considered as an issue

**Comment by mgsmus** [comment]
```
if((new Mobile_Detect)->isMobile()) {
    // ...
}
```

**Comment by serbanghita** [comment]
@ezosher it's possible that you are declaring `$detect` too late, because it's `null` instead of pointing to the library. If you declare `$detect` globally that doesn't mean you have access to its value

**Comment by ezosher** [comment]
Hey guys sorry for the late reply, thanks to all for the great help, I have found the issue, it was a `syntax` mistake the library working fine and its amazing thank you all :)

**Comment by serbanghita** [comment]
@ezosher 10x for coming back with a closure, thanks @mgsmus for the assist
