### ISSUE TITLE
Samsung GT-P5100 is detected as mobile

### ISSUE THREAD

**Issue by PaddyHu** [serbanghita/Mobile-Detect#743]
Samsung GT-P5100 is detected as mobile, but it's a tablet.

userAgent:
Mozilla/5.0 (Linux; Android 4.2.2; GT-P5100 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Safari/537.36

https://developers.whatismybrowser.com/useragents/explore/operating_platform/samsung-gt-p5100/5

**Comment by serbanghita** [comment]
@PaddyHu thank you, I'm adding this to the next release

**Comment by serbanghita** [comment]
@PaddyHu 👍 done, fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33
