### ISSUE TITLE
Google Pixel 2 is detected as tablet

### ISSUE THREAD

**Issue by halukpp** [serbanghita/Mobile-Detect#750]
-------------delete this message-------------
* By submitting a new issue I acknowledge that I already read the README, CODE EXAMPLES and KNOWN LIMITATIONS. 
* I understand that the current version `2.x` is only meant to detect `mobile` devices.
* Please post your User-Agent string! On a real device/s, the library is expected to work correctly.
-------------delete this message-------------

**Issue description**
"Google Pixel 2" phone is detected as tablet.

**User-Agent(s)**
Mozilla/5.0 (Linux; Android 8.1.0; Pixel 2 Build/OPM2.171026.006.G1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

**Suggestions**
It should be detected as mobile not tablet.

**Comment by wcarle** [comment]
I'm also having this problem with users of our site.

It has been reported by multiple users: https://www.giantbomb.com/forums/bug-reporting-33/mobile-site-not-working-1838754/

**Comment by serbanghita** [comment]
@halukpp Thank you! I'm extremely grateful for you putting the full information about the bug and the UA! 🍻 
@wcarle I'm sorry for the inconvenience, I have fixed the problem in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33 ; Thank you for reaching out!

**Comment by wcarle** [comment]
@serbanghita Thanks so much!!
