### ISSUE TITLE
Sony Xperia Z4 Tablet SGP771 is not detected as tablet

### ISSUE THREAD

**Issue by Nestrot** [serbanghita/Mobile-Detect#753]
**Issue description**
Sony Xperia Z4 Tablet SGP771 is not detected as tablet

**User-Agent(s)**
Mozilla/5.0 (Linux; Android 7.1.1; SGP771 Build/32.4.A.1.54) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Safari/537.36

**Suggestions**
It should be detected as tablet.

**Comment by serbanghita** [comment]
@Nestrot @spmartin823 thank you so much for your contributions!
Fixed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.33
