### ISSUE TITLE
VOYO Q101 tablet detected as phone

### ISSUE THREAD

**Issue by mikhailter** [serbanghita/Mobile-Detect#754]
Device: VOYO Q101 4G

User agent: Mozilla/5.0 (Linux; Android 7.0; 4G-Universal version Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.81 Safari/537.36

This is a tablet, but detected as phone.

**Comment by serbanghita** [comment]
@mikhailter the UA is too generic, do you have more VOYO User-Agents?
I was looking also at http://en.myvoyo.com/chanpin/pingban/ to try to make a connection between the tablet codes and some User-Agents

**Comment by serbanghita** [comment]
The problem is that we can only rely on `4G-Universal` string to identify this as a tablet which is way too generic. If you have User-Agent variants for Opera or other browsers please put them here and I will research.
