### ISSUE TITLE
VoninoTablet - Malware link

### ISSUE THREAD

**Issue by dazza041** [serbanghita/Mobile-Detect#758]
There appears to be a Malware link embedded within the Mobile Detect class. Wordfence does not like this and neither does Chrome. Therefore it should probably be removed.

Found on line 380: Vonino Tablets - http://www.vonino.eu/tablets

**Comment by serbanghita** [comment]
@dazza041 thanks, I will remove it, I'm guessing their site was hacked. Did Wordfence reported this? It seems harmless in the context of a plain comment.

**Comment by findSaif** [comment]
@serbanghita Yes Wordfence reported this issue. It seems Google is also reporting it as "This site may harm your computer."
Better to just remove the reference in the code.

**Comment by Shaatarn** [comment]
@serbanghita thanks for removing this. It seems that Akamai also has a problem with this link as was blocking our sites access to the MailChimp API. Once I removed these lines of code (380, 381), our access was restored. To me, this is very strange, but this is what happened.
