### ISSUE TITLE
is table is not right 

### ISSUE THREAD

**Issue by ghost** [serbanghita/Mobile-Detect#759]
```
include __DIR__.'/libraries/Yf/Utils/Device.php';


echo 'is mobile:'.Yf_Utils_Device::isMobile()."<br>";
echo 'is isTablet:'.Yf_Utils_Device::isMobile();
```

when i use phone visit ,its show

![image](https://user-images.githubusercontent.com/39790804/45027245-71b1b780-b073-11e8-8623-4ab0b3316c15.png)

this is not right.

**Comment by u-mulder** [comment]
What __phone__ do you use?

**Comment by mustify** [comment]
its a big screen like tv.
but its system is andriod

**Comment by mimmi20** [comment]
@mustify Please add the useragent.
