### ISSUE TITLE
Possible typo: "Window Mobile" in operatingSystems array

### ISSUE THREAD

**Issue by luisamat** [serbanghita/Mobile-Detect#766]
https://github.com/serbanghita/Mobile-Detect/blob/9713866c051565de918b19c4ad03535af1e00e87/Mobile_Detect.php#L487

It seems as if the `WindowsMobileOS` entry in the `operatingSystems` array should contain `Windows Mobile` (with an 's') rather than the current `Window Mobile` (without an 's').

We did some basic searches and haven't found a `Window Mobile` UA string, but have found a few UA's containing `Windows Mobile`.

Example: `Opera/9.80 (Windows Mobile; Opera Mini/5.1.21594/37.7011; U; fr) Presto/2.12.423 Version/12.16`

We have had to account for this typo in our code by separately identifying `Windows Mobile` UA's.

**Comment by serbanghita** [comment]
@luisamat thanks for catching this, I updated `devel` and the next version will include the fix
