### ISSUE TITLE
ssl cert broken for https://demo.mobiledetect.net/ since 2015

### ISSUE THREAD

**Issue by wowcut** [serbanghita/Mobile-Detect#769]
https://demo.mobiledetect.net/ returns a broken ssl cert message with a cert expired **since 2015** - this made me think that the project is dead - if you are still actively working on this project it might be a good idea to **remove this dead project indicator** and get a LE cert for the site.

**Comment by serbanghita** [comment]
@wowcut thank you for reminding me of this problem. I will get an IP (for older browsers who don't support SNI) and a SSL cert back up again.

**Comment by serbanghita** [comment]
I used Let's Encrypt and also fixed the feedback submission to accept both http and https. Thank you!
