### ISSUE TITLE
In Chrome developer mode 'Mobile-Detect' is not detecting my mobile

### ISSUE THREAD

**Issue by srinivsncse** [serbanghita/Mobile-Detect#773]
I am using chrome Developer tools to test my application using 'Mobile-Detect'. I have mobile devices configuration in my chrome developer mode like below
iPhone X    - 375 X 812
Galaxy S7   - 414 X 732
HuaweiP10 - 360 X 640

Using this setup the 'Mobile-Detect' library is not detecting my device as mobile device.

In another case, I am testing for large desktop devices like the below configuration
1600 X 900 and 1920 X 1080
in this case 'Mobile-Detect' library detecting it as mobile (as 'Nexus' device).

Can anyone suggest how to test 'Mobile-Detect' library using chrome developer tool

**Comment by ildarkhasanshin** [comment]
actually also in feb '19 for chrome 72.0.3626.81
