### ISSUE TITLE
shortcode

### ISSUE THREAD

**Issue by AngeloLazzari** [serbanghita/Mobile-Detect#781]
Hi, i got into your plugin looking for a mobile detector plugin for wordpress, but i see it's giving "only" the php features to work with, is there a plan to add some shortcodes to permit "not developer" people to use it? i mean, like plugin like this does: https://es.wordpress.org/plugins/wp-mobile-detect/

thank you very much and congrats!

**Comment by derUli** [comment]
This is only a PHP library which provides functions to detect mobile devices for developers.
The Wordpress plugin you mentioned is based on this library.
