### ISSUE TITLE
Warning:  strpos() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by gohelkiran30** [serbanghita/Mobile-Detect#782]
**Issue description**
Getting this warning while checking for a mobile device with isMobile()

Warning:  strpos() expects parameter 1 to be string, array given in /var/www/html/php/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php on line 1054

**User-Agent(s)**

**Suggestions**

**Comment by derUli** [comment]
Could you please provide us the part of your source code where you use MobileDetect?

**Comment by gohelkiran30** [comment]
its in slim depedencies.php file

`
$container['mobileDetector'] = function ($c) {
    return new MobileDetect($c->get('request')->getHeaders(), $c->get('request')->getHeaderLine('User_Agent'));
};
`

**Comment by derUli** [comment]
It seems like you are supplying an array instead of a string as Useragent to Mobile_Detect.
If you
do in that function block
```php
 var_dump($c->get('request')->getHeaderLine('User_Agent'));
```
what output do you get?

**Comment by gohelkiran30** [comment]
I did that, it's string value for user agent. here is the output

string(76) "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"

**Comment by derUli** [comment]
Whats contained in
```php
$c->get('request')->getHeaders()
```
?

Output it with var_dump() please.

**Comment by gohelkiran30** [comment]
Here is the output of  `$c->get('request')->getHeaders()`

```
array(15) {
  ["HTTP_CACHE_CONTROL"]=>
  array(1) {
    [0]=>
    string(8) "no-cache"
  }
  ["HTTP_PRAGMA"]=>
  array(1) {
    [0]=>
    string(8) "no-cache"
  }
  ["HTTP_UPGRADE_INSECURE_REQUESTS"]=>
  array(1) {
    [0]=>
    string(1) "1"
  }
  ["HTTP_COOKIE"]=>
  array(1) {
    [0]=>
    string(891) "lang=en; PHPSESSID=pc7o5cj5v3otgp0kgjisfvdgqh; userLoggedIn=1"
  }
  ["HTTP_CONNECTION"]=>
  array(1) {
    [0]=>
    string(10) "keep-alive"
  }
  ["HTTP_AUTHORIZATION"]=>
  array(1) {
    [0]=>
    string(26) "Basic "
  }
  ["HTTP_ACCEPT_ENCODING"]=>
  array(1) {
    [0]=>
    string(13) "gzip, deflate"
  }
  ["HTTP_ACCEPT_LANGUAGE"]=>
  array(1) {
    [0]=>
    string(14) "en-US,en;q=0.5"
  }
  ["HTTP_ACCEPT"]=>
  array(1) {
    [0]=>
    string(63) "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  }
  ["HTTP_USER_AGENT"]=>
  array(1) {
    [0]=>
    string(76) "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
  }
  ["HTTP_HOST"]=>
  array(1) {
    [0]=>
    string(9) "localhost"
  }
  ["CONTENT_LENGTH"]=>
  array(1) {
    [0]=>
    string(0) ""
  }
  ["CONTENT_TYPE"]=>
  array(1) {
    [0]=>
    string(0) ""
  }
}
```

**Comment by derUli** [comment]
There we have the issue:
getHeaders() returns an array which contains an array which contains a string, while MobileDetect expects just an array with strings.
Replace $c->get('request')->getHeaders() with $_SERVER should fix the problem.
