### ISSUE TITLE
Unable to update mobiledetect using Composer

### ISSUE THREAD

**Issue by Shylajhaa** [serbanghita/Mobile-Detect#786]
I'm trying to update `mobiledetect` from `2.8.24` to `2.8.33`.
My `composer.json` is as follows
```
"require": {
    "mobiledetect/mobiledetectlib": "2.8.33",
},
"prefer-stable": true
```

When I run `composer update`, I get this error.
`The requested package mobiledetect/mobiledetectlib ^2.8.25 exists as mobiledetect/mobiledetectlib[2.8.24] but these are rejected by your constraint`

P.S. I tried updating after clearing cache too.

**Comment by derUli** [comment]
Just replace "2.8.33" with "*" and run composer update again.

**Comment by Shylajhaa** [comment]
@derUli In this case it doesn't update anything

**Comment by derUli** [comment]
What version of the package is listed in your composer.json.lock as installed version?
Did you try to remove the "vendor" folder and to reinstall all composer packages in your project?
