### ISSUE TITLE
PixelSlate detected as a comptuer

### ISSUE THREAD

**Issue by texasade** [serbanghita/Mobile-Detect#788]
-------------delete this message-------------
* By submitting a new issue I acknowledge that I already read the README, CODE EXAMPLES and KNOWN LIMITATIONS. 
* I understand that the current version `2.x` is only meant to detect `mobile` devices.
* Please post your User-Agent string! On a real device/s, the library is expected to work correctly.
-------------delete this message-------------

PixelSlate (Tablet) running ChromeOS detected as a computer.
Device: https://store.google.com/us/product/pixel_slate?hl=en-US 

Mozilla/5.0 (X11; CrOS x86_64 11316.148.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.117 Safari/537.36

Should detect as a tablet

**Comment by serbanghita** [comment]
@texasade thanks for reporting this, it looks like this will go into KNOWN_LIMITATIONS section because there is no clear indicator in the User-Agent that the device might be a tablet.
