### ISSUE TITLE
Firefox Browser 23, Windows 7

### ISSUE THREAD

**Issue by solariz** [serbanghita/Mobile-Detect#79]
**OS** Windows 7
**BROWSER** Firefox 7 Version 23
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20130421 Firefox/23.0`

**Comment by serbanghita** [comment]
https://github.com/serbanghita/Mobile-Detect/issues/15#issuecomment-782725480

I experimented with device details detection, see https://github.com/serbanghita/Mobile-Detect/tree/devel-3-workinprogress/lib, and it's very hard to maintain. I'll keep the a tight focus to Mobile Detect, and that is to detect the mobile environment and focus on the separation of mobiles vs tablets.
