### ISSUE TITLE
Caching Method IsMobile and Other Method If Possible

### ISSUE THREAD

**Issue by vevev** [serbanghita/Mobile-Detect#792]
I had a performance problem when using this library on a large website. If other people don't notice and use isMobile () wherever possible, instead of just checking it once it will run every time.
So what do you think if we will cache the results of the first run?
```
public function isMobile($userAgent = null, $httpHeaders = null)
{   
    static $isMobile;

    if(!is_null($isMobile)){
        return $isMobile;
    }

    if ($httpHeaders) {
        $this->setHttpHeaders($httpHeaders);
    }
    if ($userAgent) {
        $this->setUserAgent($userAgent);
    }
    // Check specifically for cloudfront headers if the useragent === 'Amazon CloudFront'
    if ($this->getUserAgent() === 'Amazon CloudFront') {
        $cfHeaders = $this->getCfHeaders();
        if(array_key_exists('HTTP_CLOUDFRONT_IS_MOBILE_VIEWER', $cfHeaders) && $cfHeaders['HTTP_CLOUDFRONT_IS_MOBILE_VIEWER'] === 'true') {
            return $isMobile = true;
        }
    }
    $this->setDetectionType(self::DETECTION_TYPE_MOBILE);
    if ($this->checkHttpHeadersForMobile()) {
        return $isMobile = true;
    } else {
        return $isMobile = $this->matchDetectionRulesAgainstUA();
    }
}
```

**Comment by uniring** [comment]
Same problem here, we're calling isMobile and isDesktop lots of times in a page render and it spends so much time parsing the regexes.

+1 for the static proposed by @vevev.

(Maybe using a static can cause problems for those using some kind of PHP process manager like php-pm but it's the easiest solution for the rest of unprivileged humans)

**Comment by serbanghita** [comment]
@vevev @uniring  My proposal is to put the result in `$_SESSION`
```php
require_once '../Mobile_Detect.php';
$detect = new Mobile_Detect;
$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'computer');
$_SESSION['deviceType'] = $deviceType
```

and check for the existence of `$_SESSION['deviceType']` key or something similar.

Normally this library should have a pluggable caching system. None was considered for `2.x` release.
