### ISSUE TITLE
Samsung tablets detected as phones

### ISSUE THREAD

**Issue by ClassicalMark** [serbanghita/Mobile-Detect#794]
These Samsung tablets are identified as phones

Samsung GalaxyTab S4 10.5"

Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-T830 Build/PPR1.180610.011) AppleWebKit 537.36 (KHTML, like Gecko) SamsungBrowser/8.0 Chrome/63.0.4349.111 Safari/537.36
-----------------------

Samsung GalaxyTab S4

Mozilla/5.0 (Linux; Android 8.1.0; SAMSUNG SM-T837V Build/M1AJQ) AppleWebKit 537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Safari/537.36
-----------------------

Samsung GalaxyTab S5e 10.5"

Mozilla/5.0 (Linux; Android 9; SM-T720) AppleWebKit 537.36 (KHTML, like Gecko) SamsungBrowser/8.0 Chrome/74.0.3729.157 Safari/537.36 
-----------------------

Samsung GalaxyTab A(2019) 10.1"

Mozilla/5.0 (Linux; Android 9; SM-T510) AppleWebKit 537.36 (KHTML, like Gecko) SamsungBrowser/8.0 Chrome/74.0.3729.157 Safari/537.36 
-----------------------

Samsung GalaxyTab A 8"

Mozilla/5.0 (Linux; Android 8.1.0; SM-T387V) AppleWebKit 537.36 (KHTML, like Gecko) SamsungBrowser/8.0 Chrome/74.0.3729.157 Safari/537.36 
-----------------------

**Comment by RyanBlundell** [comment]
I have the same problem

My Samsung Tablet is being detected as a phone via Chrome app

Your UA is Mozilla/5.0 (Linux; Android 7.1.1; SM-P555 Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Safari/537.36
