### ISSUE TITLE
Application Detect

### ISSUE THREAD

**Issue by ZifengX** [serbanghita/Mobile-Detect#797]
**Issue description**
is there any way to detect open in different app? Like Wechat, Alipay, Weibo, Whatsapp

**User-Agent(s)**
MicroMessenger, Alipayclient

**Suggestions**

**Comment by serbanghita** [comment]
@ZifengX there would be if the opened browser is the in-app browser. This library never intended to have those covered. If you have a list of user-agents please send them over.
