### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Jany-M** [serbanghita/Mobile-Detect#798]
@serbanghita are you still maintaining this or have you abandoned it?

**Comment by webenot** [comment]
Hello. This is not my repository. I don't know does the author  maintains
it, unfortunatly.

пн, 8 июл. 2019 г. в 17:38, Jany Martelli <notifications@github.com>:

**Comment by serbanghita** [comment]
@Jany-M yes, I was away from work due to personal reasons. I'll get back at it this week. Let me know if you have anything urgent to commit and fix.
