### ISSUE TITLE
Handheld method

### ISSUE THREAD

**Issue by playinteractive** [serbanghita/Mobile-Detect#799]
Hi,

Have you considered a method like `$MobileDetect->isHandheld()` ?

Handheld is an alternate serving media type for old phones. It's part of SEO mobile as indicated here: 

https://developers.google.com/search/mobile-sites/mobile-seo/other-devices

Greetings!

**Comment by serbanghita** [comment]
@playinteractive I believe the `feature phones` could be classified separately but I think it's more value, for a website, to employ a graceful degradation technique than sniff for feature phones.

Still, I have no idea where to start this ... maybe first determine what exactly is a `feature phone` or device, I guess one that is not "smart". I remember owning Nokia devices that had Opera Mini. It looks like a huge task and there is a possibility of false positives with the newest devices signatures.
