### ISSUE TITLE
Unity iOS user agent not detected as iOS

### ISSUE THREAD

**Issue by jsaade** [serbanghita/Mobile-Detect#800]
**Issue description**
I am running my application through Unity. Which I assume adds some items to user_agent.
When I call  my backend API, I am checking and logging the user agent.
In case of Android (user agent below) it is detected as isMobile and isAndroid
In the case of iiPhoneOS it is neither detected with isMobile nor with is iOS.

**User-Agent(s)**
iOS: {appname} CFNetwork/978.0.7 Darwin/18.6.0
Android: Dalvik/2.1.0 (Linux; U; Android 5.0.2; SM-T535 Build/LRX22G)

**Comment by serbanghita** [comment]
@jsaade First, thanks for letting me know about this case-study!

It looks to me that we could detect that this is an in-app web browser by using regexes like:

* inApp iOS = `CFNetwork/[0-9.]+ Darwin/[0-9.]+`
* inApp Android = Dalvik/[0-9.]+.*Android`

I don't see enough information to check if this is from Unity, maybe a look at full HTTP headers will reveal something different. Are you aware of any of that?
