### ISSUE TITLE
prevent detection at desktop browser

### ISSUE THREAD

**Issue by pixprod** [serbanghita/Mobile-Detect#803]
Hi guys,
is there a valid way to prevent isMobile() / isTablet() on all desktop computers even within chrome device toolbar? I couldn't get it done right :(

I'd like to code a small "paywall" and exclude all computers / local browsers etc. and allow only for all mobiles and tablets. But if i use for example chrome "iPad simulation", Mobile-Detect sets isMobile/isTablet to true - that's correct i know - but for my use case i'd like to detect isComputer()

Any ideas??? Thanks!! Best Stefan

**Comment by chonocom** [comment]
Couldn't you just do something like: `<?php if (is_mobile()||is_tablet()): else: // Desktop?>` or add exclamation to the condition if you dont need an "else" etc.

**Comment by pixprod** [comment]
Hi chonocom - thanks for your quick response!

Sure! Your approach would work - but i'd like to prevent that a (technical experienced) user can bypass my "Mobile & Tablet stuff here" with using the developer / device toolbar at a desktop-system. That's what i want to prevent - **no real(!) mobile/tablet => no access!**

**Comment by chonocom** [comment]
Do mean something in the line of preventing users from emulating agents/devices and circumvent your desired technical design?

**Comment by pixprod** [comment]
@chonocom : exactly :)!! I think this is not possible out-of-the-box isnt'it?? Does anyone has a good idea how to do these??

**Comment by chonocom** [comment]
It might be difficult/impossible to truly prevent user-agent spoofing since it's possible to change/manipulate the user-agent string the browser sends to the server etc.

**Comment by pixprod** [comment]
@chonocom: thanks for your input :)!! I've tried some more approaches inside MobileDetect, but in the end there was always loophole to bypass it.

I've done the paywall into the app - thanks for your help!
