### ISSUE TITLE
Fetching Device Specs when connected to PC/Web App?

### ISSUE THREAD

**Issue by Sami0802** [serbanghita/Mobile-Detect#808]
Hi,
Is there any possible way to fetch mobile or any device specs when it is connected with PC for some Web App operations?

I have seen some API which shows results but we have to put device model manually. I want when phone is connected that Web App should fetch device specs automatically.

**Comment by serbanghita** [comment]
@Sami0802 none that I'm aware of. Closing this as unrelated to the library.
