### ISSUE TITLE
iOS 13 is recognized as a computer

### ISSUE THREAD

**Issue by icoumans** [serbanghita/Mobile-Detect#809]
We are testing a few tablets with iOS 13 (public beta). I currently do not have an iPhone that I can test iOS 13 on, but I should be able to provide you with a result and UA for that next week.

On the demo site it is not recognized as iOS, Mobile, Tablet or Safari.

**UA**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

**Comment by serbanghita** [comment]
@icoumans it's because the user-agent really doesn't provide any info so we can identify it as mobile. See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md

Does the new tablet has a `desktop` mode or is that the default for Safari?

**Comment by thbl** [comment]
@serbanghita 
cant this trick be implanted ?
https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up
