### ISSUE TITLE
iPadOS is no longer distinguishable from macOS Safari

### ISSUE THREAD

**Issue by djsweet** [serbanghita/Mobile-Detect#814]
**Issue description**
iPadOS 13.1.3 changed the user agent to identify itself as Desktop Safari in Progressive Web Apps pinned to the home screen. Prior versions of iPadOS identified the user agent as Desktop Safari in Safari proper, but "CPU OS 13" is no longer used in any circumstance.

**User-Agent(s)**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

**Comment by serbanghita** [comment]
From the User-Agent we cannot determine if the device is a mobile.
See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md

> Ipad 2019 is being recognized as a desktop because of Safari's default Request Desktop Website setting. See details and possible workaround #820
