### ISSUE TITLE
Google Pixel should have own category

### ISSUE THREAD

**Issue by hinaloe** [serbanghita/Mobile-Detect#815]
Google Pixel phone should use `Pixel` or `Google` not `HTC`.

Now, the following devices exist:

- Pixel / XL
- Pixel 2 / XL
- Pixel 3 / XL
- Pixel 3a / XL
- Pixel 4 / XL

Pixel, Pixel XL, Pixel 2 is manufactured by HTC, but other is by LG or foxconn ( https://en.wikipedia.org/wiki/Comparison_of_Google_Pixel_smartphones ) and they are really Google device.

**Comment by serbanghita** [comment]
@hinaloe agree, can you specify your business case study? Why would you need detection specifically for Pixel phones?

**Comment by serbanghita** [comment]
@hinaloe Added `isPixel` in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.36
Let me know if this helps (if you're still using the lib).
