### ISSUE TITLE
iPad does not detected as tablet

### ISSUE THREAD

**Issue by gergogy** [serbanghita/Mobile-Detect#817]
Issue: My iPad does not detected as a tablet
![image](https://user-images.githubusercontent.com/21192274/68287919-d1df2780-0083-11ea-84cf-4bc2c39ea6d6.png)

**User-Agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

I changed my safari User-Agent to: Mozilla/5.0 (iPad; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1 (via Develop -> User Agent -> Safari - iOS 12.1.3 - iPad) and my browser was detected as an iPad, so it is something with iOS 13?

**Comment by stefetom** [comment]
Hello.

I have the same problem.
**For my tablet iPad 2019, isiPad() and istablet() return false.**

User-Agent is :
`Mozilla/5.0 (Macintosh; Intel Mac OS X10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15`
with Safari and
`Mozilla/5.0 (Macintosh; Intel Mac OS X10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)`
with Firefox.

Thomas

PS. I'm french, sorry if my english is not good.

**Comment by derUli** [comment]
iPad's Safari identifies as macOS since iPad OS 13.
Unfortunately it seems like there is no way to distinguish between iPad on Safari and Safari on Mac.

**Comment by FlorentMasson** [comment]
iPads on IOS 13 now request websites in desktop mode by default.
This solution works: https://stackoverflow.com/a/57924983/4228964

**Comment by RazorEdgexD** [comment]
Opened Settings -> Safari -> Request Desktop Website -> All websites. 

That option is enabled by default. I disabled it and the proper User Agent is now displayed.

https://forums.developer.apple.com/thread/119186

**Comment by razor1907** [comment]
I use images on a mobile template for mobile phones only.
The script does its job well and excludes desktop and tablets from seeing these images however ipad's are considered as mobile still. Not sure if i'm doing something wrong.

```
function detectMobile($type = 'mobile') {
    global $basepath;
	$user_agent = $_SERVER['HTTP_USER_AGENT'];
    if($_GET['mobileDevice']) {
        return true;
    }
    switch(true) {
        case (stripos($user_agent,'opera mini'));
             $isMobile = true;
         break;
        case (stripos($user_agent,'blackberry'));
            $isMobile = true;
        break;
        case (preg_match('/(mini 9.5|vx1000|lge |m800|e860|u940|ux840|compal|wireless| mobi|ahong|lg380|lgku|lgu900|lg210|lg47|lg920|lg840|lg370|sam-r|mg50|s55|g83|t66|vx400|mk99|d615|d763|el370|sl900|mp500|samu3|samu4|vx10|xda_|samu5|samu6|samu7|samu9|a615|b832|m881|s920|n210|s700|c-810|_h797|mob-x|sk16d|848b|mowser|s580|r800|471x|v120|rim8|c500foma:|160x|x160|480x|x640|t503|w839|i250|sprint|w398samr810|m5252|c7100|mt126|x225|s5330|s820|htil-g1|fly v71|s302|-x113|novarra|k610i|-three|8325rc|8352rc|sanyo|vx54|c888|nx250|n120|mtk |c5588|s710|t880|c5005|i;458x|p404i|s210|c5100|teleca|s940|c500|s590|foma|samsu|vx8|vx9|a1000|_mms|myx|a700|gu1100|bc831|e300|ems100|me701|me702m-three|sd588|s800|8325rc|ac831|mw200|brew |d88|htc\/|htc_touch|355x|m50|km100|d736|p-9521|telco|sl74|ktouch|m4u\/|me702|8325rc|kddi|phone|lg |sonyericsson|samsung|240x|x320vx10|nokia|sony cmd|motorola|up.browser|up.link|mmp|symbian|smartphone|midp|wap|vodafone|o2|pocket|kindle|mobile|psp|treo|palm os|palm|hiptop|avantgo|fennec|plucker|xiino|blazer|elaine|iris|3g_t|windows ce|opera mobi|windows ce; smartphone;|windows ce; iemobile)/i',$user_agent));
            $isMobile = true;
        break;
    }
    return $isMobile; 
```

**Comment by kamyweb** [comment]
My quick fix on ipad air 2020
$detect->match('Macintosh|Mac.*OS.*X')

**Comment by serbanghita** [comment]
From the User-Agent we cannot determine if the device is a mobile.
See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md

> Ipad 2019 is being recognized as a desktop because of Safari's default Request Desktop Website setting. See details and possible workaround #820

Thank you everyone for assisting and providing solutions.
