### ISSUE TITLE
i want detect ipad as iphone

### ISSUE THREAD

**Issue by ahmetozcan999** [serbanghita/Mobile-Detect#818]
i have a responsible template for wordpress. when i open my website over phone it shows a navigation bar. but when i open over tablets navigation bar not showing. 
i mean that i dont't want detect tablets. or i want detect tablets as phone 
help me pls

**Comment by derUli** [comment]
Is your iPad running iOS or iPad OS?
Unfortunately iPad OS Safari identifies as macOS since Version 13 and there is no way to distinguish iPad Safari from  Safari on Mac.

**Comment by RazorEdgexD** [comment]
Opened Settings -> Safari -> Request Desktop Website -> All websites. 

That option is enabled by default. I disabled it and the proper User Agent is now displayed.

https://forums.developer.apple.com/thread/119186

**Comment by serbanghita** [comment]
@ahmetozcan999  From the User-Agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15` we cannot determine if the device is a mobile.
See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md

> Ipad 2019 is being recognized as a desktop because of Safari's default Request Desktop Website setting. See details and possible workaround #820

@RazorEdgexD thank you for assisting 🍻
