### ISSUE TITLE
The same UA in Mobile and Computer - Apple

### ISSUE THREAD

**Issue by jepiquer** [serbanghita/Mobile-Detect#819]
Hi,

In iPad and Mac, I have the same UA, both Safari browser:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15

Do you have the same problem?

Thank you.

**Comment by derUli** [comment]
Since the switch from iOS to iPad OS the safari identifies itself as Mac OS by default.
Unfortunately It's not possible to  distinguish iPad OS Safari from Safari on Mac.
Maybe it' possible in JavaScript but not with PHP

**Comment by RazorEdgexD** [comment]
Opened Settings -> Safari -> Request Desktop Website -> All websites. 

That option is enabled by default. I disabled it and the proper User Agent is now displayed.

https://forums.developer.apple.com/thread/119186

**Comment by serbanghita** [comment]
From the User-Agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15` we cannot determine if the device is a mobile.
See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md

> Ipad 2019 is being recognized as a desktop because of Safari's default Request Desktop Website setting. See details and possible workaround #820
