### ISSUE TITLE
iPad 2019 is not recognized as tablet!

### ISSUE THREAD

**Issue by AdiAlex** [serbanghita/Mobile-Detect#820]
Hello
My new iPad (2019 - 7th generation, iPadOS 13.2.2) is not recognized as tablet. Can you solve this problem?
Thank you very much.
Greetings from Switzerland
Adrian

![IMG_0035](https://user-images.githubusercontent.com/2806621/69007521-f74f1980-093e-11ea-858b-19fcecbbd91a.PNG)

Please specify the User-Agent. Go to https://demo.mobiledetect.net and copy-paste it here.

**Comment by mlaurense** [comment]
I'm facing the same issue, but I'm not sure this is a problem with the Mobile Detect library... The iPad is wrongly identifying itself as a computer, to make sure the servers sends a desktop view to the browser. See also this thread at Apple, started July 2nd... https://forums.developer.apple.com/thread/119186

Apparently there is a switch in the settings to control this, but Apple in all its wisdom has decided that faking a computer on a tablet screen is a good idea, completely overlooking the fact that as a webdeveloper you might want to alter the HTML to provide a better user interface for touch screens.

FWIW: Chrome on iPad still identifies itself as iPad...

**Comment by RazorEdgexD** [comment]
Opened Settings -> Safari -> Request Desktop Website -> All websites. 

That option is enabled by default. I disabled it and the proper User Agent is now displayed.

https://forums.developer.apple.com/thread/119186

**Comment by dorhivert** [comment]
You can switch of one iPad (assuming you are the owner) by this settings. 
But as far as I know currently there is no option to distinguish iPads that use the default settings with Safari (and that is - over 90% of iPads) from Macs, as they have the exact same user agent.

**Comment by Manviel** [comment]
Same issue

**Comment by kamyweb** [comment]
My quick fix on ipad air 2020
`$detect->match('Macintosh|Mac.*OS.*X')`

**Comment by Tommasov** [comment]
> My quick fix on ipad air 2020
> `$detect->match('Macintosh|Mac.*OS.*X')`

Thank you!

**Comment by serbanghita** [comment]
Just like @mlaurense and @RazorEdgexD pointed out, there is nothing the library can do without breaking existing tests.

I would go with @kamyweb 's response. I will put his response in the https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md

**Comment by aqres** [comment]
> My quick fix on ipad air 2020
> `$detect->match('Macintosh|Mac.*OS.*X')`

How does this work as a fix to identify iPad ???

**Comment by vdite** [comment]
> 

this would match all Macs with macOS

**Comment by aqres** [comment]
Yes indeed - _and_ iPads (as I confirmed by testing it just now).  I was puzzled because I thought the rule was being put forward in some way as a method to recognise iPads.
