### ISSUE TITLE
Using Android's stock Browser (Internet) the device is not detected as mobile

### ISSUE THREAD

**Issue by mayeaux** [serbanghita/Mobile-Detect#821]
**Issue description**
Using Android's stock Browser (Internet) the device is not detected as mobile

**User-Agent(s)**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Suggestions**
I haven't updated this phone for a long time that may be causing the Regex to fail, but I figured I should include this anyway

**Comment by serbanghita** [comment]
@mayeaux from `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36` we cannot determine if this is a mobile device. See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md
