### ISSUE TITLE
Coming from jenssegers/agent - Google to phase out user-agent strings in Chrome

### ISSUE THREAD

**Issue by kevincobain2000** [serbanghita/Mobile-Detect#824]
**Issue description**

Also addressed to https://github.com/jenssegers/agent/issues/165
Paste Raw

Hi,
With regards to the recent announcement by Google. 
https://www.zdnet.com/article/google-to-phase-out-user-agent-strings-in-chrome/

>**Google to phase out user-agent strings in Chrome Chrome will move to a new technology called Client Hints, part of the newer Privacy Sandbox project.**

**Current**

```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
            AppleWebKit/537.36 (KHTML, like Gecko)
            Chrome/79.0.3945.117 Safari/537.36
```

**NEW**

```
Sec-CH-UA: "Chrome 79.0.3945.117"
Sec-CH-Platform: "Windows 10"
Sec-CH-Arch: "AMD64"
Sec-CH-Mobile: 0
```

I wonder if it will be added to the Roadmap of this project for future updates.

**User-Agent(s)**

**Suggestions**

**Comment by serbanghita** [comment]
@kevincobain2000 thank you for the details! I am looking into this! 👍

**Comment by maietta** [comment]
Thank you @kevincobain2000 for mentioning what I was about to mention here. I am essentially ready to devote a bit of time into make the necessary changes to get this working. I don't have much time today, but I can be available this weekend to fork, change and do a pull request. If someone else is already working on it, I won't waste my time, but feel free to use me to get this fixed.

**Comment by serbanghita** [comment]
Did this went through after all?
