### ISSUE TITLE
Mobile detect on My Website not detecting tecno,infinix,gionee,itel phones

### ISSUE THREAD

**Issue by Seapson** [serbanghita/Mobile-Detect#825]
-------------delete this message-------------
* By submitting a new issue I acknowledge that I already read the README, CODE EXAMPLES and KNOWN LIMITATIONS. 
* I understand that the current version `2.x` is only meant to detect `mobile` devices.
* Please post your User-Agent string! On a real device/s, the library is expected to work correctly.
-------------delete this message-------------

Please help me,mobile detect does not detect those phones on my website, so when visitors visit my website on mobile,it looks unarranged,and some icons stack on others

**Issue description**

**User-Agent(s)**

**Suggestions**

**Comment by serbanghita** [comment]
@Seapson I need User-Agent strings in order to create a patch.
