### ISSUE TITLE
3rd generation iPad Pro. and it returns this is a computer

### ISSUE THREAD

**Issue by sameernaqvi1** [serbanghita/Mobile-Detect#827]
3rd generation iPad Pro. and it returns this is a computer... **WRONG INFORMATION**

![Screenshot 2020-03-16](https://user-images.githubusercontent.com/25508620/76743133-0f5a6c80-676a-11ea-9016-cfe3aa7efb80.png)

Regards

**Comment by hgoebl** [comment]
@sameernaqvi1 why don't you read the other issues about iPad and instead open a new one and shouting around?
Blame Apple.

**Comment by kamyweb** [comment]
my quick fix:
`$detect->match('Macintosh|Mac.*OS.*X')`

**Comment by serbanghita** [comment]
I don't see any way we can deal with this at the moment.

**Comment by jasperf** [comment]
> `$detect->match('Macintosh|Mac.*OS.*X')`

Thanks for this tip. Looking into solutions for detecting iPads properly
