### ISSUE TITLE
Does not detect Chrome and Safari on macOS

### ISSUE THREAD

**Issue by outfoxer** [serbanghita/Mobile-Detect#831]
Does not detect Chrome and Safari on macOS

**Issue description**

**User-Agent(s)**
Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

**Suggestions**

**Comment by ismaail** [comment]
Same here:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

**Comment by DannyJoris** [comment]
Based on https://stackoverflow.com/a/15272187/477949 , I was able to do a check for Safari like this:
```
$detect = new Mobile_Detect();
$is_safari = $detect->match('Safari') && !$detect->match('Chrome');
```

**Comment by serbanghita** [comment]
Being away for a while and now reading your question, I don't understand what is the context:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

Is this Chrome or Safari on Mac?
What is the suggested solution?
