### ISSUE TITLE
Linkedin app not detected

### ISSUE THREAD

**Issue by cappadaan** [serbanghita/Mobile-Detect#832]
This following use agent is not recognized

DesktopMozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [LinkedInApp] 

I guess this is someone using the linkedin app.

**Comment by serbanghita** [comment]
We're currently not supporting in-app browser detection. I'm gathering case studies at the moment.
