### ISSUE TITLE
Huawei AspiegelBot

### ISSUE THREAD

**Issue by JmRy** [serbanghita/Mobile-Detect#835]
Hello, 

**Issue description**
It would be nice to add the detection of the Huawei Search bot. He is very aggressive now.

**User-Agent(s)**
UA: mostly

`Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; AspiegelBot)`

Rarely
`Mozilla/5.0 (compatible;AspiegelBot)
`
His IPs always start with 114.119.16*

**Suggestions**
If possible thank you very much

**Comment by serbanghita** [comment]
Will be available in `2.8.35`
