### ISSUE TITLE
Update device list

### ISSUE THREAD

**Issue by jimmydjabali** [serbanghita/Mobile-Detect#836]
**Issue description**

The device list of `mobile-detect.js` were updated last time in September 2019, and now new phones came out (eg. **Galaxy S20**).

Did you planned to update the device model list ?

**User-Agent(s)**

Mozilla/5.0 (Linux; Android 10; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36

**Suggestions**

Update the device list

**Comment by bzed** [comment]
@serbanghita do you have any plans to work on this project again soon? I could spend some time on it if needed.

**Comment by JuneTwooo** [comment]
Or maybe a updated fork ?

**Comment by serbanghita** [comment]
I'm on it, I'm scanning Samsung websites for new devices. Update will be available in `2.8.35`
