### ISSUE TITLE
Update Facebook Bots User Agents

### ISSUE THREAD

**Issue by ErminMerdanovic** [serbanghita/Mobile-Detect#837]
**Old Bots:**

```
facebookexternalhit/
Facebot
```

**New Bots:**

```
facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
facebookexternalhit/1.1
```

**Source:**
https://developers.facebook.com/docs/sharing/webmasters/crawler/

**Comment by serbanghita** [comment]
@ErminMerdanovic thank you, it appears that we already have the detection in place. I've updated the documentation link.
