### ISSUE TITLE
Unrecognized user agent

### ISSUE THREAD

**Issue by cappadaan** [serbanghita/Mobile-Detect#838]
This user_agent is not recognized:

DesktopMozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko)

**Comment by serbanghita** [comment]
> If the mobile browser is set on Desktop mode, the Mobile Detect script has no way of knowing that the device is mobile.
from https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md
