### ISSUE TITLE
Viewport 

### ISSUE THREAD

**Issue by bjgraham** [serbanghita/Mobile-Detect#839]
User agent confirmed iPad Mozilla device ID correct.
One small problem, the device whilst recognised the browser, failed to consider or detect the appropriate VIEWPORT.
This is relevant, had it been an iPhone all would have appeared to be in order, but, the viewport on an iPad Pro 10.5  could easily have accommodated another two parallel results. I confess this appears to be symptomatic of the inherent misconception of pixel vs viewport and, without writing and cross checking, determining orientation is probably justification in itself for ignoring such problematic details. However, to me, a project is fundamentally flawed if its presentation undermines the gravitas anticipated by its developer(s). I should point out as a machine language system developer we do tend to be a bit picky!

**Comment by serbanghita** [comment]
> The script cannot detect the viewport, pixel density or resolution of the screen since it's running server-side.

This is a known limitation of the script.

https://github.com/serbanghita/Mobile-Detect/blob/master/docs/KNOWN_LIMITATIONS.md
