### ISSUE TITLE
MacOS Big Sur detected as Android 6

### ISSUE THREAD

**Issue by juhasev** [serbanghita/Mobile-Detect#844]
**Issue description**
I get Android 6 as opposed to Mac OS Big Sur or similar...

**User-Agent(s)**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

**Suggestions**
Should not revert to Android 6

**Comment by serbanghita** [comment]
@juhasev I ran tests on the string

```php
$detect = new Mobile_Detect;
$detect->setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36');

var_dump($detect->isiOS());
var_dump($detect->isAndroid());
var_dump($detect->version("Android"));
```

Results:

```
$ php -f examples/test.php
bool(false)
bool(false)
bool(false)

```
