### ISSUE TITLE
Detecting desktop version in IOS?

### ISSUE THREAD

**Issue by BackuPs** [serbanghita/Mobile-Detect#845]
How to detect that the ios desktop version is loaded?

I need to add css only for ios on mobile and desktop version.  But it fails to detect IOS if it runs the desktop version.

please advice

**Comment by BackuPs** [comment]
I understand that there is no way to detect if iphone or ipad are loading the desktop version.  Code that works on ipad an iphone also affects imacs and macbooks

This seems to be something that apple has to resolve as they should provide the correct device information.

Below the code that works without adjusting the mobile_detect.php file as reported in another thread.

`if( $mobiledetect->isiOS() && $mobiledetect->isiPhone() || $mobiledetect->isiOS() && $mobiledetect->isiPad() || $mobiledetect->version(iOS)=='X'  ){ do your stuff}`

**Comment by dinuionut** [comment]
@BackuPs Our fix is only for [Ionic Framework](https://ionicframework.com/)'s App Webview, where "Mobile" is mentioned in the User-Agent. It doesn't work in regular Safari, unfortunately. You can see the details in my commit's description.

**Comment by BackuPs** [comment]
> 
> 
> @BackuPs Our fix is only for [Ionic Framework](https://ionicframework.com/)'s App Webview, where "Mobile" is mentioned in the User-Agent. It doesn't work in regular Safari, unfortunately. You can see the details in my commit's description.

if you change your code to iPad' => 'iPad|iPad.*Mobile|Macintosh',  it also works on ipad. But also on the Imac, and Macbooks.  

This is something Apple had to fix so one can detect ipad and iphone desktop mode in safari, chrome, firefox

Bizar that they mess-up such this way !

**Comment by donRollo** [comment]
Hi on you. I have been using "Mobile_Detect" for long time and have solved the Ipad-problem with this code that seems to work fine

<?php 
	$detect = new Mobile_Detect;
	$deviceType = ($detect->isMobile() ? ($detect->isTablet() ? 'tablet' : 'phone') : 'computer');
	if ($deviceType == 'computer') {
		if (strpos($_SERVER['HTTP_USER_AGENT'], "Macintosh") > 0 && strpos($_SERVER['HTTP_USER_AGENT'], "Version") > 0) {
			echo "iPad";
		} else {
			echo "Computer";
		}
	} elseif ($deviceType == 'phone') {
		echo "Phone";
	} else {
		echo "Tablet";
	}
?>

/Roland

**Comment by dinuionut** [comment]
@donRollo In my previous tests both Mac and iPad Safari HTTP_USER_AGENT contained both "Macintosh" and "Version", so I don't think that your solution works.

Mac Safari
User-Agent: Mozilla/5.0 (**Macintosh**; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version**/13.1.1 Safari/605.1.15

iPad Safari
User-Agent: Mozilla/5.0 (**Macintosh**; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version**/13.1.1 Safari/605.1.15

**Comment by donRollo** [comment]
Ok, but i tested on a new Mac, with 10_15_6, you tested with 10_15_4. So maybe Apple have removed "Version" from 10_15_6?

Mac
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by dinuionut** [comment]
It's not about the version, but about the browser you test with. You test Safari on iPad but Chrome on Mac, right?

Below are my current tests (MacBook Pro 15-inch, 2019, MacOS Big Sur 11.0 Beta):

Safari (Version 14.0)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

Chrome (Version 85.0.4183.102)
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by donRollo** [comment]
Ahhh, so Apple always return "Version" in Safari. Apple do not care about developers :(

**Comment by donRollo** [comment]
Hi again.
I have been thinking about this. I should recommend that you implement "Macintosh" and "Version" to get correct is_tablet() for iPads. It's not 100% correct because a Mac on Safari is then a "tablet". But now is Ipad always a "computer" which is not so good if you want to add specific features for Ipads. What do you think about this?

**Comment by serbanghita** [comment]
Thank you @dinuionut for the assist.

I don't see any reasonable way to detect this scenario in Mobile Detect.
