### ISSUE TITLE
Two Samsung tablets id as phones

### ISSUE THREAD

**Issue by ClassicalMark** [serbanghita/Mobile-Detect#846]
**Issue description**
2 Samsung Galaxy tablets are identified as phones.

**User-Agent(s)**

[Galaxy Tab S6 Lite 10.4"]
Mozilla/5.0 (Linux; Android 10; SM-P610) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

[Galaxy Tab A]
Mozilla/5.0 (Linux; Android 10; SM-T290) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Safari/537.36

**Comment by serbanghita** [comment]
Will be available in `2.8.35`
