### ISSUE TITLE
xiaomi 8pro not detected as mobile

### ISSUE THREAD

**Issue by Golden-Puma** [serbanghita/Mobile-Detect#849]
-------------delete this message-------------
* By submitting a new issue I acknowledge that I already read the README, CODE EXAMPLES and KNOWN LIMITATIONS. 
* I understand that the current version `2.x` is only meant to detect `mobile` devices.
* Please post your User-Agent string! On a real device/s, the library is expected to work correctly.
-------------delete this message-------------

**Issue description**

**User-Agent(s)**

**Suggestions**

**Comment by Golden-Puma** [comment]
@version 2.8.34
 This is a computer. Your UA is Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/71.0.3578.141 Safari/534.24 XiaoMi/MiuiBrowser/12.6.6-gn

**Comment by DrLightman** [comment]
so should it be detected as computer or mobile?

**Comment by Golden-Puma** [comment]
as desktop

**Comment by serbanghita** [comment]
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/71.0.3578.141 Safari/534.24 XiaoMi/MiuiBrowser/12.6.6-gn` is detected as a computer as it should.
