### ISSUE TITLE
Samsung Galaxy Tab S7+ detected as Phone instead of Tablet

### ISSUE THREAD

**Issue by ForsakenNGS** [serbanghita/Mobile-Detect#850]
**Issue description**
Samsung Galaxy Tab S7+ detected as Phone instead of Tablet.

**User-Agent(s)**
"Mozilla/5.0 (Linux; Android 11; SM-T970) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"

**Suggestions**
Add "SM-T970" in the regexp under $tabletDevices["SamsungTablet"]

**Comment by serbanghita** [comment]
@ForsakenNGS thank you for the report. Fix available in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.36
