### ISSUE TITLE
Samsung Tab A7 SM-T500 not recognized as tablet

### ISSUE THREAD

**Issue by VARGA-Peter** [serbanghita/Mobile-Detect#853]
Adding "```SM-T500```" to ```$tabletDevices``` fixes this. May be the situation could be re-considered and the fingerprint "SM-T500" could be added in one of the next updates. Thx!

**Comment by serbanghita** [comment]
@VARGA-Peter thank, sure, next minor version

**Comment by VARGA-Peter** [comment]
I appreciate your fast help!

**Comment by serbanghita** [comment]
Available in `2.8.37` release
