### ISSUE TITLE
Feature request: getDevice and getDeviceCategory

### ISSUE THREAD

**Issue by Wuschba** [serbanghita/Mobile-Detect#854]
Great and usefull work! 

Is there already a way to get a string which device was detected? If not, it would be great to get 2 methods:

function getDevice()
-> returns the device which was detected (like "iPhone", "iPad", "Samsung", "SamsungTablet" etc).

And (just for convenience):
function getDeviceCategory()
-> returns "mobile", "tablet" or "desktop" as a string

**Comment by serbanghita** [comment]
I'm looking into this, clearly it's better to have the values programatically available rather than rely on the magic methods
