### ISSUE TITLE
Missing a bunch agents of the past years

### ISSUE THREAD

**Issue by gehaktmolen** [serbanghita/Mobile-Detect#856]
Hi, I noticed the script is missing the following agents. Mainly late Samsung models:

## Samsung Smartphones
```
SM-G991B|SM-G981B|SM-G986B|SM-G988B|SM-G973F|SM-G960F|SM-G975F|SM-G970F|SM-G965F|SM-A515F|SM-A115F|SM-A105FN|SM-N980F|SM-N986B|SM-N970F|SM-N976B|SM-N960F|SM-N950F|SM-N910A|SM-N900
```

samsung s21
SM-G991B

samsung s20
SM-G981B

samsung s20+
SM-G986B

samsung s20 ultra
SM-G988B

samsung s10
SM-G973F

samsung s9
SM-G960F

samsung s10+
SM-G975F

samsung s10e
SM-G970F

samsung s9+
SM-G965F

samsung a51
SM-A515F

samsung a11
SM-A115F

samsung a10
SM-A105FN

samsung note 20
SM-N980F

samsung note 20 ultra
SM-N986B

samsung note 10
SM-N970F

samsung note 10+
SM-N976B

samsung note 9
SM-N960F

samsung note 8
SM-N950F

samsung note 4
SM-N910A

samsung note 3
SM-N900

## Samsung Tablet

samsung tab s7
SM-T875

## Others
OnePlus 8 (can't check by ONEPLUS anymore)
IN2013

Oneplus 7t
HD1903

oneplus 7
GM1903

motorola g7 play
moto g(7) play

Xiaomi
Redmi Note 8

Vivo Y50
vivo 1935

Oppo Reno 3 Pro
CPH2035

**Comment by serbanghita** [comment]
Thank you, this is a perfect addition for this weekend!

**Comment by lasso-media** [comment]
May I add another missing user agent here or should I create a new issue?
Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; 
PetalBot;+https://webmaster.petalsearch.com/site/petalbot)
