### ISSUE TITLE
isTablet in iPad is returning false

### ISSUE THREAD

**Issue by viracoding** [serbanghita/Mobile-Detect#860]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

isTablet in iPad is returning false

**Comment by darapa1** [comment]
@viracoding 
This is normal behavior, because your mentioned UA string ist from Desktop mode.
This is default configuration for Safari using iPadOS.

You can "Request Mobile Website" at the "aA" Menu left of our URL.
This will result in isTablet() = true.

Works as designed from Apple.
