### ISSUE TITLE
Fix the license file so Github can pick it up in the UI

### ISSUE THREAD

**Issue by exussum12** [serbanghita/Mobile-Detect#861]
The licence file has both a licence and a contributing agreement.

Would you be open to splitting them into 2 files ?

**Comment by serbanghita** [comment]
@exussum12 sure! What is your use case for this change?

**Comment by exussum12** [comment]
Github doesn't pick up the licence correctly due to the additional non licence text at the bottom. They pick the correct file, but can't work out the licence

**Comment by serbanghita** [comment]
@exussum12 where did you noticed this? I want to replicate it myself

**Comment by exussum12** [comment]
https://github.com/serbanghita/Mobile-Detect/blob/5.x/LICENSE.txt  

That should show something like

https://github.com/doctrine/dbal/blob/3.1.x/LICENSE


![image](https://user-images.githubusercontent.com/1102850/118483070-7d534880-b70d-11eb-9ffc-9629d8bf2300.png)


vs

![image](https://user-images.githubusercontent.com/1102850/118483100-8b08ce00-b70d-11eb-8825-2be1a701420c.png)


If you remove the bottom section yours will also have the correct licence picked up

**Comment by serbanghita** [comment]
@exussum12 thanks, fixed in https://github.com/serbanghita/Mobile-Detect/commit/10d919b34a0dbd2a72a3c90b09f797edef66988a
![Screenshot 2021-05-26 at 11 52 38](https://user-images.githubusercontent.com/1106849/119631918-04dd3d80-be19-11eb-8c20-a2b15369506b.png)

**Comment by exussum12** [comment]
Amazing thank you!
