### ISSUE TITLE
isTablet and problem with UA

### ISSUE THREAD

**Issue by gaglioffo** [serbanghita/Mobile-Detect#864]
Hi,
this UA fails isTablet function

`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; rv:11.0) like Gecko`

Futher information here
[whatismybrowser.com](https://developers.whatismybrowser.com/useragents/parse/764250internet-explorer-windows-trident)

I found many cases like this
[pastebin.com](https://pastebin.com/BK6CuUkY)
- version mobiledetectlib => 2.8.37
- DB from whatismybrowser => 550 ua
- Test failed: isTablet => 211
- Test failed: isTablet && isMobile => 207

Is WhatsMyBrowser wrong? Many are MSIE and you use "Tablet PC" into string.

Thank's a lot to check it

**Comment by josephmiller2000** [comment]
Yes isTablet function need a tweak, it is not being accurate with detecting only isTablet ipad.

isTablet and isMobile both recognize ipad as mobile nd tablet.
