### ISSUE TITLE
How do I get the mobile name?

### ISSUE THREAD

**Issue by anhao** [serbanghita/Mobile-Detect#868]
**Issue description**
How do I get the mobile name? 

**User-Agent(s)**

**Suggestions**

**Comment by DrLightman** [comment]
You don't need the library, parse the global var `$_SERVER['HTTP_USER_AGENT']`

**Comment by anhao** [comment]
> You don't need the library, parse the global var `$_SERVER['HTTP_USER_AGENT']`

I need monile name, For example, iPhone, iPad , Xiaomi

**Comment by sonegs** [comment]
Something like that could be useful for you

`       $browser=array("IE","OPERA","MOZILLA","NETSCAPE","FIREFOX","SAFARI","CHROME", "MIUIBROWSER");
       
        $info['browser'] = "OTHER";
        foreach($browser as $parent)
        {
            $getBrowser = strpos(strtoupper($_SERVER['HTTP_USER_AGENT']), $parent);
           
            if ($getBrowser)
            {
                $info['browser'] = $getBrowser;
            }
        }`
