### ISSUE TITLE
Lenovo TB-X306X is detected as phone

### ISSUE THREAD

**Issue by unipeh** [serbanghita/Mobile-Detect#871]
$_SERVER['HTTP_USER_AGENT'] has value:
'Mozilla/5.0 (Linux; Android 10; Lenovo TB-X306X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome'

This is detected as a phone by Version 2.8.37. But the device is a quite ordinary tablet.

**Comment by serbanghita** [comment]
Thank you, this was released in the last version!
