### ISSUE TITLE
Xiaomi Pad 5 isn't recognized as a Tablet

### ISSUE THREAD

**Issue by vdite** [serbanghita/Mobile-Detect#872]
**Issue description**
Xiaomi Pad 5 Model 21051182G isn't recognized as a Tablet

**User-Agent(s)**
Mozilla/5.0 (Linux; Android 11; 21051182G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36

**Suggestions**
Add  
'XiaomiTablet'=>'Android.*21051182G',
to
protected static $tabletDevices = array()

**Comment by serbanghita** [comment]
This was already released https://github.com/serbanghita/Mobile-Detect/blob/5.x/Mobile_Detect.php#L454
Thank you for providing the UA for research!
