### ISSUE TITLE
How to get only mobile name?

### ISSUE THREAD

**Issue by PCcloob** [serbanghita/Mobile-Detect#874]
How can i get only mobile name?

Result like : your System is "Android" and Model is "Redmi 9s".

I try this :
```
require_once 'Mobile_Detect.php';
$user_agent=$_SERVER['HTTP_USER_AGENT']; 
$detect = new Mobile_Detect;
if($detect->isMobile()){
your System is "Android" and Model is $detect->devicename.
}
```
but Not work!

I use Mobile-Detect 2.8.37 and PHP7.3.
Thanks.

**Comment by serbanghita** [comment]
@PCcloob Mobile Detect as a library has never had that goal.
