### ISSUE TITLE
Deprecated notice php 8.1

### ISSUE THREAD

**Issue by cappadaan** [serbanghita/Mobile-Detect#876]
php 8.1 gives

preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated on line 1460 in /httpdocs/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php

**Comment by VincentLanglet** [comment]
Hi @serbanghita, there is multiple PR created to fix the deprecation warning. 
Do you have time to take a look and create a new release ? Thanks.

**Comment by serbanghita** [comment]
@VincentLanglet this was addressed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.38
Thank you for the reminder!
