### ISSUE TITLE
Wrong mobile detection on iPad/Safari

### ISSUE THREAD

**Issue by DmitrySamushchenko** [serbanghita/Mobile-Detect#877]
**Issue description**
Hi, i'm developer from Amasty.
The library detects a desktop device type instead of mobile while using Safari on iPad. Meanwhile, everything works as intended in the Chrome browser using the same iPad. As far as I see, there is no information about the device type in the UserAgent. I suppose that the issue occurs on the side of the Safari, but perhaps, there is a possibility to do something about it.

**User-Agent(s)**
Safari/Ipad: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15`
For example Chrome/Ipad: `Mozilla/5.0 (iPad; CPU OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/86.0.4240.93 Mobile/15E148 Safari/604.1`

**Suggestions**
-

**Comment by dedric81** [comment]
Please fix that issue

**Comment by maxtor233** [comment]
same problem, and $detect->isiOS() not detect ipad/safari.

**Comment by AtomicSteve** [comment]
I've found this is because the 'Request Desktop Site' setting for Safari is set to 'On' it's not detected as mobile. Turning it off allows it to be detected. The same story for Chrome, if you request a desktop site it doesn't recognise it then either.

**Comment by microchip8** [comment]
> I've found this is because the 'Request Desktop Site' setting for Safari is set to 'On' it's not detected as mobile. Turning it off allows it to be detected. The same story for Chrome, if you request a desktop site it doesn't recognise it then either.

AFAIK, this is intended behavior. Setting a mobile browser to desktop mode changes the user agent so MobileDetect treats it as a desktop/laptop

**Comment by AtomicSteve** [comment]
> > I've found this is because the 'Request Desktop Site' setting for Safari is set to 'On' it's not detected as mobile. Turning it off allows it to be detected. The same story for Chrome, if you request a desktop site it doesn't recognise it then either.
> 
> AFAIK, this is intended behavior. Setting a mobile browser to desktop mode changes the user agent so MobileDetect treats it as a desktop/laptop

Which would be fine, but isSafari() also doesn't seem to work whether mobile, iPad or macOS. As Safari is only available on iDevices these days I figured that would be a decent fallback but it looks like I need to get a bit more creative!

**Comment by serbanghita** [comment]
> Safari/Ipad: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

Looking at the provided UA, there is no way for the lib to detect that those are actually mobile devices.
