### ISSUE TITLE
Latest iPad versions are not detected as tablets in Safari browser

### ISSUE THREAD

**Issue by Razbash** [serbanghita/Mobile-Detect#886]
Hey!

The following iPad models are not detected as tablets in the Safari browser. Through the Google Chrome browser, everything is determined as it should:

iPad Pro 12.9 2020 v14.0
iPad Pro 12.9 2020 v13.4
iPad Pro 12.9 2021 v14.6
iPad 9th v15.1

**Comment by darapa1** [comment]
Hello @Razbash 

What is your UA string for one of the devices?

Guess your iPad is in default mode.
Desktop is default.
User has to change by its own to the Tablet UA string.

See: https://developer.apple.com/forums/thread/119186

Kind regards

**Comment by danilo900** [comment]
The latest iPad UA:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

**Comment by danilo900** [comment]
Searching for the web.
Newest ipad now has "request desktop website" by default.

We have to implement something like that:

https://developer.apple.com/forums/thread/119186?page=2

**Comment by serbanghita** [comment]
@Razbash from `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15` there is not way to determine that this is mobile.
@darapa1 thanks for pointing that out! Your reply is worthy of being put in the readme
@danilo900 thanks for sharing the UA
