### ISSUE TITLE
->isMobile() returns false for iPhone XS Max

### ISSUE THREAD

**Issue by cawhite78** [serbanghita/Mobile-Detect#889]
**Issue description**
The iPhone XS max returns false for ->isMobile().  This is the one iphone Apple made in 2017 that has the 6.46 screen size.

**User-Agent(s)**
Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1

**Suggestions**

**Comment by serbanghita** [comment]
@cawhite78 `Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1` returns `true` for both `isMobile` and `isiPhone()`. Are you sure the browser was not in desktop mode?
