### ISSUE TITLE
[NEW] Detect Device Details with Detective API

### ISSUE THREAD

**Issue by realtechspecs** [serbanghita/Mobile-Detect#891]
Hello Devs,

Detecting the device details of your users is now easier than ever with Detective API. Our API is powered by AI and makes detecting devices easy and effortless. Check it out [here](https://techspecs.readme.io/reference/introducing-techspecs-detective)

**Comment by ClearanceClarence** [comment]
The fact that the free service is limited to 100calls per day is reason enough to not use it

**Comment by serbanghita** [comment]
@realtechspecs good to know, I wish you great success with the solution!
@ClearanceClarence thanks for replying
