### ISSUE TITLE
The Huawei BG2-W09 (MediaPad T3 7.0) not as tablet #762

### ISSUE THREAD

**Issue by KateNaumova** [serbanghita/Mobile-Detect#897]
Hello,

The Huawei MediaPad T3 7.0  is recognized as a phone (by $detect->isMobile()), but not a tablet (by $detect->isTablet()). And it's a tablet.

**Issue description**

**User-Agent(s)**
Mozilla/5.0 (Linux; Android 6.0;BG2-W09 Build/HuaweiBAGGIO2) AppleWebKit...

Tablet models are : BG2-U01, BG2-W09, BG2-U03

Thanks

**Comment by serbanghita** [comment]
@KateNaumova thank you so much. Released in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.41
