### ISSUE TITLE
Not recognized operation systems and device types

### ISSUE THREAD

**Issue by mkenderaqu** [serbanghita/Mobile-Detect#898]
tablets are not correctly recognized as tablet:

Samsung Galaxy Tab S8 Ultra
`Mozilla/5.0 (Linux; Android 12; SM-X906C Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36`

Lenovo Yoga Tab 11
`Mozilla/5.0 (Linux; Android 11; Lenovo YT-J706X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

Operation system of Mac OS X is not recognized:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9`

Chrome os is not recognized:
`Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36`

**Comment by tcse** [comment]
Hello. Also does not recognize smart chxcs on Wear OS

Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-R875F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36

**Comment by serbanghita** [comment]
> tablets are not correctly recognized as tablet:
> 
> Samsung Galaxy Tab S8 Ultra `Mozilla/5.0 (Linux; Android 12; SM-X906C Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36`
> 
> Lenovo Yoga Tab 11 `Mozilla/5.0 (Linux; Android 11; Lenovo YT-J706X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

Addressed in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.41
👏 thank you so much!

> Operation system of Mac OS X is not recognized: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9`
> 
> Chrome os is not recognized: `Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36`

I've only focused the script to detect mobile stuff.

**Comment by serbanghita** [comment]
> Hello. Also does not recognize smart chxcs on Wear OS
> 
> Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-R875F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36

@tcse I haven't thought about adding support for watches/wearables. Is this actually helping someone?

**Comment by tcse** [comment]
Inside a Wear OS watch, a full-fledged Chrome-based web browser
They allow you to view sites, but in silence look very bad.

Even Google search results without adaptation are not very good.

And with the support of Wear OS, it will be possible to make up separate versions of the site just for easy viewing on the watch.

For example, this is how notifications on watches from social networks look like

Without the support of mobiledetect.php for smart watches, it will be extremely inconvenient to create websites that will be convenient to watch on the watch.



На русском:

Внутри часов на Wear OS полноценный веб-браузер на основе Chrome
Они позволяют просматривать сайты, но по-молчанию выглядеть очень плохо.

http://demo.mobiledetect.net <http://demo.mobiledetect.net/> 

 







Даже результаты поиска Google без адаптации не очень хорошо.






А при поддержке Wear OS можно будет верстать отдельные версии сайтом именно для удобного просмотра на часах.

Например вот так выглядят уведомления на часах из соцсетей






Или простейщая html страница с text-center 





Без поддержки работы mobiledetect.php для  смарт-часов верстать сайты которые будет удобно смотреть на часах  будет крайне неудобно.

**Comment by serbanghita** [comment]
> Inside a Wear OS watch, a full-fledged Chrome-based web browser They allow you to view sites, but in silence look very bad. Even Google search results without adaptation are not very good. And with the support of Wear OS, it will be possible to make up separate versions of the site just for easy viewing on the watch. For example, this is how notifications on watches from social networks look like Without the support of mobiledetect.php for smart watches, it will be extremely inconvenient to create websites that will be convenient to watch on the watch. 

@tcse this is actually very interesting and makes total sense to detect watches. They are mobile devices and the surface is so small that it clearly requires special formatting of text ... and media.

I opened an issue to further gather more info https://github.com/serbanghita/Mobile-Detect/issues/902
