### ISSUE TITLE
its not work when google chrome mobile browser is set to Desktop Version

### ISSUE THREAD

**Issue by shajiuddin** [serbanghita/Mobile-Detect#899]
its not work when google chrome mobile browser is set to Desktop Version

**Comment by ernestbuffington** [comment]
It thinks I'm on a tablet when in destop chrome...

**Comment by serbanghita** [comment]
We need the user-agent string in order to identify the issue.
You can use navigate to https://demo.mobiledetect.net/ and report the UA or copy paste it here.
