### ISSUE TITLE
Bad detection for recent Xiaomi browser

### ISSUE THREAD

**Issue by benland2** [serbanghita/Mobile-Detect#901]
The following user agent of Xiaomi mobile  is detected as PC:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/89.0.4389.116 Safari/534.24 XiaoMi/MiuiBrowser/12.13.2-gn

**Comment by serbanghita** [comment]
@benland2 problem here is that besides `XiaoMi/MiuiBrowser/12.13.2-gn` part, there is no indication of what type of device this is. Is this the browser https://play.google.com/store/apps/details?id=com.mi.globalbrowser&hl=en&gl=US ?
If this is only on mobile devices then I can add it to the list of mobile browsers

**Comment by benland2** [comment]
OK it means that my related user has enabled the Desktop Mode on his browser. Thank you for your investigation.
