### ISSUE TITLE
3.74.x releases

### ISSUE THREAD

**Issue by staabm** [serbanghita/Mobile-Detect#909]
**Issue description**

the readme talks about  a 3.74 release version meant for use with php 7.3+, but it seems there is no release yet for it?
how should we use the lib in version 3.74?

https://github.com/serbanghita/Mobile-Detect/blob/bfe08d83297c5578af1b0026cf5398f749b6aba4/README.md?plain=1#L37

side note: the line above links to a `7.x` branch which does not exist

**Comment by serbanghita** [comment]
@staabm not yet, I've asked the community how to proceed with the release [0] and I'm going to fix this today or tomorrow.
Thank you for pointing this out!

[0] https://github.com/serbanghita/Mobile-Detect/issues/904#issuecomment-1326150912

**Comment by serbanghita** [comment]
@staabm if you don't mind, can you tell me your use case of Mobile Detect? (if you have any)

**Comment by staabm** [comment]
we are using mobile detect to render different html for some mobile cases.

I was checking whether its supported for php8, as we are in the process of updating our servers.
most of our stuff is already responsive, but I was checking here to get a feeling whether we can update for php8 compat, or we need to rework everything based on this lib with responsive html in a hurry :).

so for the mid-time future I hope we can get rid of this lib. sorry to say that, but I think it should not be required in a modern stack at all.

thx for maintaining it so, it was of big help in the past.

**Comment by serbanghita** [comment]
> so for the mid-time future I hope we can get rid of this lib. sorry to say that, but I think it should not be required in a modern stack at all.

thanks for the use-case, I totally agree that this is not needed with good RWD

**Comment by serbanghita** [comment]
@staabm I've pushed the new tag https://github.com/serbanghita/Mobile-Detect/releases/tag/3.74.0
Working branch is https://github.com/serbanghita/Mobile-Detect/tree/7.x

**Comment by staabm** [comment]
@serbanghita thx for the fix. does the project readme need an update, since it only talks about php 8.0 compat?
