### ISSUE TITLE
Samsung Tab S8 Ultra tablet appears  as a mobile device

### ISSUE THREAD

**Issue by kilicabdulkadir** [serbanghita/Mobile-Detect#911]
My device's user agent is as follows
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

But my device appears as mobile even though it is a tablet. isTablet function returns false. How can i solve this problem

**Comment by serbanghita** [comment]
@kilicabdulkadir from the UA `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36` there is no hint that this is a tablet or a mobile device.
