### ISSUE TITLE
Samsung Galaxy Tab S8 series

### ISSUE THREAD

**Issue by travelcon-it** [serbanghita/Mobile-Detect#912]
Detection for the latest Samsung Tab S8 series is missing. Please add the following model names to $tabletDevices['SamsungTablet']

```SM-X700|SM-X706|SM-X706B|SM-X706U|SM-X706N|SM-X800|SM-X806|SM-X806B|SM-X806U|SM-X806N|SM-X900|SM-X906|SM-X906B|SM-X906U|SM-X906N```

Thanks in advance.

**Comment by linuxmobile** [comment]
Same problem here. S8 tab don't detect it

**Comment by serbanghita** [comment]
@travelcon-it thank you some much 🙇
