### ISSUE TITLE
Consider running 7x workflow against all supported PHP versions

### ISSUE THREAD

**Issue by acelaya** [serbanghita/Mobile-Detect#914]
I have noticed the `7x.yml` workflow only runs against PHP 7.4. I was thinking if you would be interested in making it run against PHP 8.0, 8.1 and 8.2 as well, to ensure compatibility with all supported versions.

I can provide a PR if so.

**Comment by serbanghita** [comment]
@acelaya thank you for mentioning this 

I have updated the workflows as such

https://github.com/serbanghita/Mobile-Detect/blob/2.8.x/.github/workflows/2.8.x-test.yml `php-version: ["5.3"]`
https://github.com/serbanghita/Mobile-Detect/blob/3.74.x/.github/workflows/3.74.x-test.yml `php-version: [7.4]`
https://github.com/serbanghita/Mobile-Detect/blob/4.8.x/.github/workflows/4.8.x-test.yml `php-version: [8.0, 8.1, 8.2]`

If you think this is not enough please let me know, thank you!
