### ISSUE TITLE
README correction

### ISSUE THREAD

**Issue by htasevsk1** [serbanghita/Mobile-Detect#920]
**Issue description**
In the README file it says that version 3.74.x is compatible for PHP versions >=7.3,<8.0, but in [packagist](https://packagist.org/packages/mobiledetect/mobiledetectlib) it is specified that this version requires php: >=7.4.

So when I tried to require it, I got: 
`mobiledetect/mobiledetectlib 3.74.0 requires php >=7.4 -> your php version (7.3; overridden via config.platform, actual: 7.3.31) does not satisfy that requirement. `

**User-Agent(s)**

**Suggestions**
In the README file it should say that version 3.74.x is compatible for PHP versions >=**7.4**,<8.0

**Comment by epsilon-5** [comment]
Yes it does not work in php 7.3.

**Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)**
line 249: `protected array $cache = [];`

**Comment by serbanghita** [comment]
Fixed in both 4.8.x README.md and also 3.74.x

@htasevsk1 @epsilon-5 thank you! 🙇
