### ISSUE TITLE
User Agents from iOS and Android apps do not detect

### ISSUE THREAD

**Issue by ghost** [serbanghita/Mobile-Detect#925]
**Issue description**

If an iOS or Android app makes a request (instead of the request going through a mobile browser), its user agent will be different.

These app user agents do not yet match any rules.

**User-Agent(s)**

iOS: `MeqMobile/126 CFNetwork/1406.0.4 Darwin/22.4.0` (where "MeqMobile" is the app id)

Android: `okhttp/4.9.2`

**Suggestions**

Add patterns to detect these user agents.

Perhaps also add a "isApp" method to say if the request was from an app vs a browser.

**Comment by pquerner** [comment]
If you have control over the app's UA you should handle that, it should'nt be part of the library here I think.
Although it could be made easier to extend stuff, ie. see #928
