### ISSUE TITLE
Use getters (ie. getTabletDevices())

### ISSUE THREAD

**Issue by pquerner** [serbanghita/Mobile-Detect#928]
(Using version 2.8.34)

We have getters like `public static function getTabletDevices()` but they dont seem to be used; which makes it hard to overwrite, or add stuff to the big regex data arrays, for instance `protected static $tabletDevices`.

If we want to extend the class `Mobile_Detect` and add to the `$tabletDevices` data array by extending `getTabletDevices` it would be the easiest way.

Ie this:

```
foreach (self::$tabletDevices as $_regex) {
            if ($this->match($_regex, $userAgent)) {
                return true;
            }
        }
```

changes to

```
foreach (static::getTabletDevices() as $_regex) {
    if ($this->match($_regex, $userAgent)) {
        return true;
    }
}
```

And then the extending class can overwrite `getTabletDevices` properly.

**Comment by serbanghita** [comment]
@pquerner you have a point, can you submit a PR? Are you using PHP5?

**Comment by pquerner** [comment]
Yes I can give you a PR. I'll do that in the coming days.
I have an application stuck on PHP 7.0 for now, hence why I am on the 2.x Branch. :(

**Comment by serbanghita** [comment]
@pquerner 👍 I made changes to `3.74.x` branch and will publish soon

**Comment by pquerner** [comment]
@serbanghita I saw. I commented on the commit, can you check it please?
