### ISSUE TITLE
MD v 3.74 - PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in Mobile_Detect.php on line 245

### ISSUE THREAD

**Issue by dogslife** [serbanghita/Mobile-Detect#933]
As per title - MD v 3.74 - PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in Mobile_Detect.php on line 245

Have experienced this on two separate hosting environment thus far.

**Comment by serbanghita** [comment]
@dogslife when running MD 3.74 you need PHP >=7.4
If that's not possible use the releases from https://github.com/serbanghita/Mobile-Detect/tree/2.8.x
