### ISSUE TITLE
4.8.x

### ISSUE THREAD

**Issue by serbanghita** [serbanghita/Mobile-Detect#938]
- [x] Support for PHP>=8.x
- [x] PSR-16 cache support https://github.com/php-fig/simple-cache
- [x] Run benchmark tests https://github.com/phpbench/phpbench
- [x] Establish perf tests baselines
- [x] Split regex strings into array of strings 
- [x] Run before/after per tests
- [x] Git hooks: lint and run tests
- [ ] Implement ReadTheDocs? Example: https://phpbench.readthedocs.io/en/latest/

**Comment by serbanghita** [comment]
Released https://github.com/serbanghita/Mobile-Detect/releases/tag/4.8.01

**Comment by acelaya** [comment]
Just out of curiosity. Why did you jump directly to v4.8.x and skipped everything between 4.0.x and 4.7.x?

**Comment by serbanghita** [comment]
@acelaya I tried to somehow reflect the supported PHP version

2.x - already supported PHP 5.3 so no change there
3.**74**.x - because it supports PHP 7.4
and lastly
4.**8**.x - because it supports PHP 8.0

looking in retrospect, this is kind of dumb but I can't go back right now :))

**Comment by acelaya** [comment]
I see 😅
