### ISSUE TITLE
Restore implicit use of `HTTP_USER_AGENT` in 4.8.x branch 

### ISSUE THREAD

**Issue by ADmad** [serbanghita/Mobile-Detect#941]
`4.8` removed the automatic use of `$_SERVER['HTTP_USER_AGENT']` and requires one to explicitly set the User-Agent string.

This hinders usability IMHO as in majority of the use case that's the value users will have to get explicitly.

So I suggest re-introducing the implicit use of  `$_SERVER['HTTP_USER_AGENT']` if the User-Agent  string is not explicit set.

**Comment by serbanghita** [comment]
@ADmad taking a look today at this, probably I forgot this code + tests

**Comment by serbanghita** [comment]
I checked and forgot to put the fallback to `setHttpHeaders` which sets the userAgent from HTTP headers. Will provide a patch after work. 👍 🙇

**Comment by serbanghita** [comment]
@ADmad done in https://github.com/serbanghita/Mobile-Detect/releases/tag/4.8.03
thanks a lot for the input!
