### ISSUE TITLE
[bug] breaking change pushed as patch

### ISSUE THREAD

**Issue by KumaVolt** [serbanghita/Mobile-Detect#947]
**Describe the bug**
The PHP version composer requirements has been changed from '>= 5.6.*' to 5.6.0.  

Breaking change introduced as patch in version:
2.8.42

commit reference:
https://github.com/serbanghita/Mobile-Detect/commit/091c628c164f920dedd512b3100bf485b9371c6b

**Comment by KumaVolt** [comment]
Issue has been reflected to [laravel/jetstream](https://github.com/laravel/jetstream/issues/1394) package

**Comment by serbanghita** [comment]
@KumaVolt thank you, I am reverting in the next minor version. Indeed this was a breaking change that I completely overlooked 🙇

**Comment by serbanghita** [comment]
Done in https://github.com/serbanghita/Mobile-Detect/releases/tag/2.8.43
