### ISSUE TITLE
Class "Detection\MobileDetect" not found

### ISSUE THREAD

**Issue by devajmeireles** [serbanghita/Mobile-Detect#964]
Trying to use it with Laravel 11:

Error:
![CleanShot 2024-09-15 at 01 01 32](https://github.com/user-attachments/assets/66140a27-d6fa-45a4-bf6a-ff810dd84af8)

Usage:
![CleanShot 2024-09-15 at 01 02 01](https://github.com/user-attachments/assets/9f80f2e2-ca4c-48b0-a683-736e7f311dc6)

**Comment by serbanghita** [comment]
@devajmeireles what was the problem?
