### ISSUE TITLE
Manual use of 4.8.x lib

### ISSUE THREAD

**Issue by FranciscoFernandezA** [serbanghita/Mobile-Detect#970]
Hello,

I've been trying to access the API from the MobileDetect repository version 4.8.x using the same approach as in version 3.74.x (3.7 is workig but will be nice use the las version), by referencing the namespace. However, I'm unable to get it to work in 4.8.x.

I don't use Composer on my server, so I am manually including the files. Could you please advise on what I need to do differently in version 4.8.x to properly load and use the API without Composer? Any guidance on how to handle this in a non-Composer environment would be greatly appreciated.

Thank you for your help!

**Comment by Apollodore** [comment]
Hello, yes it would really be great dear Şerban Ghiţă!

**Comment by sanchezzzhak** [comment]
register custom autoload class for spl_autoload_register

create autoload.php file in lib dir

```php
function md_autoload(string $classname) {
    if (false === strpos($classname, 'Detection\\')) {
        return;
    }
    $namespaceMap = ['Detection\\' => __DIR__ . '/src'];
    foreach ($namespaceMap as $prefix => $dir) {
        $path = str_replace([$prefix, '\\'], [$dir, '/'], $classname);
        $path .= '.php';
        if (file_exists($path)) {
            include $path;
        }
    }
}
spl_autoload_register('md_autoload');
```
include once autoload.php for use Detection before.

further work with the library will be the same as in the documentation

use Detection\MobileDetect;
$detect = new MobileDetect();

**Comment by serbanghita** [comment]
Related to https://github.com/serbanghita/Mobile-Detect/issues/973

@FranciscoFernandezA the only reason why this can't be used standalone is because of the Cache. I'm looking into this.
@sanchezzzhak that's a good start, problem is with the `"psr/simple-cache": "^3",  "psr/cache": "^3.0"` deps. Since these are not into the repository, you can't just download the Mobile Detect repo and start using it. Kind of frustrating ...

**Comment by serbanghita** [comment]
@sanchezzzhak thanks a lot for the suggestion. I pushed into `4.8.x` branch:
https://github.com/serbanghita/Mobile-Detect/tree/4.8.x/standalone
https://github.com/serbanghita/Mobile-Detect/blob/4.8.x/src/MobileDetectStandalone.php

@FranciscoFernandezA check https://docs.mobiledetect.net/home/usage-1 and tell me if it works for you. Let me know if this works for you
