### ISSUE TITLE
How to use the 4.8.086

### ISSUE THREAD

**Issue by BackuPs** [serbanghita/Mobile-Detect#973]
I have uploaded the file from the src folder into a folder called 

\plugins\mobile-detect

see image

![afbeelding](https://github.com/user-attachments/assets/da7db6cc-48f3-4c87-9ea7-46707812ad18)

I load the main file as follow

`

		if (!class_exists('\Detection\MobileDetect')) {
			require_once (THEME_PLUGINS . '/mobile-detect/MobileDetect.php');
		}

`

The moment i  add this  $detect = new \Detection\MobileDetect;

i get a fatal error

Fatal error: Uncaught Error: Class "Detection\Cache\Cache" not found in /var/docs/public/wp-content/themes/twentytwentyfive/framework/plugins/mobile-detect/MobileDetect.php:1036 Stack trace: #0 /var/docs/public/wp-content/themes/twentytwentyfive/functions.php(33): Detection\MobileDetect->__construct() #1 /var/docs/public/wp-settings.php(685): include('...') #2 /var/docs/public/wp-config.php(97): require_once('...') #3 /var/docs/public/wp-load.php(50): require_once('...') #4 /var/docs/public/wp-admin/admin.php(34): require_once('...') #5 /var/docs/public/wp-admin/update-core.php(10): require_once('...') #6 {main} thrown in /var/docs/public/wp-content/themes/twentytwentyfive/framework/plugins/mobile-detect/MobileDetect.php on line 1036

What am i doing wrong here?

all seems to be ok

**Comment by BackuPs** [comment]
Can you please create a build without psr and cache?

**Comment by serbanghita** [comment]
@BackuPs are you saying that you don't want to use composer right? You're looking for a way to use this standalone?

ps: I need these clarifications since PHP is no longer my primary language and I'm catching up to the ecosystem

**Comment by BackuPs** [comment]
Correct i dont use composer, nor do i need the caching or the psr. Like many plugins and themes used todo they just included the mobiledetect.php file.  Now i have to edit the file and remove all the code/abilities i do not need.

**Comment by serbanghita** [comment]
@BackuPs check https://docs.mobiledetect.net/home/usage-standalone and tell me if it works for you

**Comment by BackuPs** [comment]
Thank that works for me.  Although i prefer to use it like this.


        if (class_exists('\Detection\MobileDetectStandalone')) {
            $detection = new \Detection\MobileDetectStandalone;
            $detection->setUserAgent('iPad');

            try {
                var_dump($detection);
                var_dump($detection->isMobile());
            } catch (MobileDetectException $e) {
                print_r($e);
            }
        }

**Comment by serbanghita** [comment]
@BackuPs I'll add `class_exists('\Detection\MobileDetectStandalone')` as a recommendation, it looks like a good safety feature

**Comment by BackuPs** [comment]
Thank you for your kind and fast support. It is appreciated.
